// @generated by tools/spec-gen.ts from specs/notifier.pkl — DO NOT EDIT
// テストを直したくなったら specs/ を編集して `just spec-gen` を実行する。
// Tauri IPCをmockしたrenderer統合テスト。Rust commandやOS通知を通った証明にはしない(docs/E2E.md)。
// 実行: just renderer-test (Playwright / WebKit)

import { expect, test } from "@playwright/test";
import { bootConsole, calls } from "./harness";

// RND-001: パレットはどこでも打鍵で開いて入力を引き継ぎ、Escで閉じ、一覧画面のEscは条件クリアを呼び、IME変換中のEnterは適用せず、確定後のEnterは候補を適用して開いたまま連続入力できる(renderer統合)
test("RND-001 palette keyboard", async ({ page }) => {
  await bootConsole(page);
  // どこでも打鍵で開き、入力を引き継ぐ
  await page.keyboard.press("s");
  await expect(page.locator("#palette-overlay")).toBeVisible();
  await expect(page.locator("#palette-input")).toHaveValue("s");
  // Escで閉じる
  await page.keyboard.press("Escape");
  await expect(page.locator("#palette-overlay")).toBeHidden();
  // パレットが閉じた一覧画面のEscは条件クリア(CLR-001の結線)
  await page.keyboard.press("Escape");
  await expect(page.locator("#rail-msg")).toHaveText("ルールを既定に戻した");
  expect((await calls(page)).some((entry) => entry.cmd === "clear_filter")).toBe(true);
  // IME変換中(composition中)のEnterは候補を適用しない
  await page.keyboard.press("a");
  await expect(page.locator("#palette-overlay")).toBeVisible();
  await page.locator("#palette-input").dispatchEvent("compositionstart");
  const appliedBefore = (await calls(page)).filter((entry) => entry.cmd === "apply_candidate").length;
  await page.keyboard.press("Enter");
  expect((await calls(page)).filter((entry) => entry.cmd === "apply_candidate").length).toBe(appliedBefore);
  await page.locator("#palette-input").dispatchEvent("compositionend");
  // 確定後のEnterは候補を適用し、開いたままクエリだけリセット(連続入力)
  await page.locator("#palette-input").fill("axi");
  await page.keyboard.press("Enter");
  const applied = (await calls(page)).filter((entry) => entry.cmd === "apply_candidate");
  expect(applied.length).toBe(appliedBefore + 1);
  expect(applied[applied.length - 1].args.id).toBe("tier:Axi");
  await expect(page.locator("#palette-overlay")).toBeVisible();
  await expect(page.locator("#palette-input")).toHaveValue("");
});

// RND-002: Webhook URL入力直後のTEST DELIVERYは、遅延保存を先にflushしてから通知テストを実行する(renderer統合)
test("RND-002 delivery flush", async ({ page }) => {
  await bootConsole(page);
  await page.locator("#delivery-tab").click();
  await page.locator("#webhook-input").fill("https://discord.com/api/webhooks/1/tok");
  await page.locator("#test-btn").click();
  await expect(page.locator("#rail-msg")).toHaveText(/通知要求/);
  const sequence = await calls(page);
  const saveIndex = sequence.findIndex(
    (entry) =>
      entry.cmd === "set_config" &&
      entry.args.config.discordWebhookUrl === "https://discord.com/api/webhooks/1/tok",
  );
  const testIndex = sequence.findIndex((entry) => entry.cmd === "test_notification");
  expect(saveIndex).toBeGreaterThanOrEqual(0);
  expect(testIndex).toBeGreaterThan(saveIndex);
});

// RND-003: ルール行のenabled切替はset_rule_enabledだけを呼びedit focus表示を変えず、行本体はパレットを開くだけで切替を呼ばない。全ルール無効では一覧とステータスバーにNO ENABLED表示が出る(renderer統合)
test("RND-003 toggle vs edit focus", async ({ page }) => {
  await bootConsole(page);
  const editingBefore = await page.locator("#editing-meta").textContent();
  // enabled切替はset_rule_enabledだけを呼び、edit focus表示もパレットも動かさない
  await page.locator(".rule-toggle").click();
  const toggles = (await calls(page)).filter((entry) => entry.cmd === "set_rule_enabled");
  expect(toggles.length).toBe(1);
  expect(toggles[0].args).toEqual({ index: 0, enabled: false });
  await expect(page.locator("#editing-meta")).toHaveText(editingBefore ?? "");
  await expect(page.locator("#palette-overlay")).toBeHidden();
  // 行本体はパレットを開くだけで切替を呼ばない
  await page.locator(".rule-edit").click();
  await expect(page.locator("#palette-overlay")).toBeVisible();
  expect((await calls(page)).filter((entry) => entry.cmd === "set_rule_enabled").length).toBe(1);
});

// RND-003: ルール行のenabled切替はset_rule_enabledだけを呼びedit focus表示を変えず、行本体はパレットを開くだけで切替を呼ばない。全ルール無効では一覧とステータスバーにNO ENABLED表示が出る(renderer統合) (全ルール無効の明示)
test("RND-003 all rules disabled", async ({ page }) => {
  await bootConsole(page, { allRulesDisabled: true });
  await expect(page.locator("#fissure-rows td.empty")).toHaveText("NO ENABLED NOTIFICATION RULES");
  await expect(page.locator("#sb-watch")).toHaveText("WATCH: NO ENABLED NOTIFICATION RULES");
});

// RND-004: 最小720x480でも右サイドバーは縦スクロールなしでルールnavigator・NEW/DEL/CLEAR・5軸launcher・配送設定・TEST/PAUSE・時間設定へ到達でき、launcherはパレットをその軸に絞って開く(renderer統合)
test("RND-004 sidebar fits minimum window", async ({ page }) => {
  await page.setViewportSize({ width: 720, height: 480 });
  await bootConsole(page);
  const railFits = () =>
    page.locator(".rail").evaluate((el) => el.scrollHeight <= el.clientHeight);
  expect(await railFits()).toBe(true);
  // FILTERSタブ: ルールnavigator・NEW/DEL/CLEAR・5軸launcherへ到達できる
  await expect(page.locator(".rule-focus")).toBeVisible();
  for (const id of ["rule-new", "rule-del", "clear-btn"]) {
    await expect(page.locator("#" + id)).toBeVisible();
  }
  for (const id of ["tier-checks", "mode-checks", "storm-checks", "mission-checks", "planet-checks"]) {
    await expect(page.locator("#" + id)).toBeVisible();
  }
  // launcherは既存パレットをその軸に絞って開く
  await page.locator("#mission-checks").click();
  await expect(page.locator("#palette-overlay")).toBeVisible();
  await expect(page.locator("#palette-rule")).toContainText("MISSION");
  const facets = await page.locator("#palette-cands .cand .facet").allTextContents();
  expect(facets.length).toBeGreaterThan(0);
  expect(facets.every((facet) => facet === "MISSION")).toBe(true);
  await page.keyboard.press("Escape");
  // DELIVERYタブ: 配送先・TEST・時間設定・PAUSEへ到達できる
  await page.locator("#delivery-tab").click();
  for (const id of ["desktop-check", "webhook-input", "test-btn", "minremain-input", "poll-input", "pause-btn"]) {
    await expect(page.locator("#" + id)).toBeVisible();
  }
  expect(await railFits()).toBe(true);
  // 既定サイズでも縦スクロールを必要としない
  await page.setViewportSize({ width: 960, height: 620 });
  expect(await railFits()).toBe(true);
});

// RND-005: 亀裂表はviewport 950pxで7列1段、949px以下で2段gridへ切り替わり、720/800/949pxで横スクロールを生まず、MODEとSTORMは独立セル、長い値はellipsisしてもDOM全文と行tooltipを保持し、empty rowは全幅、ヘッダはsticky、th[scope=col]は7個(renderer統合)
test("RND-005 compact table breakpoints", async ({ page }) => {
  await page.setViewportSize({ width: 950, height: 620 });
  await bootConsole(page);
  await expect(page.locator("th[scope=col]")).toHaveCount(7);
  const firstRow = page.locator("#fissure-rows tr").first();
  // 950px(表領域740px)では7列1段のtable表示を維持する
  expect(await firstRow.evaluate((el) => getComputedStyle(el).display)).toBe("table-row");
  for (const width of [949, 800, 720]) {
    await page.setViewportSize({ width, height: 620 });
    // 2段gridへ切り替わる
    expect(await firstRow.evaluate((el) => getComputedStyle(el).display)).toBe("grid");
    // 横スクロールを必要としない
    expect(await page.locator(".tablewrap").evaluate((el) => el.scrollWidth <= el.clientWidth)).toBe(true);
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    // ヘッダはsticky
    expect(await page.locator("thead").evaluate((el) => getComputedStyle(el).position)).toBe("sticky");
  }
  // MODEとSTORMは別セル・別ラベルのまま
  const stormRow = page.locator("#fissure-rows tr", { hasText: "Nsu Grid" });
  await expect(stormRow.locator(".col-mode .flag")).toHaveText(/HARD/);
  await expect(stormRow.locator(".col-storm .flag")).toHaveText(/STORM/);
  // 長い値はellipsisしてもDOM上の全文と行tooltipを保持する
  const longRow = page.locator("#fissure-rows tr", { hasText: "Taveuni" });
  await expect(longRow.locator(".col-node .icon-label > span:last-child")).toHaveText(
    "Taveuni (Kuva Fortress)",
  );
  expect(await longRow.getAttribute("title")).toContain("Taveuni (Kuva Fortress)");
});

// RND-005: 亀裂表はviewport 950pxで7列1段、949px以下で2段gridへ切り替わり、720/800/949pxで横スクロールを生まず、MODEとSTORMは独立セル、長い値はellipsisしてもDOM全文と行tooltipを保持し、empty rowは全幅、ヘッダはsticky、th[scope=col]は7個(renderer統合) (empty rowの全幅表示)
test("RND-005 empty row spans full width", async ({ page }) => {
  await page.setViewportSize({ width: 720, height: 480 });
  await bootConsole(page, { allRulesDisabled: true });
  const spansFullWidth = await page.locator("#fissure-rows td.empty").evaluate((el) => {
    const row = el.closest("tr");
    if (!row) return false;
    return Math.abs(el.getBoundingClientRect().width - row.getBoundingClientRect().width) <= 1;
  });
  expect(spansFullWidth).toBe(true);
});
