// @generated by tools/spec-gen.ts from specs/notifier.pkl — DO NOT EDIT
// テストを直したくなったら specs/ を編集して `just spec-gen` を実行する。
// Tauri IPCをmockしたrenderer統合テスト。Rust commandやOS通知を通った証明にはしない(docs/E2E.md)。
// 実行: just renderer-test (Playwright / WebKit)

import { expect, test } from "@playwright/test";
import { bootConsole, calls } from "./harness";

// RND-001: パレットはどこでも打鍵で開いて入力を引き継ぎ、Escで閉じ、一覧画面のEscは設定を変更しない(リセットはCLEARボタン/パレット候補のみ)。一覧画面のSpaceはパレットを開かずに編集中ルールの表示選択(enabled)をトグルし(action:toggle-rule)、一覧画面の↑/↓はedit focusを前後のルールへ巡回移動し、Ctrl+1..9は対応indexのルールへedit focusを移す(パレット表示中も有効。フォーカス移動は設定を変更しない)。Cmd+1..9は9個のコンテンツタブ専用でルールを変更しない。IME変換中のEnterは適用せず、確定後のEnterは候補を適用して開いたまま連続入力でき、DESELECT ALL RULES候補は全表示選択を解除して通知参加を変えない(renderer統合)
test("RND-001 palette keyboard", async ({ page }) => {
  await bootConsole(page);
  // どこでも打鍵で開き、入力を引き継ぐ
  await page.keyboard.press("s");
  await expect(page.locator("#palette-overlay")).toBeVisible();
  await expect(page.locator("#palette-input")).toHaveValue("s");
  // Escで閉じる
  await page.keyboard.press("Escape");
  await expect(page.locator("#palette-overlay")).toBeHidden();
  // 一覧画面のEscは設定を変更しない(リセットはCLEARボタン/パレット候補のみ)
  await page.keyboard.press("Escape");
  await expect(page.locator("#rules-meta")).toHaveText("1/2 VIEW");
  expect((await calls(page)).some((entry) => entry.cmd === "clear_filter")).toBe(false);
  // 一覧画面のSpaceはパレットを開かず、編集中ルールのVIEW選択(enabled)をトグルする
  await page.keyboard.press(" ");
  await expect(page.locator("#palette-overlay")).toBeHidden();
  await expect(page.locator("#rules-meta")).toHaveText("0/2 VIEW");
  await expect(page.locator(".rule-row .rule-toggle").first()).toHaveText("[ ]");
  expect(
    (await calls(page)).filter(
      (entry) => entry.cmd === "apply_candidate" && entry.args.id === "action:toggle-rule",
    ).length,
  ).toBe(1);
  // 再度Spaceで元に戻る(トグル)
  await page.keyboard.press(" ");
  await expect(page.locator("#rules-meta")).toHaveText("1/2 VIEW");
  await expect(page.locator(".rule-row .rule-toggle").first()).toHaveText("[x]");
  // DESELECT ALL RULESは全VIEW選択だけを解除し、notify・ルール数・edit focusを保持する
  await page.keyboard.press("d");
  await page.locator("#palette-input").fill("deselect all rules");
  await page.keyboard.press("Enter");
  await expect(page.locator("#rules-meta")).toHaveText("0/2 VIEW");
  await expect(page.locator("#rules-list .rule-row")).toHaveCount(2);
  await expect(page.locator(".rule-row .rule-toggle").first()).toHaveText("[ ]");
  await expect(page.locator(".rule-row .rule-toggle").nth(1)).toHaveText("[ ]");
  await expect(page.locator(".rule-row .rule-notify").first()).toHaveAttribute("aria-pressed", "true");
  await expect(page.locator(".rule-row .rule-notify").nth(1)).toHaveAttribute("aria-pressed", "true");
  await expect(page.locator("#editing-meta")).toHaveText("R1/2");
  await expect(page.locator("#sb-watch")).toHaveText("WATCH: 2 RULES");
  const deselectCalls = (await calls(page)).filter(
    (entry) => entry.cmd === "apply_candidate" && entry.args.id === "action:deselect-all-rules",
  );
  expect(deselectCalls).toHaveLength(1);
  expect((await calls(page)).some((entry) => entry.cmd === "set_rule_notify")).toBe(false);
  expect((await calls(page)).some((entry) => entry.cmd === "clear_filter")).toBe(false);
  await page.keyboard.press("Escape");
  await expect(page.locator("#palette-overlay")).toBeHidden();
  // 一覧画面の↑/↓はedit focusを前後のルールへ巡回移動する(設定は変更しない)
  const mutations = async () =>
    (await calls(page)).filter(
      (entry) => entry.cmd === "set_config" || entry.cmd === "set_rule_enabled",
    ).length;
  const mutationsBefore = await mutations();
  await page.keyboard.press("ArrowDown");
  await expect(page.locator("#editing-meta")).toHaveText("R2/2");
  await expect(page.locator(".rule-row").nth(1)).toHaveClass(/rule-focus/);
  await page.keyboard.press("ArrowDown");
  await expect(page.locator("#editing-meta")).toHaveText("R1/2");
  await page.keyboard.press("ArrowUp");
  await expect(page.locator("#editing-meta")).toHaveText("R2/2");
  // Ctrl+1..9は対応indexのルールへ直接ジャンプする。Cmd+数字はコンテンツタブ専用
  await page.keyboard.press("Control+1");
  await expect(page.locator("#editing-meta")).toHaveText("R1/2");
  expect(await mutations()).toBe(mutationsBefore);
  // Cmd+1..9はコンテンツタブ専用で、rule edit focus・設定を変更しない。
  await page.keyboard.press("Meta+9");
  await expect(page.locator('#content-tabs [aria-selected="true"]')).toHaveAttribute(
    "data-tab-id",
    "descendia",
  );
  await expect(page.locator("#editing-meta")).toHaveText("R1/2");
  expect(await mutations()).toBe(mutationsBefore);
  await page.keyboard.press("Meta+1");
  await expect(page.locator('#content-tabs [aria-selected="true"]')).toHaveAttribute(
    "data-tab-id",
    "fissures",
  );
  // IME変換中(composition中)のEnterは候補を適用しない
  await page.keyboard.press("a");
  await expect(page.locator("#palette-overlay")).toBeVisible();
  await page.locator("#palette-input").dispatchEvent("compositionstart");
  const appliedBefore = (await calls(page)).filter((entry) => entry.cmd === "apply_candidate").length;
  await page.keyboard.press("Enter");
  expect((await calls(page)).filter((entry) => entry.cmd === "apply_candidate").length).toBe(appliedBefore);
  await page.locator("#palette-input").dispatchEvent("compositionend");
  // 確定後のEnterは候補を適用し、開いたままクエリだけリセット(連続入力)
  await page.locator("#palette-input").fill("axi");
  await page.keyboard.press("Enter");
  const applied = (await calls(page)).filter((entry) => entry.cmd === "apply_candidate");
  expect(applied.length).toBe(appliedBefore + 1);
  expect(applied[applied.length - 1].args.id).toBe("tier:Axi");
  await expect(page.locator("#palette-overlay")).toBeVisible();
  await expect(page.locator("#palette-input")).toHaveValue("");
  // パレット表示中もCtrl+数字で編集対象を切り替えられる(開いたまま)
  await page.keyboard.press("Control+2");
  await expect(page.locator("#palette-rule")).toContainText("EDIT R2");
  await expect(page.locator("#palette-overlay")).toBeVisible();
});

// RND-002: Webhook URL入力直後のTEST DELIVERYは、遅延保存を先にflushしてから通知テストを実行する(renderer統合)
test("RND-002 delivery flush", async ({ page }) => {
  await bootConsole(page);
  await page.locator("#delivery-tab").click();
  await page.locator("#webhook-input").fill("https://discord.com/api/webhooks/1/tok");
  await page.locator("#test-btn").click();
  await expect(page.locator("#rail-msg")).toHaveText(/通知要求/);
  const sequence = await calls(page);
  const saveIndex = sequence.findIndex(
    (entry) =>
      entry.cmd === "set_config" &&
      entry.args.config.discordWebhookUrl === "https://discord.com/api/webhooks/1/tok",
  );
  const testIndex = sequence.findIndex((entry) => entry.cmd === "test_notification");
  expect(saveIndex).toBeGreaterThanOrEqual(0);
  expect(testIndex).toBeGreaterThan(saveIndex);
});

// RND-003: ルール行のenabled切替は一覧表示だけを変えるset_rule_enabledを呼びedit focus・notifyを変えず、行のnotify切替はset_rule_notifyだけを呼びenabledもedit focusも変えず、行本体はedit focusをそのルールへ移すだけでパレットも切替も呼ばない。DEL/CLEARは2度押し確認で、1クリック目はSURE?表示になるだけで実行せず、2秒で自動復帰し、SURE?表示中のクリックだけが実行する。全ルールの表示選択を解除しても一覧は全亀裂を表示し、notify=trueのルールはWATCH表示と通知参加を維持する(renderer統合)
test("RND-003 toggle vs edit focus", async ({ page }) => {
  await bootConsole(page);
  const editingBefore = await page.locator("#editing-meta").textContent();
  // VIEW選択(enabled)切替はset_rule_enabledだけを呼び、notify・edit focus・パレットを動かさない
  await page.locator(".rule-row .rule-toggle").first().click();
  const toggles = (await calls(page)).filter((entry) => entry.cmd === "set_rule_enabled");
  expect(toggles.length).toBe(1);
  expect(toggles[0].args).toEqual({ index: 0, enabled: false });
  await expect(page.locator(".rule-row .rule-notify").first()).toHaveAttribute("aria-pressed", "true");
  await expect(page.locator("#editing-meta")).toHaveText(editingBefore ?? "");
  await expect(page.locator("#palette-overlay")).toBeHidden();
  // notify切替はset_rule_notifyだけを呼び、VIEW選択(enabled)もedit focusも変えない
  await page.locator(".rule-row .rule-notify").first().click();
  const notifies = (await calls(page)).filter((entry) => entry.cmd === "set_rule_notify");
  expect(notifies.length).toBe(1);
  expect(notifies[0].args).toEqual({ index: 0, notify: false });
  await expect(page.locator(".rule-row .rule-notify").first()).toHaveAttribute("aria-pressed", "false");
  expect((await calls(page)).filter((entry) => entry.cmd === "set_rule_enabled").length).toBe(1);
  await expect(page.locator("#editing-meta")).toHaveText(editingBefore ?? "");
  // 行本体はedit focusをそのルールへ移すだけで、パレットも切替も呼ばない
  await page.locator(".rule-row .rule-edit").nth(1).click();
  await expect(page.locator("#editing-meta")).toHaveText("R2/2");
  await expect(page.locator(".rule-row").nth(1)).toHaveClass(/rule-focus/);
  await expect(page.locator("#palette-overlay")).toBeHidden();
  expect((await calls(page)).filter((entry) => entry.cmd === "set_rule_enabled").length).toBe(1);
  // DEL/CLEARは2度押し確認: 1クリック目はSURE?表示になるだけで実行しない
  await page.locator("#rule-del").click();
  await expect(page.locator("#rule-del")).toHaveText("SURE?");
  const delCalls = async () =>
    (await calls(page)).filter(
      (entry) => entry.cmd === "apply_candidate" && entry.args.id === "action:delete-rule",
    ).length;
  expect(await delCalls()).toBe(0);
  // 2秒で自動復帰する
  await expect(page.locator("#rule-del")).not.toHaveText("SURE?", { timeout: 4000 });
  expect(await delCalls()).toBe(0);
  // SURE?表示中のクリックだけが実行する
  await page.locator("#rule-del").click();
  await page.locator("#rule-del").click();
  await expect.poll(delCalls).toBe(1);
  await expect(page.locator("#rules-list .rule-row")).toHaveCount(1);
  // CLEARも同じ2度押し(1クリック目は実行しない)
  await page.locator("#clear-btn").click();
  await expect(page.locator("#clear-btn")).toHaveText("SURE?");
  expect((await calls(page)).some((entry) => entry.cmd === "clear_filter")).toBe(false);
});

// RND-003: ルール行のenabled切替は一覧表示だけを変えるset_rule_enabledを呼びedit focus・notifyを変えず、行のnotify切替はset_rule_notifyだけを呼びenabledもedit focusも変えず、行本体はedit focusをそのルールへ移すだけでパレットも切替も呼ばない。DEL/CLEARは2度押し確認で、1クリック目はSURE?表示になるだけで実行せず、2秒で自動復帰し、SURE?表示中のクリックだけが実行する。全ルールの表示選択を解除しても一覧は全亀裂を表示し、notify=trueのルールはWATCH表示と通知参加を維持する(renderer統合) (全ルールのVIEW選択解除)
test("RND-003 all rules view off", async ({ page }) => {
  await bootConsole(page, { allRulesDisabled: true });
  // VIEW無指定でも一覧は全亀裂を表示し、notify=trueルールのWATCHは継続する
  await expect(page.locator("#fissure-rows tr")).toHaveCount(3);
  await expect(page.locator("#fissure-rows td.empty")).toHaveCount(0);
  await expect(page.locator("#rules-meta")).toHaveText("0/2 VIEW");
  await expect(page.locator("#sb-watch")).toHaveText("WATCH: 2 RULES");
  await expect(page.locator(".rule-row .rule-notify").first()).toHaveAttribute("aria-pressed", "true");
});

// RND-004: 最小720x480でも右サイドバーは縦スクロールなしでルール一覧・NEW/DEL/CLEAR・6軸launcher(レリック/モード/VOID嵐/ミッション/惑星/勢力)・配送設定・TEST/PAUSE・時間設定へ到達でき、ルール一覧はrail高さの固定比率領域に全ルール行を保持して内側だけ縦スクロールし、launcherはパレットをその軸に絞って開く(renderer統合)
test("RND-004 sidebar fits minimum window", async ({ page }) => {
  await page.setViewportSize({ width: 720, height: 480 });
  await bootConsole(page);
  const railFits = () =>
    page.locator(".rail").evaluate((el) => el.scrollHeight <= el.clientHeight);
  expect(await railFits()).toBe(true);
  // FILTERSタブ: ルール一覧・NEW/DEL/CLEAR・5軸launcherへ到達できる
  await expect(page.locator(".rule-focus")).toBeVisible();
  for (const id of ["rule-new", "rule-del", "clear-btn"]) {
    await expect(page.locator("#" + id)).toBeVisible();
  }
  for (const id of ["tier-checks", "mode-checks", "storm-checks", "mission-checks", "planet-checks", "faction-checks"]) {
    await expect(page.locator("#" + id)).toBeVisible();
  }
  // launcherは既存パレットをその軸に絞って開く
  await page.locator("#mission-checks").click();
  await expect(page.locator("#palette-overlay")).toBeVisible();
  await expect(page.locator("#palette-rule")).toContainText("MISSION");
  const facets = await page.locator("#palette-cands .cand .facet").allTextContents();
  expect(facets.length).toBeGreaterThan(0);
  expect(facets.every((facet) => facet === "MISSION")).toBe(true);
  await page.keyboard.press("Escape");
  // DELIVERYタブ: 配送先・TEST・時間設定・PAUSEへ到達できる
  await page.locator("#delivery-tab").click();
  for (const id of ["desktop-check", "webhook-input", "test-btn", "minremain-input", "poll-input", "pause-btn"]) {
    await expect(page.locator("#" + id)).toBeVisible();
  }
  expect(await railFits()).toBe(true);
  // 既定サイズでも縦スクロールを必要としない
  await page.setViewportSize({ width: 960, height: 620 });
  expect(await railFits()).toBe(true);
});

// RND-004: 最小720x480でも右サイドバーは縦スクロールなしでルール一覧・NEW/DEL/CLEAR・6軸launcher(レリック/モード/VOID嵐/ミッション/惑星/勢力)・配送設定・TEST/PAUSE・時間設定へ到達でき、ルール一覧はrail高さの固定比率領域に全ルール行を保持して内側だけ縦スクロールし、launcherはパレットをその軸に絞って開く(renderer統合) (ルール一覧の固定比率領域と内側縦スクロール)
test("RND-004 rules list scrolls inside fixed-ratio area", async ({ page }) => {
  await page.setViewportSize({ width: 720, height: 480 });
  await bootConsole(page);
  const listHeight = () => page.locator("#rules-list").evaluate((el) => el.clientHeight);
  const fewHeight = await listHeight();
  // ルールが増えても一覧領域の高さ(固定比率)は変わらず、railもスクロールしない
  for (let i = 0; i < 10; i++) {
    await page.locator("#rule-new").click();
  }
  await expect(page.locator("#rules-list .rule-row")).toHaveCount(12);
  expect(Math.abs((await listHeight()) - fewHeight)).toBeLessThanOrEqual(1);
  expect(await page.locator(".rail").evaluate((el) => el.scrollHeight <= el.clientHeight)).toBe(true);
  // 全ルール行を保持したまま一覧の内側だけ縦スクロールする
  expect(await page.locator("#rules-list").evaluate((el) => el.scrollHeight > el.clientHeight)).toBe(true);
  // focus行(最後に追加したR12)は可視領域へ追従する
  await expect(page.locator(".rule-focus .rno")).toHaveText("R12");
  await expect(page.locator(".rule-focus")).toBeInViewport();
});

// RND-006: FILTERSのNAME入力は編集中ルールの名前をdebounce保存し、ルール行は名前を要約より優先表示し、パレットは名前でRULE候補を検索でき、適用はenabledのトグルだけでedit focus表示を変えない。RENAME RULE候補の適用はパレット入力を改名モードへ切り替え、Enterで編集中ルールの名前を保存して通常モードへ戻り、Escは保存せず通常モードへ戻る(renderer統合)
test("RND-006 rule naming and palette toggle", async ({ page }) => {
  await bootConsole(page);
  // NAME入力は編集中ルール(R1)の名前をdebounce保存する
  await page.locator("#rulename-input").fill("MY FARM");
  await expect
    .poll(async () =>
      (await calls(page)).some(
        (entry) => entry.cmd === "set_config" && entry.args.config.rules[0].name === "MY FARM",
      ),
    )
    .toBe(true);
  // ルール行は名前を要約より優先表示する
  await expect(page.locator(".rule-focus .rule-summary")).toHaveText("MY FARM");
  const editingBefore = await page.locator("#editing-meta").textContent();
  // パレットは名前でRULE候補を検索できる(どこでも打鍵で開く)
  await page.locator("#rulename-input").blur();
  await page.keyboard.press("m");
  await expect(page.locator("#palette-overlay")).toBeVisible();
  await page.locator("#palette-input").fill("my farm");
  const cand = page.locator("#palette-cands .cand", { hasText: "MY FARM" });
  await expect(cand.locator(".facet")).toHaveText("RULE");
  await expect(cand.locator(".box")).toHaveText("[x]");
  // 適用は対象ルールのenabledトグルだけで、edit focus表示を変えない
  await page.keyboard.press("Enter");
  const applied = (await calls(page)).filter((entry) => entry.cmd === "apply_candidate");
  expect(applied[applied.length - 1].args.id).toBe("rule:0");
  await expect(page.locator(".rule-row").first()).toHaveClass(/disabled/);
  await expect(page.locator(".rule-row .rule-toggle").first()).toHaveText("[ ]");
  await expect(page.locator("#editing-meta")).toHaveText(editingBefore ?? "");
  // RENAME RULE候補の適用はパレット入力を改名モードへ切り替える(現在名をprefill)
  await page.locator("#palette-input").fill("rename");
  await page.keyboard.press("Enter");
  await expect(page.locator("#palette-input")).toHaveValue("MY FARM");
  // Escは保存せず通常モードへ戻る(パレットは開いたまま)
  await page.keyboard.press("Escape");
  await expect(page.locator("#palette-overlay")).toBeVisible();
  await expect(page.locator("#palette-input")).toHaveValue("");
  // 改名モードのEnterは編集中ルールの名前を保存して通常モードへ戻る
  await page.locator("#palette-input").fill("rename");
  await page.keyboard.press("Enter");
  await page.locator("#palette-input").fill("VOID RUSH");
  await page.keyboard.press("Enter");
  await expect
    .poll(async () =>
      (await calls(page)).some(
        (entry) => entry.cmd === "set_config" && entry.args.config.rules[0].name === "VOID RUSH",
      ),
    )
    .toBe(true);
  await expect(page.locator(".rule-focus .rule-summary")).toHaveText("VOID RUSH");
  await expect(page.locator("#palette-overlay")).toBeVisible();
  await expect(page.locator("#palette-input")).toHaveValue("");
});

// RND-005: 亀裂表はviewport 950pxで7列1段、949px以下で2段gridへ切り替わり、720/800/949pxで横スクロールを生まず、MODEとSTORMは独立セル、長い値はellipsisしてもDOM全文と行tooltipを保持する一方でFACTIONのTHE MURMURと既知の最長ミッション種別INFESTED SALVAGEは950pxでも省略せず全文表示し、empty rowは全幅、ヘッダはsticky、th[scope=col]は7個(renderer統合)
test("RND-005 compact table breakpoints", async ({ page }) => {
  await page.setViewportSize({ width: 950, height: 620 });
  await bootConsole(page);
  await expect(page.locator("th[scope=col]")).toHaveCount(7);
  const firstRow = page.locator("#fissure-rows tr").first();
  // 950px(表領域740px)では7列1段のtable表示を維持する
  expect(await firstRow.evaluate((el) => getComputedStyle(el).display)).toBe("table-row");
  for (const width of [949, 800, 720]) {
    await page.setViewportSize({ width, height: 620 });
    // 2段gridへ切り替わる
    expect(await firstRow.evaluate((el) => getComputedStyle(el).display)).toBe("grid");
    // 横スクロールを必要としない
    expect(await page.locator(".tablewrap").evaluate((el) => el.scrollWidth <= el.clientWidth)).toBe(true);
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    // ヘッダはsticky
    expect(await page.locator("thead").evaluate((el) => getComputedStyle(el).position)).toBe("sticky");
  }
  // MODEとSTORMは別セル・別ラベルのまま
  const stormRow = page.locator("#fissure-rows tr", { hasText: "Nsu Grid" });
  await expect(stormRow.locator(".col-mode .flag")).toHaveText(/HARD/);
  await expect(stormRow.locator(".col-storm .flag")).toHaveText(/STORM/);
  // 長い値はellipsisしてもDOM上の全文と行tooltipを保持する
  const longRow = page.locator("#fissure-rows tr", { hasText: "Taveuni" });
  await expect(longRow.locator(".col-node .t-node")).toHaveText(
    "Taveuni (Kuva Fortress)",
  );
  expect(await longRow.getAttribute("title")).toContain("Taveuni (Kuva Fortress)");
  // 実APIのFACTION名THE MURMURは標準幅でも省略しない
  const murmur = longRow.locator(".col-faction .icon-label > span:last-child");
  await expect(murmur).toHaveText("THE MURMUR");
  expect(await murmur.evaluate((el) => el.scrollWidth <= el.clientWidth)).toBe(true);
  // 既知の最長ミッション種別INFESTED SALVAGEは950pxの7列1段でも省略しない
  await page.setViewportSize({ width: 950, height: 620 });
  const longestMission = longRow.locator(".col-mission .icon-label > span:last-child");
  await expect(longestMission).toHaveText("INFESTED SALVAGE");
  expect(await longestMission.evaluate((el) => el.scrollWidth <= el.clientWidth)).toBe(true);
});

// RND-005: 亀裂表はviewport 950pxで7列1段、949px以下で2段gridへ切り替わり、720/800/949pxで横スクロールを生まず、MODEとSTORMは独立セル、長い値はellipsisしてもDOM全文と行tooltipを保持する一方でFACTIONのTHE MURMURと既知の最長ミッション種別INFESTED SALVAGEは950pxでも省略せず全文表示し、empty rowは全幅、ヘッダはsticky、th[scope=col]は7個(renderer統合) (empty rowの全幅表示)
test("RND-005 empty row spans full width", async ({ page }) => {
  await page.setViewportSize({ width: 720, height: 480 });
  await bootConsole(page, { noFissures: true });
  const spansFullWidth = await page.locator("#fissure-rows td.empty").evaluate((el) => {
    const row = el.closest("tr");
    if (!row) return false;
    return Math.abs(el.getBoundingClientRect().width - row.getBoundingClientRect().width) <= 1;
  });
  expect(spansFullWidth).toBe(true);
});

// RND-008: 一覧表示中の亀裂は次回pollを待たずexpiry到達後1秒以内にDOMとfrontend snapshotから除去され、他の生存中亀裂・設定・通知状態を変えない(renderer統合)
test("RND-008 expiry cleanup", async ({ page }) => {
  await bootConsole(page, { firstExpirySecs: 1 });
  const expiring = page.locator("#fissure-rows tr", { hasText: "Taveuni" });
  await expect(expiring).toHaveCount(1);
  await expect(expiring).toHaveCount(0, { timeout: 3500 });
  await expect(page.locator("#fissure-rows tr", { hasText: "Nsu Grid" })).toHaveCount(1);
  const statusIds = await page.evaluate(() => {
    const state = (window as unknown as { __MOCK_STATE__: { status: { fissures: Array<{ id: string }> } } }).__MOCK_STATE__;
    return state.status.fissures.map((fissure) => fissure.id);
  });
  expect(statusIds).not.toContain("fx-requiem");
  expect(
    (await calls(page)).filter((entry) =>
      ["set_config", "set_rule_enabled", "set_rule_notify", "apply_candidate"].includes(entry.cmd),
    ).length,
  ).toBe(0);
});

// RND-007: 亀裂表のヘッダクリックで項目別ソートでき、同じ列の再クリックで昇順/降順をトグルし、ソート中の列にaria-sortが付く。既定はT-REMAIN昇順で、パレットのSORT BY {列}候補もヘッダクリックと同じソートを適用し、同じ列への再適用は降順へトグルし、適用後もパレットは開いたまま連続入力できる。ヘッダ・パレットのどちらのソートも表示のみ(設定・通知の変更を呼ばない)(renderer統合)
test("RND-007 table sort by column", async ({ page }) => {
  await bootConsole(page);
  const firstRow = () => page.locator("#fissure-rows tr").first();
  // 既定はT-REMAIN昇順(消滅が近い順)
  await expect(page.locator("th.col-timer")).toHaveAttribute("aria-sort", "ascending");
  await expect(firstRow().locator(".col-tier")).toContainText("REQUIEM");
  // ヘッダクリックでその列の昇順ソート
  await page.locator("th.col-tier").click();
  await expect(page.locator("th.col-tier")).toHaveAttribute("aria-sort", "ascending");
  await expect(page.locator("th.col-timer")).not.toHaveAttribute("aria-sort");
  await expect(firstRow().locator(".col-tier")).toContainText("LITH");
  // 同じ列の再クリックで降順へトグル
  await page.locator("th.col-tier").click();
  await expect(page.locator("th.col-tier")).toHaveAttribute("aria-sort", "descending");
  await expect(firstRow().locator(".col-tier")).toContainText("REQUIEM");
  // 別の列をクリックするとその列の昇順から始まる
  await page.locator("th.col-mission").click();
  await expect(page.locator("th.col-mission")).toHaveAttribute("aria-sort", "ascending");
  await expect(firstRow().locator(".col-mission")).toContainText("CAPTURE");
  // パレットのSORT BY {列}候補はヘッダクリックと同じソートを適用する
  await page.keyboard.press("s");
  await expect(page.locator("#palette-overlay")).toBeVisible();
  await page.locator("#palette-input").fill("sort by node");
  await expect(page.locator("#palette-cands .cand", { hasText: "SORT BY NODE" })).toHaveCount(1);
  await page.keyboard.press("Enter");
  await expect(page.locator("th.col-node")).toHaveAttribute("aria-sort", "ascending");
  await expect(page.locator("th.col-mission")).not.toHaveAttribute("aria-sort");
  await expect(firstRow().locator(".col-node")).toContainText("Hepit");
  // 同じ列への再適用は降順へトグルし、パレットは開いたまま連続入力できる
  await expect(page.locator("#palette-overlay")).toBeVisible();
  await expect(page.locator("#palette-input")).toHaveValue("");
  await page.locator("#palette-input").fill("sort by node");
  await page.keyboard.press("Enter");
  await expect(page.locator("th.col-node")).toHaveAttribute("aria-sort", "descending");
  await expect(firstRow().locator(".col-node")).toContainText("Taveuni");
  await page.keyboard.press("Escape");
  // ヘッダ・パレットのどちらのソートも表示のみ: 設定・通知の変更を呼ばない
  expect(
    (await calls(page)).filter((entry) =>
      ["set_config", "set_rule_enabled", "set_rule_notify", "apply_candidate"].includes(entry.cmd),
    ).length,
  ).toBe(0);
});

// RND-009: VIEW選択0本からピッカーでfilter候補を適用すると既存ルールを変更せずVIEW ON・NOTIFY OFFの新ルールを作り、edit focusを新ルールへ移す。NEW RULE適用中に別のfilter候補を素早く確定しても操作を直列化し、旧edit対象を変更せず同じ新ルールへ適用する(renderer統合)
test("RND-009 unselected picker creates a view rule", async ({ page }) => {
  await bootConsole(page, { allRulesDisabled: true });
  // 全VIEW解除後も残っているR2のedit focusを、暗黙作成時に誤編集しない
  await page.locator(".rule-row .rule-edit").nth(1).click();
  await expect(page.locator("#editing-meta")).toHaveText("R2/2");
  const before = await page.evaluate(() =>
    structuredClone(
      (window as unknown as { __MOCK_STATE__: { config: { rules: unknown[] } } })
        .__MOCK_STATE__.config.rules,
    ),
  );

  await page.locator("#tier-checks").click();
  await page.locator("#palette-cands .cand", { hasText: "Requiem" }).click();

  await expect(page.locator("#rules-list .rule-row")).toHaveCount(3);
  await expect(page.locator("#rules-meta")).toHaveText("1/3 VIEW");
  await expect(page.locator("#editing-meta")).toHaveText("R3/3");
  const after = await page.evaluate(() =>
    structuredClone(
      (window as unknown as {
        __MOCK_STATE__: {
          config: {
            rules: Array<{
              enabled: boolean;
              notify: boolean;
              tiers: string[];
            }>;
          };
        };
      }).__MOCK_STATE__.config.rules,
    ),
  );
  expect(after.slice(0, 2)).toEqual(before);
  expect(after[2]).toMatchObject({ enabled: true, notify: false, tiers: ["Requiem"] });
  const applied = (await calls(page)).filter((entry) => entry.cmd === "apply_candidate");
  expect(applied[applied.length - 1].args).toEqual({ id: "tier:Requiem", active: 1, tab: "fissures" });
});

// RND-009: VIEW選択0本からピッカーでfilter候補を適用すると既存ルールを変更せずVIEW ON・NOTIFY OFFの新ルールを作り、edit focusを新ルールへ移す。NEW RULE適用中に別のfilter候補を素早く確定しても操作を直列化し、旧edit対象を変更せず同じ新ルールへ適用する(renderer統合) (NEW RULE応答中の後続候補を旧ルールへ適用しない)
test("RND-009 serializes rapid new rule and filter apply", async ({ page }) => {
  await bootConsole(page, { allRulesDisabled: true, applyCandidateDelayMs: 80 });
  const before = await page.evaluate(() =>
    structuredClone(
      (window as unknown as { __MOCK_STATE__: { config: { rules: unknown[] } } })
        .__MOCK_STATE__.config.rules,
    ),
  );

  await page.keyboard.press("n");
  await page.locator("#palette-input").fill("new rule");
  await page.keyboard.press("Enter");
  // 最初のIPC応答を待たず、異なるfilter候補を確定する
  await page.locator("#palette-input").fill("axi");
  await expect(page.locator("#palette-cands .cand", { hasText: "Axi" })).toHaveCount(1);
  await page.keyboard.press("Enter");

  await expect(page.locator("#rules-list .rule-row")).toHaveCount(3);
  await expect(page.locator("#rules-meta")).toHaveText("1/3 VIEW");
  await expect(page.locator("#editing-meta")).toHaveText("R3/3");
  await expect
    .poll(async () =>
      page.evaluate(() =>
        (window as unknown as {
          __MOCK_STATE__: { config: { rules: Array<{ tiers: string[] }> } };
        }).__MOCK_STATE__.config.rules[2]?.tiers,
      ),
    )
    .toEqual(["Axi"]);
  const after = await page.evaluate(() =>
    structuredClone(
      (window as unknown as {
        __MOCK_STATE__: {
          config: { rules: Array<{ enabled: boolean; notify: boolean; tiers: string[] }> };
        };
      }).__MOCK_STATE__.config.rules,
    ),
  );
  expect(after.slice(0, 2)).toEqual(before);
  expect(after[2]).toMatchObject({ enabled: true, notify: false, tiers: ["Axi"] });
});

// RND-010: コンテンツ領域はfissures/arbitration/sortie/archon/syndicates/area-missions/circuit/archimedea/descendiaの9タブをこの順で持ち、英語表示はFissures/Arbitration/Sortie/Archon Hunt/Syndicates/Area Missions/Circuit/Archimedea/Descendiaとなる。ネットセルのtabとtabpanelは持たない。時限cardは亀裂表と同じ時間文法に従い、仲裁cardはcommunity schedule・browse.wf出典で絶対日時のStarts表記ではなくdata-expiry駆動の残り時間カウントダウンを表示し、将来Descendiaはupcomingとしてdata-activation駆動の開始までカウントダウンを表示する。DescendiaのSpecs/Aurasは生のLotus pathを本文へ表示せず、path leafを人間可読ラベル(CoH接頭辞とSpec/Aura接尾辞を除去しcamelCaseを分かち書き)へ整形して表示し、整形前のraw識別子はtooltipへ保持する。Descendiaのactive cardはupcoming行と同じくpanel全幅の単一列で表示し、multi-card gridの分割幅で細長く積まない。Circuitタブは現在のデュヴィリのスパイラル(WFCD由来の環境サイクルcard。状態ラベルと残り時間カウントダウン付き)をCircuit cardの前へ併記し、WFCD sourceの障害はこのタブでも表示できる。スパイラルcardはArea環境サイクルの表示からも取り除かない。個人進捗の非公開を説明するprogress noteはどのタブにも表示しない。Areaは環境・通常依頼・objective rotation・追加依頼・eventの5 groupをこの順で分離し、WFCD・Oracle Bounty・Oracle location-bountiesのsource別errorを表示できる。active tabと可視tabpanelは常に各1つで、Cmd+1..9は対応タブへ切替、Ctrl+Tab/Ctrl+Shift+Tabは前後へ循環し、Ctrl+1..9は従来どおりrule edit focusだけを変更する。パレットのGO TO {タブ}候補は対応タブへ切り替えてパレットを閉じ、ルール・設定を変更しない。タブ列が横幅からあふれるときは、あふれている側だけにedge fadeヒント(scrolled-start/scrolled-end)を付けてスクロール可能性を示し、native scrollbarより控えめな細いテーマ色バーを使う。tablist/tab/tabpanelのARIA対応、aria-controls/labelledby、aria-selectedとtabindex=0の一意性、矢印/Home/Endによるroving focusを保持し、poll更新で仲裁card全体をlive regionとして再告知しない(renderer統合)
test("RND-010 content tabs and browser shortcuts", async ({ page }) => {
  await page.setViewportSize({ width: 960, height: 620 });
  await bootConsole(page, { locale: "en" });
  const tabs = [
    ["fissures", "Fissures"],
    ["arbitration", "Arbitration"],
    ["sortie", "Sortie"],
    ["archon", "Archon Hunt"],
    ["syndicates", "Syndicates"],
    ["area-missions", "Area Missions"],
    ["circuit", "Circuit"],
    ["archimedea", "Archimedea"],
    ["descendia", "Descendia"],
  ] as const;
  await expect(page.locator("#content-tabs")).toHaveAttribute("role", "tablist");
  await expect(page.locator("#content-tabs [role=tab]")).toHaveCount(tabs.length);
  await expect(page.locator('[role="tabpanel"]')).toHaveCount(tabs.length);
  expect(
    await page.locator("#content-tabs [role=tab]").evaluateAll((elements) =>
      elements.map((element) => element.getAttribute("data-tab-id")),
    ),
  ).toEqual(tabs.map(([id]) => id));
  await expect(
    page.locator("#tab-netracells, #panel-netracells"),
  ).toHaveCount(0);

  for (const [id, label] of tabs) {
    const tab = page.locator("#tab-" + id);
    const panel = page.locator("#panel-" + id);
    await expect(tab).toHaveAttribute("role", "tab");
    await expect(tab).toHaveAttribute("data-tab-id", id);
    await expect(tab).toHaveAttribute("aria-controls", "panel-" + id);
    await expect(tab).toHaveText(label);
    await expect(panel).toHaveAttribute("role", "tabpanel");
    await expect(panel).toHaveAttribute("aria-labelledby", "tab-" + id);
  }

  const assertActive = async (id: string) => {
    await expect(page.locator('#content-tabs [role="tab"][aria-selected="true"]')).toHaveCount(1);
    await expect(page.locator('#content-tabs [role="tab"][tabindex="0"]')).toHaveCount(1);
    await expect(page.locator('#content-tabs [role="tab"][aria-selected="true"]')).toHaveAttribute(
      "data-tab-id",
      id,
    );
    await expect(page.locator('[role="tabpanel"]:not([hidden])')).toHaveCount(1);
    await expect(page.locator("#panel-" + id)).toBeVisible();
    await expect(page.locator('#content-tabs [role="tab"][aria-selected="false"]')).toHaveCount(
      tabs.length - 1,
    );
    await expect(page.locator('#content-tabs [role="tab"][tabindex="-1"]')).toHaveCount(
      tabs.length - 1,
    );
  };

  await assertActive("fissures");
  for (let i = 0; i < tabs.length; i++) {
    await page.keyboard.press("Meta+" + (i + 1));
    await assertActive(tabs[i][0]);
  }
  // 最終タブから次へ、先頭タブから前へ循環する。
  await page.keyboard.press("Control+Tab");
  await assertActive("fissures");
  await page.keyboard.press("Control+Shift+Tab");
  await assertActive("descendia");

  // Ctrl+数字はタブではなく従来のrule edit focusだけを変更する。
  await page.keyboard.press("Control+2");
  await expect(page.locator("#editing-meta")).toHaveText("R2/2");
  await assertActive("descendia");

  // パレットのGO TO {タブ}候補は対応タブへ切り替えてパレットを閉じ、ルール・設定を変更しない。
  await page.keyboard.press("g");
  await expect(page.locator("#palette-overlay")).toBeVisible();
  await page.locator("#palette-input").fill("go to syndicates");
  await expect(page.locator("#palette-cands .cand", { hasText: "GO TO SYNDICATES" })).toHaveCount(1);
  await page.keyboard.press("Enter");
  await assertActive("syndicates");
  await expect(page.locator("#palette-overlay")).toBeHidden();
  expect(
    (await calls(page)).filter((entry) =>
      ["set_config", "set_rule_enabled", "set_rule_notify", "apply_candidate"].includes(entry.cmd),
    ).length,
  ).toBe(0);

  // タブ列があふれるときは、あふれている側だけedge fadeヒントを付ける。
  await page.locator("#content-tabs").evaluate((el) => {
    el.scrollLeft = 0;
  });
  await page.setViewportSize({ width: 720, height: 620 });
  await expect(page.locator("#content-tabs")).toHaveClass(/scrolled-end/);
  await expect(page.locator("#content-tabs")).not.toHaveClass(/scrolled-start/);
  await page.locator("#content-tabs").evaluate((el) => {
    el.scrollLeft = el.scrollWidth;
  });
  await expect(page.locator("#content-tabs")).toHaveClass(/scrolled-start/);
  await expect(page.locator("#content-tabs")).not.toHaveClass(/scrolled-end/);
  // 収まる幅ではどちらのヒントも付けない。
  await page.setViewportSize({ width: 1100, height: 620 });
  await expect(page.locator("#content-tabs")).not.toHaveClass(/scrolled-start|scrolled-end/);
  await page.setViewportSize({ width: 960, height: 620 });

  // ARIA roving focusは矢印/Home/Endでactive tabと共に移動する。
  await page.locator("#tab-fissures").focus();
  await page.keyboard.press("ArrowRight");
  await expect(page.locator("#tab-arbitration")).toBeFocused();
  await assertActive("arbitration");
  await page.keyboard.press("Home");
  await expect(page.locator("#tab-fissures")).toBeFocused();
  await assertActive("fissures");
  await page.keyboard.press("End");
  await expect(page.locator("#tab-descendia")).toBeFocused();
  await assertActive("descendia");

  // source・時間状態・Area内のsource分離をDOM属性で保持する。
  await page.keyboard.press("Meta+2");
  const arbitration = page.locator(
    '#panel-arbitration .timed-card[data-card-id="arbitration-current"]',
  );
  await expect(arbitration).toHaveAttribute("data-temporal-status", "active");
  await expect(arbitration).toHaveAttribute("data-provenance", "community-schedule");
  expect(await page.locator("#timed-arbitration").getAttribute("aria-live")).toBeNull();
  // 亀裂表と同じ時間文法: 絶対日時のStarts表記ではなくdata-expiry駆動のカウントダウン。
  const arbitrationTimer = arbitration.locator(".t-timer[data-expiry]");
  await expect(arbitrationTimer).toHaveCount(1);
  await expect(arbitrationTimer).toHaveText(/^\d+:\d{2}(:\d{2})?$/);
  expect(await arbitration.textContent()).not.toContain("Starts ");
  await expect(arbitration.locator(".timed-source-link")).toHaveAttribute(
    "href",
    /browse\.wf/,
  );
  await expect(
    page.locator(
      '#panel-arbitration .timed-source-validity[data-source="browseWfArbitration"]',
    ),
  ).toBeVisible();

  await page.keyboard.press("Meta+6");
  const areaGroups = page.locator("#panel-area-missions .timed-card-group");
  await expect(areaGroups).toHaveCount(5);
  expect(
    await areaGroups.evaluateAll((groups) => groups.map((group) => group.getAttribute("data-group"))),
  ).toEqual(["environments", "worldstate", "location-objectives", "bounties", "events"]);
  await expect(page.locator('#panel-area-missions .timed-card-group[data-group="environments"] .timed-card')).toHaveCount(5);
  await expect(page.locator('#panel-area-missions .timed-card-group[data-group="location-objectives"] .timed-card')).toHaveCount(3);
  await expect(page.locator('#panel-area-missions .timed-card-group[data-group="events"] .timed-card')).toHaveCount(1);
  const areaFactionVariants = await page
    .locator('#panel-area-missions .timed-card-group[data-group="worldstate"] .timed-card, #panel-area-missions .timed-card-group[data-group="bounties"] .timed-card')
    .evaluateAll((cards) => cards.map((card) => card.getAttribute("data-variant")));
  for (const variant of ["ostrons", "solaris-united", "entrati", "holdfasts", "cavia", "hex"]) {
    expect(areaFactionVariants).toContain(variant);
  }
  await expect(
    page.locator(
      '#panel-area-missions .timed-source-error[data-source="wfcd"][data-freshness="stale"]',
    ),
  ).toContainText("wfcd down");
  await expect(
    page.locator(
      '#panel-area-missions .timed-source-error[data-source="browseWfBounties"][data-freshness="unavailable"]',
    ),
  ).toContainText("oracle down");
  await expect(
    page.locator(
      '#panel-area-missions .timed-source-error[data-source="browseWfLocationBounties"][data-freshness="unavailable"]',
    ),
  ).toContainText("location oracle down");

  await page.keyboard.press("Meta+7");
  const circuit = page.locator('#panel-circuit .timed-card[data-provenance="official-live"]');
  await expect(circuit).toHaveCount(1);
  await expect(circuit.locator(".timed-stage")).toHaveCount(2);
  await expect(circuit.locator(".timed-stage").nth(0)).toContainText(/Excalibur.*Mag.*Volt/s);
  await expect(circuit.locator(".timed-stage").nth(1)).toContainText(/Braton.*Lato.*Skana.*Paris.*Kunai/s);
  // デュヴィリのスパイラル(環境サイクル)をCircuit cardの前へ併記し、状態とカウントダウンを表示する
  const spiral = page.locator('#panel-circuit .timed-card[data-variant="duviri"]');
  await expect(spiral).toHaveCount(1);
  await expect(spiral).toContainText("Duviri");
  await expect(spiral.locator(".timed-meta")).toContainText("Joy");
  await expect(spiral.locator(".t-timer[data-expiry]")).toHaveCount(1);
  expect(
    await page
      .locator("#panel-circuit .timed-card")
      .evaluateAll((cards) => cards.map((card) => card.getAttribute("data-variant"))),
  ).toEqual(["duviri", null]);
  // WFCD sourceの障害はCircuitタブでも表示できる
  await expect(
    page.locator('#panel-circuit .timed-source-error[data-source="wfcd"]'),
  ).toContainText("wfcd down");
  // Area環境サイクルからは取り除かない(5 groupの検査は上のMeta+6節)

  await page.keyboard.press("Meta+9");
  await expect(page.locator('#panel-descendia .timed-card[data-temporal-status="active"]')).toBeVisible();
  // Specs/Aurasは生のLotus pathを本文表示せず、人間可読ラベル+raw tooltipで表示する
  expect(await page.locator("#panel-descendia").textContent()).not.toContain("/Lotus/");
  const activeDescendia = page.locator('#panel-descendia .timed-card[data-temporal-status="active"]');
  // active cardはupcoming行と同じくpanel全幅の単一列(multi-card gridの分割幅にしない)
  expect(
    await activeDescendia.evaluate((card) => {
      const panel = card.closest(".timed-cards");
      if (!panel) return 0;
      return card.getBoundingClientRect().width / panel.getBoundingClientRect().width;
    }),
  ).toBeGreaterThan(0.9);
  const descendiaSpec = activeDescendia.locator(".timed-value-group li", { hasText: "Roller" }).first();
  await expect(descendiaSpec).toHaveText("Roller");
  await expect(descendiaSpec).toHaveAttribute(
    "title",
    "/Lotus/Types/Game/EnemySpecs/Tau/CoHRollerSpec",
  );
  const descendiaAura = activeDescendia.locator(".timed-value-group li", { hasText: "Rocket Spawn" }).first();
  await expect(descendiaAura).toHaveText("Rocket Spawn");
  await expect(descendiaAura).toHaveAttribute(
    "title",
    "/Lotus/Types/Scripts/Tau/CoH/Complications/RocketSpawnAura",
  );
  await expect(
    page.locator('#panel-descendia details.timed-upcoming[data-card-id="descendia-next"]'),
  ).toBeVisible();
  // upcomingは開始までのカウントダウン(data-activation駆動)を表示する。
  await expect(
    page.locator(
      '#panel-descendia details.timed-upcoming[data-card-id="descendia-next"] .t-timer[data-activation]',
    ),
  ).toHaveCount(1);
  // 個人進捗の非公開を説明するprogress noteはどのタブにも表示しない。
  await expect(page.locator(".timed-progress-note")).toHaveCount(0);
});

// RND-015: 亀裂の検索条件を変更する操作が成功したとき、コンテンツタブが亀裂以外なら亀裂タブへ自動で切り替える。対象はfilter候補(tier/mission/planet/faction/mode/storm)の適用(亀裂以外のタブではfacet launcherが開く亀裂ピッカー経由)、RULE候補とルール行・SpaceによるVIEW選択トグル、DESELECT ALL RULES、DELETE RULE、CLEAR。パレット経由の適用では自動切替してもパレットを閉じず連続入力を妨げない。通知トグル・改名・NEW RULEの空draft追加・SORT/GO TOコマンド・contentRules編集(タブ別ピッカーのコンテンツ候補適用を含む)・配送設定では切り替えない(renderer統合)
test("RND-015 filter change reveals fissures tab", async ({ page }) => {
  await bootConsole(page);
  const activeTab = () => page.locator('#content-tabs [role="tab"][aria-selected="true"]');
  // 亀裂以外のタブではfacet launcherが亀裂ピッカーを開き、filter候補の適用で亀裂タブへ
  // 自動で切り替わる。パレットは開いたまま
  await page.keyboard.press("Meta+2");
  await expect(activeTab()).toHaveAttribute("data-tab-id", "arbitration");
  await page.locator("#tier-checks").click();
  await page.locator("#palette-input").fill("axi");
  await page.keyboard.press("Enter");
  await expect(activeTab()).toHaveAttribute("data-tab-id", "fissures");
  await expect(page.locator("#palette-overlay")).toBeVisible();
  await page.keyboard.press("Escape");
  // タブ別ピッカーのコンテンツ候補適用(contentRules編集)は切り替えない
  await page.keyboard.press("Meta+2");
  await page.keyboard.press("s");
  await page.locator("#palette-input").fill("survival");
  await page.keyboard.press("Enter");
  await expect
    .poll(async () =>
      (await calls(page)).some(
        (entry) => entry.cmd === "apply_candidate" && entry.args.id === "ckeyword:Survival",
      ),
    )
    .toBe(true);
  await expect(activeTab()).toHaveAttribute("data-tab-id", "arbitration");
  // コンテンツルールのnotifyトグル(crule候補)も検索条件ではないので切り替えない
  await page.locator("#palette-input").fill("a1");
  await page.keyboard.press("Enter");
  await expect
    .poll(async () =>
      (await calls(page)).some(
        (entry) => entry.cmd === "apply_candidate" && entry.args.id === "crule:0",
      ),
    )
    .toBe(true);
  await expect(activeTab()).toHaveAttribute("data-tab-id", "arbitration");
  await page.keyboard.press("Escape");
  // Space(編集中ルールのVIEW選択トグル)は切り替える
  await page.keyboard.press(" ");
  await expect(activeTab()).toHaveAttribute("data-tab-id", "fissures");
});

// RND-016: 亀裂以外のコンテンツタブで打鍵起動したパレットはそのタブのコンテンツ候補を出し、query_candidates/apply_candidateへtabを渡す。キーワード・レベル候補の適用はタブを切り替えずパレットを開いたまま連続入力でき、rail上部のタブ通知ルール行が適用結果へ追従する。クエリの数字はレベル下限候補として適用できる。コンテンツ候補の適用は亀裂WatchRule・VIEW/NOTIFY・edit focusを変更しない。facet launcherは亀裂以外のタブでも亀裂ピッカー(tab=fissures)を開き、その適用は従来どおり亀裂タブへ自動切替する(renderer統合)
test("RND-016 content tab picker", async ({ page }) => {
  await bootConsole(page, { locale: "en" });
  const activeTab = () => page.locator('#content-tabs [role="tab"][aria-selected="true"]');
  const contentRules = async () =>
    page.evaluate(
      () =>
        (window as unknown as { __MOCK_STATE__: { config: { contentRules: unknown } } })
          .__MOCK_STATE__.config.contentRules,
    );
  const fissureRulesJson = async () =>
    page.evaluate(() =>
      JSON.stringify(
        (window as unknown as { __MOCK_STATE__: { config: { rules: unknown } } }).__MOCK_STATE__
          .config.rules,
      ),
    );
  const rulesBefore = await fissureRulesJson();

  // 仲裁タブの打鍵パレットはそのタブのコンテンツ候補を出し、queryへtabを渡す
  await page.keyboard.press("Meta+2");
  await page.keyboard.press("s");
  await expect(page.locator("#palette-overlay")).toBeVisible();
  await page.locator("#palette-input").fill("survival");
  await expect(page.locator("#palette-cands .cand", { hasText: "Survival" })).toHaveCount(1);
  await expect
    .poll(async () =>
      (await calls(page)).some(
        (entry) => entry.cmd === "query_candidates" && entry.args.tab === "arbitration",
      ),
    )
    .toBe(true);
  await page.keyboard.press("Enter");
  // 適用はタブを切り替えず、パレットは開いたまま連続入力できる
  await expect(activeTab()).toHaveAttribute("data-tab-id", "arbitration");
  await expect(page.locator("#palette-overlay")).toBeVisible();
  await expect(page.locator("#palette-input")).toHaveValue("");
  await expect
    .poll(contentRules)
    .toEqual([
      { notify: true, name: null, kinds: ["arbitration"], missionTypes: ["Survival"], minEnemyLevel: null },
    ]);
  expect(
    (await calls(page)).some(
      (entry) =>
        entry.cmd === "apply_candidate" &&
        entry.args.id === "ckeyword:Survival" &&
        entry.args.tab === "arbitration",
    ),
  ).toBe(true);
  // rail上部のタブ通知ルール行が適用結果へ追従する
  await expect(page.locator("#content-alert-rows .content-alert-row")).toHaveCount(1);

  // クエリの数字はレベル下限候補になり、同じルールへ適用される
  await page.locator("#palette-input").fill("120");
  await expect(page.locator("#palette-cands .cand", { hasText: "MIN LV 120+" })).toHaveCount(1);
  await page.keyboard.press("Enter");
  await expect
    .poll(async () =>
      ((await contentRules()) as Array<{ minEnemyLevel: number | null }>).map(
        (rule) => rule.minEnemyLevel,
      ),
    )
    .toEqual([120]);

  // コンテンツ候補の適用は亀裂WatchRule・edit focusを変更しない
  expect(await fissureRulesJson()).toBe(rulesBefore);
  await expect(page.locator("#editing-meta")).toHaveText("R1/2");

  // facet launcherは亀裂以外のタブでも亀裂ピッカー(tab=fissures)を開き、
  // filter候補の適用は従来どおり亀裂タブへ自動切替する
  await page.keyboard.press("Escape");
  await page.locator("#tier-checks").click();
  await expect(page.locator("#palette-overlay")).toBeVisible();
  await expect
    .poll(async () =>
      (await calls(page)).some(
        (entry) => entry.cmd === "query_candidates" && entry.args.tab === "fissures",
      ),
    )
    .toBe(true);
  await page.locator("#palette-input").fill("axi");
  await page.keyboard.press("Enter");
  await expect(activeTab()).toHaveAttribute("data-tab-id", "fissures");
  await expect(page.locator("#palette-overlay")).toBeVisible();
});

// RND-014: ルール管理はコンテンツタブごとに分かれる: 亀裂タブではrail上部のルール一覧が亀裂WatchRuleを表示し、それ以外のタブでは同じ位置がそのタブ対象のコンテンツ通知ルール管理UI(タブ名入りheading・行リスト・キーワード+LV下限の追加フォーム)へ切り替わる。行はkindsがタブのkind群(エリアはarea-mission/area-objective/bounty、シンジケートはsyndicate)と交差するルールに加えkinds未指定(すべて)のルールも含み、追加はそのタブのkind群へ展開して保存される。行の通知トグルは元のcontentRulesの該当ルールのnotifyだけを、削除ボタンは該当ルールの除去だけをset_config(contentRules)へ保存する。これらの操作は亀裂のWatchRule・VIEW/NOTIFY・edit focus・通知ミュート設定を変更しない(renderer統合)
test("RND-014 per-tab rule management", async ({ page }) => {
  await bootConsole(page, { locale: "en" });
  // 亀裂タブでは亀裂WatchRuleの一覧が見え、タブ通知UIは非表示
  await expect(page.locator("#fissure-rules")).toBeVisible();
  await expect(page.locator("#tab-alerts")).toBeHidden();
  const rulesBefore = await page.locator("#rules-list .rule-row").count();
  const editingBefore = await page.locator("#editing-meta").textContent();
  const contentRules = async () =>
    page.evaluate(
      () =>
        (window as unknown as { __MOCK_STATE__: { config: { contentRules?: unknown } } })
          .__MOCK_STATE__.config.contentRules,
    );

  // 仲裁タブでは同じ位置がそのタブの通知ルール管理へ切り替わる
  await page.keyboard.press("Meta+2");
  await expect(page.locator("#fissure-rules")).toBeHidden();
  await expect(page.locator("#tab-alerts")).toBeVisible();
  await expect(page.locator("#tab-alerts-heading")).toContainText("Arbitration");
  await expect(page.locator("#content-alert-rows .content-alert-empty")).toHaveCount(1);
  await page.locator("#content-keyword-input").fill("防衛");
  await page.locator("#content-level-input").fill("60");
  await page.locator("#content-add-btn").click();
  await expect(page.locator("#content-alert-rows .content-alert-row")).toHaveCount(1);
  await expect
    .poll(contentRules)
    .toEqual([
      { notify: true, name: null, kinds: ["arbitration"], missionTypes: ["防衛"], minEnemyLevel: 60 },
    ]);

  // エリアタブでは仲裁のルールは見えず、追加はarea 3 kindへ展開される
  await page.keyboard.press("Meta+6");
  await expect(page.locator("#tab-alerts-heading")).toContainText("Area Missions");
  await expect(page.locator("#content-alert-rows .content-alert-row")).toHaveCount(0);
  await page.locator("#content-keyword-input").fill("Capture");
  await page.locator("#content-add-btn").click();
  await expect(page.locator("#content-alert-rows .content-alert-row")).toHaveCount(1);
  await expect
    .poll(async () => ((await contentRules()) as Array<{ kinds: string[] }>)[1])
    .toEqual({
      notify: true,
      name: null,
      kinds: ["area-mission", "area-objective", "bounty"],
      missionTypes: ["Capture"],
      minEnemyLevel: null,
    });

  // 仲裁タブへ戻ると仲裁のルールだけが見え、トグルは元のcontentRulesの該当ルールだけを反転する
  await page.keyboard.press("Meta+2");
  await expect(page.locator("#content-alert-rows .content-alert-row")).toHaveCount(1);
  await page.locator("#content-alert-rows .content-alert-toggle").first().click();
  await expect
    .poll(async () =>
      ((await contentRules()) as Array<{ notify: boolean }>).map((rule) => rule.notify),
    )
    .toEqual([false, true]);

  // 削除も該当ルールだけを除去する(エリアのルールは残る)
  await page.locator("#content-alert-rows .content-alert-del").first().click();
  await expect(page.locator("#content-alert-rows .content-alert-empty")).toHaveCount(1);
  await expect
    .poll(async () =>
      ((await contentRules()) as Array<{ missionTypes: string[] }>).map((rule) => rule.missionTypes),
    )
    .toEqual([["Capture"]]);

  // 亀裂タブへ戻すと亀裂ルールUIへ戻り、亀裂側・ミュートへ波及しない
  await page.keyboard.press("Meta+1");
  await expect(page.locator("#fissure-rules")).toBeVisible();
  await expect(page.locator("#tab-alerts")).toBeHidden();
  await expect(page.locator("#rules-list .rule-row")).toHaveCount(rulesBefore);
  await expect(page.locator("#editing-meta")).toHaveText(editingBefore ?? "");
  expect(
    (await calls(page)).filter((entry) =>
      ["set_rule_enabled", "set_rule_notify", "apply_candidate", "clear_filter"].includes(entry.cmd),
    ),
  ).toHaveLength(0);
  await page.locator("#delivery-tab").click();
  await expect(page.locator("#mute-check")).toHaveAttribute("aria-pressed", "false");
});

// RND-013: 亀裂表のNODE列はbackend snapshotのnodeLevels(ExportRegions由来)に表示名が一致するnodeへLV {min}-{max}を併記し、鋼(isHard)の亀裂は基底levelへ+100した範囲を表示する。行tooltipにも同じ値を含める。lookupにないnodeへはlevelを表示せず捏造しない。level表示は表示のみで設定・通知を変えない(renderer統合)
test("RND-013 node levels in fissure table", async ({ page }) => {
  await bootConsole(page);
  // 鋼(isHard)の亀裂は基底node levelへ+100した範囲を表示する
  const kuva = page.locator("#fissure-rows tr", { hasText: "Taveuni" });
  await expect(kuva.locator(".col-node .t-level")).toHaveText("LV 132-137");
  // 通常亀裂は基底levelをそのまま表示する
  const normal = page.locator("#fissure-rows tr", { hasText: "Hepit" });
  await expect(normal.locator(".col-node .t-node")).toHaveText("Hepit (Void)");
  await expect(normal.locator(".col-node .t-level")).toHaveText("LV 10-15");
  // 行tooltipにも同じ値を含める
  expect(await kuva.getAttribute("title")).toContain("LV 132-137");
  expect(await normal.getAttribute("title")).toContain("LV 10-15");
  // lookupにないnodeへはlevelを表示しない(捏造しない)
  const unknown = page.locator("#fissure-rows tr", { hasText: "Nsu Grid" });
  await expect(unknown.locator(".col-node .t-node")).toHaveText("Nsu Grid (Veil Proxima)");
  await expect(unknown.locator(".col-node .t-level")).toHaveCount(0);
  expect(await unknown.getAttribute("title")).not.toContain("LV");
  // level表示は表示のみ: 設定・通知の変更を呼ばない
  expect(
    (await calls(page)).filter((entry) =>
      ["set_config", "set_rule_enabled", "set_rule_notify", "apply_candidate"].includes(entry.cmd),
    ).length,
  ).toBe(0);
});

// RND-011: DELIVERYの通知ミュートUIはON/OFFと開始・終了時刻をAppConfig.notificationMute(enabled/startMinute/endMinute)へ保存し、backend snapshotのnotificationsMuted=trueを独自判定せず状態表示する。設定操作はルール・VIEW・NOTIFYを変えず、TEST DELIVERYはミュート表示中でも実行経路へ進む(renderer統合)
test("RND-011 notification mute window", async ({ page }) => {
  await bootConsole(page, { locale: "en", notificationsMuted: true });
  await page.locator("#delivery-tab").click();
  await expect(page.locator("#mute-status")).toHaveAttribute("data-muted", "true");
  await expect(page.locator("#mute-status")).toBeVisible();

  const rulesBefore = await page.locator("#rules-list .rule-row").count();
  await expect(page.locator("#mute-check")).toHaveAttribute("aria-pressed", "false");
  await expect(page.locator("#mute-start-input")).toBeDisabled();
  await expect(page.locator("#mute-end-input")).toBeDisabled();
  await page.locator("#mute-check").click();
  await expect(page.locator("#mute-check")).toHaveAttribute("aria-pressed", "true");
  await expect(page.locator("#mute-start-input")).toBeEnabled();
  await expect(page.locator("#mute-end-input")).toBeEnabled();
  await page.locator("#mute-start-input").fill("22:15");
  await page.locator("#mute-start-input").dispatchEvent("change");
  await page.locator("#mute-end-input").fill("06:45");
  await page.locator("#mute-end-input").dispatchEvent("change");

  await expect
    .poll(async () =>
      (await calls(page)).some(
        (entry) =>
          entry.cmd === "set_config" &&
          entry.args.config.notificationMute.enabled === true &&
          entry.args.config.notificationMute.startMinute === 1335 &&
          entry.args.config.notificationMute.endMinute === 405,
      ),
    )
    .toBe(true);
  await expect(page.locator("#rules-list .rule-row")).toHaveCount(rulesBefore);
  expect(
    (await calls(page)).filter((entry) =>
      ["set_rule_enabled", "set_rule_notify", "apply_candidate", "clear_filter"].includes(entry.cmd),
    ),
  ).toHaveLength(0);

  // backendがMUTEDと報告していても、明示操作のTEST DELIVERYは抑止しない。
  await page.locator("#test-btn").click();
  await expect
    .poll(async () => (await calls(page)).some((entry) => entry.cmd === "test_notification"))
    .toBe(true);
});

// RND-012: locale=ja/en/zh-Hansの各表示はcritical semantic DOM goldenと一致し、html lang、document.title、本文・aria-label・placeholderに加えて仲裁のcommunity schedule表示、Areaの5 group見出しと環境state、Circuitの通常/鋼候補見出しの言語が揃い、missing-key markerを残さない。720x480と950x620でページ全体・railに意図しないoverflowを生まず、各タブ自身のラベルは見切れない(renderer統合)
const localeGoldens = {
  ja: {
    text: [
      ["#tab-fissures", "tabs.fissures", "亀裂"],
      ["#tab-arbitration", "tabs.arbitration", "仲裁"],
      ["#tab-sortie", "tabs.sortie", "ソーティー"],
      ["#tab-archon", "tabs.archon", "アルコン討伐戦"],
      ["#tab-syndicates", "tabs.syndicates", "シンジケート"],
      ["#tab-area-missions", "tabs.areaMissions", "地位ミッション"],
      ["#tab-circuit", "tabs.circuit", "サーキット"],
      ["#tab-archimedea", "tabs.archimedea", "アルキメデア"],
      ["#tab-descendia", "tabs.descendia", "ディセンディア"],
      ["#filters-tab", "sidebar.filters", "フィルター"],
      ["#delivery-tab", "sidebar.delivery", "通知"],
      ["#test-btn", "delivery.test", "通知をテスト"],
      ["#pause-btn", "common.pause", "一時停止"],
      ['#mute-check [data-i18n-key="delivery.muteSchedule"]', "delivery.muteSchedule", "通知ミュート"],
    ],
    appTitle: "RELICO — 時限コンテンツ",
    tabsLabel: "時限コンテンツ",
    languageLabel: "表示言語",
    rulePlaceholder: "ルール名 (R1)",
    arbitrationProvenance: "コミュニティ予測",
    areaGroups: ["環境サイクル", "通常依頼", "ローカル依頼候補", "追加依頼", "エリアイベント"],
    environmentState: "状態 昼",
    circuitStages: ["通常サーキット", "鋼の道のりサーキット"],
  },
  en: {
    text: [
      ["#tab-fissures", "tabs.fissures", "Fissures"],
      ["#tab-arbitration", "tabs.arbitration", "Arbitration"],
      ["#tab-sortie", "tabs.sortie", "Sortie"],
      ["#tab-archon", "tabs.archon", "Archon Hunt"],
      ["#tab-syndicates", "tabs.syndicates", "Syndicates"],
      ["#tab-area-missions", "tabs.areaMissions", "Area Missions"],
      ["#tab-circuit", "tabs.circuit", "Circuit"],
      ["#tab-archimedea", "tabs.archimedea", "Archimedea"],
      ["#tab-descendia", "tabs.descendia", "Descendia"],
      ["#filters-tab", "sidebar.filters", "Filters"],
      ["#delivery-tab", "sidebar.delivery", "Delivery"],
      ["#test-btn", "delivery.test", "Test Delivery"],
      ["#pause-btn", "common.pause", "Pause"],
      ['#mute-check [data-i18n-key="delivery.muteSchedule"]', "delivery.muteSchedule", "Notification mute"],
    ],
    appTitle: "RELICO — TIMED CONTENT",
    tabsLabel: "Timed content",
    languageLabel: "Display language",
    rulePlaceholder: "Rule name (R1)",
    arbitrationProvenance: "Community prediction",
    areaGroups: ["Environments", "Open-world bounties", "Objective rotations", "Additional bounties", "Area events"],
    environmentState: "State Day",
    circuitStages: ["Normal Circuit", "Steel Path Circuit"],
  },
  "zh-Hans": {
    text: [
      ["#tab-fissures", "tabs.fissures", "裂隙"],
      ["#tab-arbitration", "tabs.arbitration", "仲裁"],
      ["#tab-sortie", "tabs.sortie", "突击"],
      ["#tab-archon", "tabs.archon", "执刑官猎杀"],
      ["#tab-syndicates", "tabs.syndicates", "集团"],
      ["#tab-area-missions", "tabs.areaMissions", "地区任务"],
      ["#tab-circuit", "tabs.circuit", "无尽回廊"],
      ["#tab-archimedea", "tabs.archimedea", "科研考察"],
      ["#tab-descendia", "tabs.descendia", "后裔战场"],
      ["#filters-tab", "sidebar.filters", "筛选"],
      ["#delivery-tab", "sidebar.delivery", "通知"],
      ["#test-btn", "delivery.test", "测试通知"],
      ["#pause-btn", "common.pause", "暂停"],
      ['#mute-check [data-i18n-key="delivery.muteSchedule"]', "delivery.muteSchedule", "通知静音"],
    ],
    appTitle: "RELICO — 限时内容",
    tabsLabel: "限时内容",
    languageLabel: "显示语言",
    rulePlaceholder: "规则名称 (R1)",
    arbitrationProvenance: "社区预测",
    areaGroups: ["环境周期", "开放世界赏金", "目标轮换", "额外赏金", "地区活动"],
    environmentState: "状态 白昼",
    circuitStages: ["普通无尽回廊", "钢铁之路无尽回廊"],
  },
} as const;

for (const [locale, golden] of Object.entries(localeGoldens)) {
  test("RND-012 semantic DOM golden " + locale, async ({ page }) => {
    await page.setViewportSize({ width: 720, height: 480 });
    await bootConsole(page, { locale: locale as "ja" | "en" | "zh-Hans" });
    await expect(page.locator("html")).toHaveAttribute("lang", locale);
    await expect(page.locator("#locale-select")).toHaveValue(locale);
    await expect(page).toHaveTitle(golden.appTitle);

    for (const [selector, key, expectedText] of golden.text) {
      const node = page.locator(selector);
      await expect(node).toHaveAttribute("data-i18n-key", key);
      await expect(node).toHaveText(expectedText);
    }
    await expect(page.locator("#content-tabs")).toHaveAttribute("data-i18n-aria-label-key", "tabs.label");
    await expect(page.locator("#content-tabs")).toHaveAttribute("aria-label", golden.tabsLabel);
    await expect(page.locator("#locale-select")).toHaveAttribute(
      "data-i18n-aria-label-key",
      "delivery.language",
    );
    await expect(page.locator("#locale-select")).toHaveAttribute("aria-label", golden.languageLabel);
    await expect(page.locator("#rulename-input")).toHaveAttribute(
      "data-i18n-placeholder-key",
      "rules.namePlaceholder",
    );
    await expect(page.locator("#rulename-input")).toHaveAttribute("placeholder", golden.rulePlaceholder);
    await expect(
      page.locator('#panel-arbitration .timed-card[data-provenance="community-schedule"] .timed-provenance-badge'),
    ).toHaveText(golden.arbitrationProvenance);
    await page.locator("#tab-area-missions").click();
    const areaHeadings = page.locator("#panel-area-missions .timed-group-heading");
    await expect(areaHeadings).toHaveCount(5);
    for (const [index, expected] of golden.areaGroups.entries()) {
      await expect(areaHeadings.nth(index)).toHaveText(expected);
    }
    await expect(
      page.locator('#panel-area-missions .timed-card-group[data-group="environments"] .timed-card').first().locator(".timed-meta"),
    ).toContainText(golden.environmentState);
    const circuitStages = page.locator("#panel-circuit .timed-stage-title");
    await expect(circuitStages).toHaveCount(2);
    await expect(circuitStages.nth(0)).toHaveText(golden.circuitStages[0]);
    await expect(circuitStages.nth(1)).toHaveText(golden.circuitStages[1]);
    await expect(page.locator("[data-i18n-missing]")).toHaveCount(0);
    expect(await page.locator("body").innerText()).not.toMatch(/\[\[[^\]]+\]\]/);

    for (const width of [720, 950]) {
      await page.setViewportSize({ width, height: 620 });
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
      expect(await page.locator(".rail").evaluate((el) => el.scrollHeight <= el.clientHeight)).toBe(true);
      const tabLabelsFit = await page.locator('#content-tabs [role="tab"]').evaluateAll((tabs) =>
        tabs.every((tab) => tab.scrollWidth <= tab.clientWidth),
      );
      expect(tabLabelsFit).toBe(true);
    }
  });
}
