// @generated by tools/spec-gen.ts from specs/notifier.pkl — DO NOT EDIT
// テストを直したくなったら specs/ を編集して `just spec-gen` を実行する。
// WDIO Tauri E2E: 実アプリ(実IPC・実WKWebView)を通す。DOM結線の網羅はrenderer統合(RND)が担い、
// ここは「本物のRust commandを往復する」ことの証明に絞る。
// 実行: just e2e (e2e featureビルド + @wdio/tauri-service embedded provider)

import { $, browser, expect } from "@wdio/globals";

async function waitForInit(): Promise<void> {
  // title同期前に$()/findElementを呼ぶとtauri-serviceのauto-focusが旧titleを探索するため、
  // 初期ready判定はfocus hook対象外のexecuteだけで行う。
  await browser.waitUntil(async () => await browser.execute(() => {
    const watch = document.querySelector("#sb-watch");
    return document.readyState === "complete" && Boolean(watch?.textContent?.trim());
  }), {
    timeout: 20000,
    timeoutMsg: "コンソールが初期化されない",
  });
}

// E2E-001: 実アプリでパレット打鍵→候補適用が本物のquery_candidates/apply_candidateを往復し、ルールsummaryとwatch行へ反映される(WDIO Tauri E2E、専用identity)
describe("E2E-001", () => {
  it("palette apply round-trips through real IPC", async () => {
    await waitForInit();
    // どこでも打鍵でパレットが開き(打鍵結線自体はRND-001)、実Rustのfuzzy(FZY-003)が候補を返す
    await browser.keys("a");
    await browser.waitUntil(async () => await $("#palette-overlay").isDisplayed(), {
      timeoutMsg: "パレットが開かない",
    });
    await browser.keys("xi");
    await browser.keys("Enter");
    // 実apply_candidateのApplyResultがrule summaryへ反映される(アイコンチップ+title=実名)
    await browser.waitUntil(
      async () => await $('.rule-summary .rule-chip[title="AXI"]').isExisting(),
      { timeoutMsg: "実IPCのapply_candidate結果がsummaryへ反映されない" },
    );
    await browser.keys("Escape");
    await browser.waitUntil(async () => !(await $("#palette-overlay").isDisplayed()));
    // 実configへ保存され、watch行にも反映されている
    await expect($("#sb-watch")).toHaveText(expect.stringContaining("AXI"));
  });
});

// E2E-002: 実アプリで通知先を全て無効にしたTEST DELIVERYが、本物のset_config・test_notificationを通り、NTF-001の失敗理由(通知先なし)をrailへ表示する(WDIO Tauri E2E)
describe("E2E-002", () => {
  it("TEST DELIVERY surfaces the real backend outcome", async () => {
    await waitForInit();
    await $("#delivery-tab").click();
    // desktopをOFFにして通知先ゼロにする(設定変更も実set_configを通る)
    const desktopCheck = $("#desktop-check");
    if ((await desktopCheck.getText()).includes("[x]")) {
      await desktopCheck.click();
      await browser.waitUntil(async () => (await desktopCheck.getText()).includes("[ ]"));
    }
    await $("#test-btn").click();
    // 実test_notificationがNTF-001の「通知先なしは失敗」を返し、railへ表示される
    await browser.waitUntil(
      async () => (await $("#rail-msg").getText()).includes("通知先"),
      { timeoutMsg: "実backendの失敗理由がrail-msgへ表示されない" },
    );
    await expect($("#rail-msg")).not.toHaveText(expect.stringContaining("受け付けました"));
  });
});

// E2E-003: 実アプリの起動時ja、en変更後、zh-Hans変更後、再読込後でdocument.titleとmain native window titleが各localeのapp.titleへ同期し、表示言語は本物のset_config完了後にhtml langとcritical UIへ反映され、再読込後も実get_configからzh-Hansが復元される(WDIO Tauri E2E)
describe("E2E-003", () => {
  it("locale round-trips through real config IPC", async () => {
    const expectSynchronizedTitle = async (expected: string) => {
      const documentTitle = await browser.execute(() => document.title);
      const states = (await browser.tauri.execute(({ core }) =>
        core.invoke("plugin:wdio|get_window_states"),
      )) as Array<{ label: string; title: string }>;
      expect(documentTitle).toBe(expected);
      expect(states.find((state) => state.label === "main")?.title).toBe(expected);
    };
    const selectLocale = async (locale: "en" | "zh-Hans") => {
      await $("#locale-select").selectByAttribute("value", locale);
      // tauri-plugin-wdioのWebKit select helperは値だけを変えてchangeを発火しないため、
      // rendererで検証済みのDOM結線を明示発火し、その先の実set_config往復をここで検査する。
      await browser.execute((nextLocale) => {
        const select = document.querySelector("#locale-select") as HTMLSelectElement | null;
        if (!select) throw new Error("locale-select not found");
        select.value = nextLocale;
        select.dispatchEvent(new Event("change", { bubbles: true }));
      }, locale);
      await browser.waitUntil(
        async () => (await browser.execute(() => document.documentElement.lang)) === locale,
        { timeoutMsg: "locale変更が実set_config完了後に反映されない" },
      );
    };

    await waitForInit();
    await expectSynchronizedTitle("RELICO — 時限コンテンツ");
    await $("#delivery-tab").click();
    await selectLocale("en");
    await expectSynchronizedTitle("RELICO — TIMED CONTENT");
    await selectLocale("zh-Hans");
    await expectSynchronizedTitle("RELICO — 限时内容");
    await expect($("#tab-fissures")).toHaveText("裂隙");

    await browser.refresh();
    await waitForInit();
    await expect($("html")).toHaveAttribute("lang", "zh-Hans");
    await expect($("#locale-select")).toHaveValue("zh-Hans");
    await expect($("#tab-fissures")).toHaveText("裂隙");
    await expectSynchronizedTitle("RELICO — 限时内容");
  });
});

// E2E-004: 実アプリのmanual_reload commandは本物のIPCを往復し、呼ぶたびに単調増加する要求番号を返して亀裂pollerと時限コンテンツpollerの待機解除要求を発行する(WDIO Tauri E2E)
describe("E2E-004", () => {
  it("manual reload round-trips through real IPC", async () => {
    await waitForInit();
    const first = (await browser.tauri.execute(({ core }) =>
      core.invoke("manual_reload"),
    )) as number;
    const second = (await browser.tauri.execute(({ core }) =>
      core.invoke("manual_reload"),
    )) as number;
    expect(first).toBeGreaterThan(0);
    expect(second).toBeGreaterThan(first);
  });
});
