// @generated by tools/spec-gen.ts from specs/notifier.pkl — DO NOT EDIT
// テストを直したくなったら specs/ を編集して `just spec-gen` を実行する。
// WDIO Tauri E2E: 実アプリ(実IPC・実WKWebView)を通す。DOM結線の網羅はrenderer統合(RND)が担い、
// ここは「本物のRust commandを往復する」ことの証明に絞る。
// 実行: just e2e (e2e featureビルド + @wdio/tauri-service embedded provider)

import { $, browser, expect } from "@wdio/globals";

async function waitForInit(): Promise<void> {
  await browser.waitUntil(async () => (await $("#sb-watch").getText()).length > 0, {
    timeout: 20000,
    timeoutMsg: "コンソールが初期化されない",
  });
}

// E2E-001: 実アプリでパレット打鍵→候補適用が本物のquery_candidates/apply_candidateを往復し、ルールsummaryとwatch行へ反映される(WDIO Tauri E2E、専用identity)
describe("E2E-001", () => {
  it("palette apply round-trips through real IPC", async () => {
    await waitForInit();
    // どこでも打鍵でパレットが開き(打鍵結線自体はRND-001)、実Rustのfuzzy(FZY-003)が候補を返す
    await browser.keys("a");
    await browser.waitUntil(async () => await $("#palette-overlay").isDisplayed(), {
      timeoutMsg: "パレットが開かない",
    });
    await browser.keys("xi");
    await browser.keys("Enter");
    // 実apply_candidateのApplyResultがrule summaryへ反映される
    await browser.waitUntil(
      async () => (await $(".rule-summary").getText()).includes("AXI"),
      { timeoutMsg: "実IPCのapply_candidate結果がsummaryへ反映されない" },
    );
    await browser.keys("Escape");
    await browser.waitUntil(async () => !(await $("#palette-overlay").isDisplayed()));
    // 実configへ保存され、watch行にも反映されている
    await expect($("#sb-watch")).toHaveText(expect.stringContaining("AXI"));
  });
});

// E2E-002: 実アプリで通知先を全て無効にしたTEST DELIVERYが、本物のset_config・test_notificationを通り、NTF-001の失敗理由(通知先なし)をrailへ表示する(WDIO Tauri E2E)
describe("E2E-002", () => {
  it("TEST DELIVERY surfaces the real backend outcome", async () => {
    await waitForInit();
    await $("#delivery-tab").click();
    // desktopをOFFにして通知先ゼロにする(設定変更も実set_configを通る)
    const desktopCheck = $("#desktop-check");
    if ((await desktopCheck.getText()).includes("[x]")) {
      await desktopCheck.click();
      await browser.waitUntil(async () => (await desktopCheck.getText()).includes("[ ]"));
    }
    await $("#test-btn").click();
    // 実test_notificationがNTF-001の「通知先なしは失敗」を返し、railへ表示される
    await browser.waitUntil(
      async () => (await $("#rail-msg").getText()).includes("通知先"),
      { timeoutMsg: "実backendの失敗理由がrail-msgへ表示されない" },
    );
    await expect($("#rail-msg")).not.toHaveText(expect.stringContaining("受け付けました"));
  });
});

// E2E-003: 実アプリで表示言語をzh-Hansへ変更すると、本物のset_config完了後にhtml langとcritical UIが切り替わり、再読込後も実get_configからzh-Hansが復元される(WDIO Tauri E2E)
describe("E2E-003", () => {
  it("locale round-trips through real config IPC", async () => {
    await waitForInit();
    await $("#delivery-tab").click();
    await $("#locale-select").selectByAttribute("value", "zh-Hans");
    // tauri-plugin-wdioのWebKit select helperは値だけを変えてchangeを発火しないため、
    // rendererで検証済みのDOM結線を明示発火し、その先の実set_config往復をここで検査する。
    await browser.execute(() => {
      const select = document.querySelector("#locale-select") as HTMLSelectElement | null;
      if (!select) throw new Error("locale-select not found");
      select.value = "zh-Hans";
      select.dispatchEvent(new Event("change", { bubbles: true }));
    });
    // html langの切替はset_config成功後に行う契約なので、ここまで待てば永続化も完了している。
    await browser.waitUntil(
      async () => (await $("html").getAttribute("lang")) === "zh-Hans",
      { timeoutMsg: "locale変更が実set_config完了後に反映されない" },
    );
    await expect($("#tab-fissures")).toHaveText("裂隙");

    await browser.refresh();
    await waitForInit();
    await expect($("html")).toHaveAttribute("lang", "zh-Hans");
    await expect($("#locale-select")).toHaveValue("zh-Hans");
    await expect($("#tab-fissures")).toHaveText("裂隙");
  });
});
