// @generated by tools/spec-gen.ts from specs/notifier.pkl — DO NOT EDIT
// テストを直したくなったら specs/ を編集して `just spec-gen` を実行する。
// 各テスト名は docs/SPEC.md の条項idに対応する。

use std::collections::HashMap;

use chrono::{DateTime, Duration, TimeZone, Utc};
use proptest::prelude::*;
use warframe_fissure_notifier_lib::backoff::Backoff;
use warframe_fissure_notifier_lib::dedup::NotifiedSet;
use warframe_fissure_notifier_lib::filter::{self, FilterConfig, Mode};
use warframe_fissure_notifier_lib::model::Fissure;

const TIERS: &[&str] = &["Lith", "Meso", "Neo", "Axi", "Requiem", "Omnia"];
const MISSIONS: &[&str] = &[
    "Defense", "Survival", "Capture", "Extermination", "Rescue",
    "Disruption", "Mobile Defense", "Void Flood", "Sabotage",
];
const PLANETS: &[&str] = &[
    "Mars", "Ceres", "Sedna", "Void", "Saturn", "Phobos",
    "Zariman", "Veil Proxima", "Kuva Fortress", "Lua",
];

/// オラクルは純粋関数を対象とするため、現在時刻は固定値でよい
fn base_now() -> DateTime<Utc> {
    Utc.with_ymd_and_hms(2026, 1, 1, 0, 0, 0).unwrap()
}

fn arb_mode() -> impl Strategy<Value = Mode> {
    prop_oneof![Just(Mode::Normal), Just(Mode::SteelPath), Just(Mode::Both)]
}

fn arb_subset(pool: &'static [&'static str]) -> impl Strategy<Value = Vec<String>> {
    proptest::sample::subsequence(pool.to_vec(), 0..=pool.len())
        .prop_map(|v| v.into_iter().map(String::from).collect())
}

fn arb_config() -> impl Strategy<Value = FilterConfig> {
    (
        arb_subset(TIERS),
        arb_subset(MISSIONS),
        arb_subset(PLANETS),
        arb_mode(),
        any::<bool>(),
        0u64..1800,
    )
        .prop_map(
            |(tiers, mission_types, planets, mode, include_storms, min_remaining_secs)| {
                FilterConfig {
                    tiers,
                    mission_types,
                    planets,
                    mode,
                    include_storms,
                    min_remaining_secs,
                }
            },
        )
}

fn arb_fissure() -> impl Strategy<Value = Fissure> {
    (
        "[a-f0-9]{8}",
        proptest::sample::select(TIERS.to_vec()),
        proptest::sample::select(MISSIONS.to_vec()),
        proptest::sample::select(PLANETS.to_vec()),
        any::<bool>(),
        any::<bool>(),
        -600i64..7200,
    )
        .prop_map(|(id, tier, mission, planet, is_storm, is_hard, expiry_off)| {
            let now = base_now();
            Fissure {
                id,
                activation: now - Duration::hours(1),
                expiry: now + Duration::seconds(expiry_off),
                node: format!("Node ({planet})"),
                mission_type: mission.to_string(),
                enemy: "Grineer".to_string(),
                tier: tier.to_string(),
                tier_num: 1,
                is_storm,
                is_hard,
            }
        })
}

proptest! {

    /// FLT-001: mode=鋼のみ のとき、isHard=false の亀裂はどんな入力でも通知されない
    #[test]
    fn flt_001(mut cfg in arb_config(), mut f in arb_fissure()) {
        let now = base_now();
        let _ = &now;
        cfg.mode = Mode::SteelPath;
        f.is_hard = false;
        prop_assert!(!filter::matches(&cfg, &f, now), "SPEC FLT-001 違反: mode=鋼のみ のとき、isHard=false の亀裂はどんな入力でも通知されない");
    }

    /// FLT-002: mode=通常のみ のとき、isHard=true の亀裂はどんな入力でも通知されない
    #[test]
    fn flt_002(mut cfg in arb_config(), mut f in arb_fissure()) {
        let now = base_now();
        let _ = &now;
        cfg.mode = Mode::Normal;
        f.is_hard = true;
        prop_assert!(!filter::matches(&cfg, &f, now), "SPEC FLT-002 違反: mode=通常のみ のとき、isHard=true の亀裂はどんな入力でも通知されない");
    }

    /// FLT-003: include_storms=false のとき、isStorm=true の亀裂(ボイドストーム)は通知されない
    #[test]
    fn flt_003(mut cfg in arb_config(), mut f in arb_fissure()) {
        let now = base_now();
        let _ = &now;
        cfg.include_storms = false;
        f.is_storm = true;
        prop_assert!(!filter::matches(&cfg, &f, now), "SPEC FLT-003 違反: include_storms=false のとき、isStorm=true の亀裂(ボイドストーム)は通知されない");
    }

    /// FLT-004: tiersが空のとき、tierを理由に棄却されない(空=全tier対象)
    #[test]
    fn flt_004(cfg in arb_config(), f in arb_fissure()) {
        let now = base_now();
        let mut empty_cfg = cfg.clone();
        empty_cfg.tiers = vec![];
        let mut pinned_cfg = cfg;
        pinned_cfg.tiers = vec![f.tier.clone()];
        prop_assert_eq!(
            filter::matches(&empty_cfg, &f, now),
            filter::matches(&pinned_cfg, &f, now),
            "SPEC FLT-004 違反: tiersが空のとき、tierを理由に棄却されない(空=全tier対象)"
        );
    }

    /// FLT-005: mission_typesが空のとき、ミッション種別を理由に棄却されない(空=全種別対象)
    #[test]
    fn flt_005(cfg in arb_config(), f in arb_fissure()) {
        let now = base_now();
        let mut empty_cfg = cfg.clone();
        empty_cfg.mission_types = vec![];
        let mut pinned_cfg = cfg;
        pinned_cfg.mission_types = vec![f.mission_type.clone()];
        prop_assert_eq!(
            filter::matches(&empty_cfg, &f, now),
            filter::matches(&pinned_cfg, &f, now),
            "SPEC FLT-005 違反: mission_typesが空のとき、ミッション種別を理由に棄却されない(空=全種別対象)"
        );
    }

    /// FLT-006: planetsが空のとき、惑星を理由に棄却されない(空=全惑星対象)
    #[test]
    fn flt_006(cfg in arb_config(), f in arb_fissure()) {
        let now = base_now();
        let mut empty_cfg = cfg.clone();
        empty_cfg.planets = vec![];
        let mut pinned_cfg = cfg;
        pinned_cfg.planets = filter::extract_planet(&f.node).into_iter().collect();
        prop_assert_eq!(
            filter::matches(&empty_cfg, &f, now),
            filter::matches(&pinned_cfg, &f, now),
            "SPEC FLT-006 違反: planetsが空のとき、惑星を理由に棄却されない(空=全惑星対象)"
        );
    }

    /// FLT-007: 残り時間がmin_remaining_secs未満の亀裂は通知されない(期限切れ含む)
    #[test]
    fn flt_007(mut cfg in arb_config(), mut f in arb_fissure()) {
        let now = base_now();
        let _ = &now;

        f.expiry = now + Duration::seconds((cfg.min_remaining_secs as i64) - 1);
        prop_assert!(!filter::matches(&cfg, &f, now), "SPEC FLT-007 違反: 残り時間がmin_remaining_secs未満の亀裂は通知されない(期限切れ含む)");
    }

    /// DED-001: 同一亀裂idは任意のポーリング列で高々1回しか通知されない
    #[test]
    fn ded_001(ids in proptest::collection::vec("[a-c][0-9]", 0..60)) {
        let far = base_now() + Duration::hours(2);
        let mut set = NotifiedSet::new();
        let mut times_notified: HashMap<String, usize> = HashMap::new();
        for id in &ids {
            if set.mark(id, far) {
                *times_notified.entry(id.clone()).or_default() += 1;
            }
        }
        prop_assert!(times_notified.values().all(|&c| c <= 1), "SPEC DED-001 違反: 同一亀裂idは任意のポーリング列で高々1回しか通知されない");
    }

    /// DED-002: pruneは生存中idの通知済み状態を保持し、期限切れidを除去する
    #[test]
    fn ded_002(n_live in 0usize..20, n_dead in 0usize..20) {
        let now = base_now();
        let mut set = NotifiedSet::new();
        for i in 0..n_live { set.mark(&format!("L{i}"), now + Duration::hours(1)); }
        for i in 0..n_dead { set.mark(&format!("D{i}"), now - Duration::hours(1)); }
        set.prune(now);
        for i in 0..n_live {
            prop_assert!(set.contains(&format!("L{i}")), "SPEC DED-002 違反: pruneは生存中idの通知済み状態を保持し、期限切れidを除去する (生存idが消えた)");
        }
        for i in 0..n_dead {
            prop_assert!(!set.contains(&format!("D{i}")), "SPEC DED-002 違反: pruneは生存中idの通知済み状態を保持し、期限切れidを除去する (期限切れidが残った)");
        }
    }

    /// PRS-001: 惑星抽出は任意文字列でパニックせず、"Node (Planet)" 形式でPlanetを返す (全入力でパニックしない)
    #[test]
    fn prs_001_total(s in ".*") {
        let _ = filter::extract_planet(&s);
    }

    /// PRS-001: 惑星抽出は任意文字列でパニックせず、"Node (Planet)" 形式でPlanetを返す (整形式で括弧内を返す)
    #[test]
    fn prs_001_wellformed(name in "[A-Za-z][A-Za-z ]{0,14}", planet in "[A-Za-z][A-Za-z ]{0,14}") {
        let planet = planet.trim().to_string();
        prop_assume!(!planet.is_empty());
        let node = format!("{} ({})", name.trim(), planet);
        prop_assert_eq!(filter::extract_planet(&node), Some(planet), "SPEC PRS-001 違反: 惑星抽出は任意文字列でパニックせず、\"Node (Planet)\" 形式でPlanetを返す");
    }

    /// POL-001: APIバックオフの遅延は失敗・成功がどう並んでも常に[60s, 600s]に収まる
    #[test]
    fn pol_001(ops in proptest::collection::vec(any::<bool>(), 0..100)) {
        let mut b = Backoff::new(60, 600);
        for fail in ops {
            let v = if fail { b.on_failure() } else { b.on_success() };
            prop_assert!((60..=600).contains(&v), "SPEC POL-001 違反: APIバックオフの遅延は失敗・成功がどう並んでも常に[60s, 600s]に収まる (v={})", v);
        }
    }
}
