// @generated by tools/spec-gen.ts from specs/notifier.pkl — DO NOT EDIT
// テストを直したくなったら specs/ を編集して `just spec-gen` を実行する。
// 各テスト名は docs/SPEC.md の条項idに対応する。

use std::collections::HashMap;

use chrono::{DateTime, Duration, TimeZone, Utc};
use proptest::prelude::*;
use relico_lib::backoff::Backoff;
use relico_lib::dedup::NotifiedSet;
use relico_lib::filter::{self, FilterSettings, Mode, StormMode, WatchRule};
use relico_lib::model::Fissure;
use relico_lib::notify::{self, NotificationOutcome};
use relico_lib::palette::{self, Candidate, Facet};
use relico_lib::poller;

const TIERS: &[&str] = &["Lith", "Meso", "Neo", "Axi", "Requiem", "Omnia"];
const MISSIONS: &[&str] = &["Defense", "Survival", "Capture", "Extermination", "Rescue", "Disruption", "Mobile Defense", "Void Flood", "Void Cascade", "Volatile"];
const PLANETS: &[&str] = &["Mars", "Ceres", "Sedna", "Void", "Saturn", "Phobos", "Zariman", "Veil Proxima", "Kuva Fortress", "Lua"];

/// オラクルは純粋関数を対象とするため、現在時刻は固定値でよい
fn base_now() -> DateTime<Utc> {
    Utc.with_ymd_and_hms(2026, 1, 1, 0, 0, 0).unwrap()
}

fn arb_mode() -> impl Strategy<Value = Mode> {
    prop_oneof![Just(Mode::Normal), Just(Mode::SteelPath), Just(Mode::Both)]
}

fn arb_storm_mode() -> impl Strategy<Value = StormMode> {
    prop_oneof![
        Just(StormMode::Exclude),
        Just(StormMode::Include),
        Just(StormMode::Only),
    ]
}

fn arb_subset(pool: &'static [&'static str]) -> impl Strategy<Value = Vec<String>> {
    proptest::sample::subsequence(pool.to_vec(), 0..=pool.len())
        .prop_map(|v| v.into_iter().map(String::from).collect())
}

fn arb_rule_name() -> impl Strategy<Value = Option<String>> {
    proptest::option::of("[A-Za-z0-9 ]{1,12}")
}

fn arb_rule() -> impl Strategy<Value = WatchRule> {
    (
        any::<bool>(),
        any::<bool>(),
        arb_rule_name(),
        arb_subset(TIERS),
        arb_subset(MISSIONS),
        arb_subset(PLANETS),
        arb_mode(),
        arb_storm_mode(),
    )
        .prop_map(|(enabled, notify, name, tiers, mission_types, planets, mode, storms)| WatchRule {
            enabled,
            notify,
            name,
            tiers,
            mission_types,
            planets,
            mode,
            storms,
        })
}

fn arb_settings() -> impl Strategy<Value = FilterSettings> {
    (proptest::collection::vec(arb_rule(), 0..4), 0u64..1800)
        .prop_map(|(rules, min_remaining_secs)| FilterSettings {
            rules,
            min_remaining_secs,
        })
}

fn arb_fissure() -> impl Strategy<Value = Fissure> {
    (
        "[a-f0-9]{8}",
        proptest::sample::select(TIERS.to_vec()),
        proptest::sample::select(MISSIONS.to_vec()),
        proptest::sample::select(PLANETS.to_vec()),
        any::<bool>(),
        any::<bool>(),
        -600i64..7200,
    )
        .prop_map(|(id, tier, mission, planet, is_storm, is_hard, expiry_off)| {
            let now = base_now();
            Fissure {
                id,
                activation: now - Duration::hours(1),
                expiry: now + Duration::seconds(expiry_off),
                node: format!("Node ({planet})"),
                mission_type: mission.to_string(),
                enemy: "Grineer".to_string(),
                tier: tier.to_string(),
                tier_num: 1,
                is_storm,
                is_hard,
            }
        })
}

fn mk_catalog(labels: Vec<String>) -> Vec<Candidate> {
    labels
        .into_iter()
        .enumerate()
        .map(|(i, label)| Candidate {
            id: format!("test:{i}"),
            value: label.clone(),
            label,
            aliases: vec![],
            facet: Facet::Mission,
        })
        .collect()
}

proptest! {

    /// FLT-001: mode=鋼のみ のルールは、isHard=false の亀裂にどんな入力でも合致しない
    #[test]
    fn flt_001(mut rule in arb_rule(), mut f in arb_fissure()) {
        rule.mode = Mode::SteelPath;
        f.is_hard = false;
        prop_assert!(!filter::rule_matches(&rule, &f), "SPEC FLT-001 違反: mode=鋼のみ のルールは、isHard=false の亀裂にどんな入力でも合致しない");
    }

    /// FLT-002: mode=通常のみ のルールは、isHard=true の亀裂にどんな入力でも合致しない
    #[test]
    fn flt_002(mut rule in arb_rule(), mut f in arb_fissure()) {
        rule.mode = Mode::Normal;
        f.is_hard = true;
        prop_assert!(!filter::rule_matches(&rule, &f), "SPEC FLT-002 違反: mode=通常のみ のルールは、isHard=true の亀裂にどんな入力でも合致しない");
    }

    /// FLT-003: storms=除外 のルールは、isStorm=true の亀裂(VOID嵐)に合致しない
    #[test]
    fn flt_003(mut rule in arb_rule(), mut f in arb_fissure()) {
        rule.storms = StormMode::Exclude;
        f.is_storm = true;
        prop_assert!(!filter::rule_matches(&rule, &f), "SPEC FLT-003 違反: storms=除外 のルールは、isStorm=true の亀裂(VOID嵐)に合致しない");
    }

    /// FLT-010: storms=嵐のみ のルールは、isStorm=false の通常亀裂に合致しない(storm only指定)
    #[test]
    fn flt_010(mut rule in arb_rule(), mut f in arb_fissure()) {
        rule.storms = StormMode::Only;
        f.is_storm = false;
        prop_assert!(!filter::rule_matches(&rule, &f), "SPEC FLT-010 違反: storms=嵐のみ のルールは、isStorm=false の通常亀裂に合致しない(storm only指定)");
    }

    /// FLT-011: 他の条件が全対象なら、storms=除外/含む/嵐のみ は isStorm=false/true に対してそれぞれ (合致/棄却)/(合致/合致)/(棄却/合致) となる
    #[test]
    fn flt_011(mut f in arb_fissure()) {
        let mut rule = WatchRule {
            mode: Mode::Both,
            ..WatchRule::default()
        };
        for (storms, normal_matches, storm_matches) in [
            (StormMode::Exclude, true, false),
            (StormMode::Include, true, true),
            (StormMode::Only, false, true),
        ] {
            rule.storms = storms;
            f.is_storm = false;
            prop_assert_eq!(
                filter::rule_matches(&rule, &f),
                normal_matches,
                "SPEC FLT-011 違反: 他の条件が全対象なら、storms=除外/含む/嵐のみ は isStorm=false/true に対してそれぞれ (合致/棄却)/(合致/合致)/(棄却/合致) となる (mode={:?}, isStorm=false)",
                storms,
            );
            f.is_storm = true;
            prop_assert_eq!(
                filter::rule_matches(&rule, &f),
                storm_matches,
                "SPEC FLT-011 違反: 他の条件が全対象なら、storms=除外/含む/嵐のみ は isStorm=false/true に対してそれぞれ (合致/棄却)/(合致/合致)/(棄却/合致) となる (mode={:?}, isStorm=true)",
                storms,
            );
        }
    }

    /// FLT-012: VOID嵐ではUIのEarth/Venus/Saturn/Neptune/Pluto/Veil Proxima条件がAPI nodeの基底名Earth/Venus/Saturn/Neptune/Pluto/Veilに合致するが、通常亀裂にはProxima別名を適用しない
    #[test]
    fn flt_012(mut f in arb_fissure(), pick in any::<prop::sample::Index>()) {
        let aliases = [
            ("Earth Proxima", "Earth"),
            ("Venus Proxima", "Venus"),
            ("Saturn Proxima", "Saturn"),
            ("Neptune Proxima", "Neptune"),
            ("Pluto Proxima", "Pluto"),
            ("Veil Proxima", "Veil"),
        ];
        let (configured, api_planet) = aliases[pick.index(aliases.len())];
        let mut rule = WatchRule {
            planets: vec![configured.to_string()],
            mode: Mode::Both,
            storms: StormMode::Only,
            ..WatchRule::default()
        };
        f.is_storm = true;
        f.node = format!("Node ({api_planet})");
        prop_assert!(filter::rule_matches(&rule, &f), "SPEC FLT-012 違反: VOID嵐ではUIのEarth/Venus/Saturn/Neptune/Pluto/Veil Proxima条件がAPI nodeの基底名Earth/Venus/Saturn/Neptune/Pluto/Veilに合致するが、通常亀裂にはProxima別名を適用しない (VOID嵐が不一致)");

        rule.storms = StormMode::Include;
        f.is_storm = false;
        prop_assert!(!filter::rule_matches(&rule, &f), "SPEC FLT-012 違反: VOID嵐ではUIのEarth/Venus/Saturn/Neptune/Pluto/Veil Proxima条件がAPI nodeの基底名Earth/Venus/Saturn/Neptune/Pluto/Veilに合致するが、通常亀裂にはProxima別名を適用しない (通常亀裂へ別名を誤適用)");
    }

    /// FLT-004: ルールのtiersが空のとき、tierを理由に棄却しない(空=全tier対象)
    #[test]
    fn flt_004(rule in arb_rule(), f in arb_fissure()) {
        let mut empty_rule = rule.clone();
        empty_rule.tiers = vec![];
        let mut pinned_rule = rule;
        pinned_rule.tiers = vec![f.tier.clone()];
        prop_assert_eq!(
            filter::rule_matches(&empty_rule, &f),
            filter::rule_matches(&pinned_rule, &f),
            "SPEC FLT-004 違反: ルールのtiersが空のとき、tierを理由に棄却しない(空=全tier対象)"
        );
    }

    /// FLT-005: ルールのmission_typesが空のとき、ミッション種別を理由に棄却しない(空=全種別対象)
    #[test]
    fn flt_005(rule in arb_rule(), f in arb_fissure()) {
        let mut empty_rule = rule.clone();
        empty_rule.mission_types = vec![];
        let mut pinned_rule = rule;
        pinned_rule.mission_types = vec![f.mission_type.clone()];
        prop_assert_eq!(
            filter::rule_matches(&empty_rule, &f),
            filter::rule_matches(&pinned_rule, &f),
            "SPEC FLT-005 違反: ルールのmission_typesが空のとき、ミッション種別を理由に棄却しない(空=全種別対象)"
        );
    }

    /// FLT-006: ルールのplanetsが空のとき、惑星を理由に棄却しない(空=全惑星対象)
    #[test]
    fn flt_006(rule in arb_rule(), f in arb_fissure()) {
        let mut empty_rule = rule.clone();
        empty_rule.planets = vec![];
        let mut pinned_rule = rule;
        pinned_rule.planets = filter::extract_planet(&f.node).into_iter().collect();
        prop_assert_eq!(
            filter::rule_matches(&empty_rule, &f),
            filter::rule_matches(&pinned_rule, &f),
            "SPEC FLT-006 違反: ルールのplanetsが空のとき、惑星を理由に棄却しない(空=全惑星対象)"
        );
    }

    /// FLT-007: 残り時間がmin_remaining_secs未満の亀裂は、ルール構成に依らず合致しない(期限切れ含む)
    #[test]
    fn flt_007(s in arb_settings(), mut f in arb_fissure()) {
        let now = base_now();
        f.expiry = now + Duration::seconds((s.min_remaining_secs as i64) - 1);
        prop_assert!(!filter::matches(&s, &f, now), "SPEC FLT-007 違反: 残り時間がmin_remaining_secs未満の亀裂は、ルール構成に依らず合致しない(期限切れ含む)");
    }

    /// FLT-015: expiryが現在時刻以下の亀裂は、min_remaining_secs=0でもルール構成に依らず合致しない(生存条件はexpiry > now)
    #[test]
    fn flt_015(mut s in arb_settings(), mut f in arb_fissure()) {
        let now = base_now();
        s.min_remaining_secs = 0; f.expiry = now;
        prop_assert!(!filter::matches(&s, &f, now), "SPEC FLT-015 違反: expiryが現在時刻以下の亀裂は、min_remaining_secs=0でもルール構成に依らず合致しない(生存条件はexpiry > now)");
    }

    /// FLT-008: ルール1つの一覧表示判定では、全体合致 = (残り時間OK ∧ rule.enabled ∧ そのルールの条件が合致)
    #[test]
    fn flt_008(rule in arb_rule(), f in arb_fissure(), min in 0u64..1800) {
        let now = base_now();
        let s = FilterSettings { rules: vec![rule.clone()], min_remaining_secs: min };
        let remaining_ok = f.expiry > now
            && f.expiry.signed_duration_since(now).num_seconds() >= min as i64;
        prop_assert_eq!(
            filter::matches(&s, &f, now),
            remaining_ok && rule.enabled && filter::rule_matches(&rule, &f),
            "SPEC FLT-008 違反: ルール1つの一覧表示判定では、全体合致 = (残り時間OK ∧ rule.enabled ∧ そのルールの条件が合致)"
        );
    }

    /// FLT-009: 表示選択(enabled=true)ルールを追加しても、それまで一覧表示に合致していた亀裂は合致し続ける(表示ルールORの単調性)
    #[test]
    fn flt_009(s in arb_settings(), mut extra in arb_rule(), f in arb_fissure()) {
        let now = base_now();
        if filter::matches(&s, &f, now) {
            extra.enabled = true;
            let mut bigger = s.clone();
            bigger.rules.push(extra);
            prop_assert!(filter::matches(&bigger, &f, now), "SPEC FLT-009 違反: 表示選択(enabled=true)ルールを追加しても、それまで一覧表示に合致していた亀裂は合致し続ける(表示ルールORの単調性)");
        }
    }

    /// FLT-013: 一覧表示の全体合致は、残り時間条件を満たし、enabled=trueのルールの少なくとも1本が条件合致する場合に限る。表示選択なし、またはルールなしではフィルタ合致しない
    #[test]
    fn flt_013(s in arb_settings(), f in arb_fissure()) {
        let now = base_now();
        let remaining_ok = f.expiry > now
            && f.expiry.signed_duration_since(now).num_seconds()
                >= s.min_remaining_secs as i64;
        let enabled_or = s.rules.iter().any(|rule|
            rule.enabled && filter::rule_matches(rule, &f)
        );
        prop_assert_eq!(
            filter::matches(&s, &f, now),
            remaining_ok && enabled_or,
            "SPEC FLT-013 違反: 一覧表示の全体合致は、残り時間条件を満たし、enabled=trueのルールの少なくとも1本が条件合致する場合に限る。表示選択なし、またはルールなしではフィルタ合致しない (VIEWルールORの完全な等式)"
        );

        let mut all_disabled = s.clone();
        for rule in &mut all_disabled.rules {
            rule.enabled = false;
        }
        let mut valid_fissure = f.clone();
        valid_fissure.expiry = now + Duration::seconds(s.min_remaining_secs as i64 + 1);
        prop_assert!(
            !filter::matches(&all_disabled, &valid_fissure, now),
            "SPEC FLT-013 違反: 一覧表示の全体合致は、残り時間条件を満たし、enabled=trueのルールの少なくとも1本が条件合致する場合に限る。表示選択なし、またはルールなしではフィルタ合致しない (全ルールVIEW OFFなのに表示合致した)"
        );

        let empty = FilterSettings {
            rules: vec![],
            min_remaining_secs: s.min_remaining_secs,
        };
        prop_assert!(
            !filter::matches(&empty, &valid_fissure, now),
            "SPEC FLT-013 違反: 一覧表示の全体合致は、残り時間条件を満たし、enabled=trueのルールの少なくとも1本が条件合致する場合に限る。表示選択なし、またはルールなしではフィルタ合致しない (ルールなしなのに合致した)"
        );
    }

    /// FLT-014: notification projection(通知範囲の射影)はnotify=trueのルールをenabledに依らず元の順序で保持し、照合用にenabled=trueへ正規化して、notify=falseルールを除き、共通のmin_remaining_secsを保持する。表示選択(enabled)の変更やnotify=false draftの追加・削除・条件編集では変わらず、notify切替・通知参加ルールの条件・min_remaining_secsの変更は通知範囲へ反映される。ルール名は表示用メタデータであり射影に含まれない(名前変更は通知範囲を変えず、再seedを起こさない)
    #[test]
    fn flt_014(
        s in arb_settings(),
        mut muted in arb_rule(),
        mut edited_muted in arb_rule(),
        mut notifying in arb_rule(),
    ) {
        let normalize = |rule: &WatchRule| WatchRule {
            enabled: true,
            name: None,
            ..rule.clone()
        };
        let base = filter::notification_projection(&s);
        let expected: Vec<WatchRule> = s.rules.iter()
            .filter(|rule| rule.notify)
            .map(normalize)
            .collect();
        prop_assert_eq!(base.rules.as_slice(), expected.as_slice(), "SPEC FLT-014 違反: notification projection(通知範囲の射影)はnotify=trueのルールをenabledに依らず元の順序で保持し、照合用にenabled=trueへ正規化して、notify=falseルールを除き、共通のmin_remaining_secsを保持する。表示選択(enabled)の変更やnotify=false draftの追加・削除・条件編集では変わらず、notify切替・通知参加ルールの条件・min_remaining_secsの変更は通知範囲へ反映される。ルール名は表示用メタデータであり射影に含まれない(名前変更は通知範囲を変えず、再seedを起こさない) (notify=trueルールと一致しない)");
        prop_assert!(base.rules.iter().all(|rule| rule.enabled && rule.notify), "SPEC FLT-014 違反: notification projection(通知範囲の射影)はnotify=trueのルールをenabledに依らず元の順序で保持し、照合用にenabled=trueへ正規化して、notify=falseルールを除き、共通のmin_remaining_secsを保持する。表示選択(enabled)の変更やnotify=false draftの追加・削除・条件編集では変わらず、notify切替・通知参加ルールの条件・min_remaining_secsの変更は通知範囲へ反映される。ルール名は表示用メタデータであり射影に含まれない(名前変更は通知範囲を変えず、再seedを起こさない) (照合用にenabled=trueへ正規化しない)");
        prop_assert_eq!(base.min_remaining_secs, s.min_remaining_secs, "SPEC FLT-014 違反: notification projection(通知範囲の射影)はnotify=trueのルールをenabledに依らず元の順序で保持し、照合用にenabled=trueへ正規化して、notify=falseルールを除き、共通のmin_remaining_secsを保持する。表示選択(enabled)の変更やnotify=false draftの追加・削除・条件編集では変わらず、notify切替・通知参加ルールの条件・min_remaining_secsの変更は通知範囲へ反映される。ルール名は表示用メタデータであり射影に含まれない(名前変更は通知範囲を変えず、再seedを起こさない) (min_remaining_secsを保持しない)");

        // notify=false draftは表示選択や条件にかかわらず通知射影へ現れない
        muted.notify = false;
        let mut with_muted = s.clone();
        with_muted.rules.push(muted);
        let added = filter::notification_projection(&with_muted);
        prop_assert_eq!(added.rules.as_slice(), base.rules.as_slice(), "SPEC FLT-014 違反: notification projection(通知範囲の射影)はnotify=trueのルールをenabledに依らず元の順序で保持し、照合用にenabled=trueへ正規化して、notify=falseルールを除き、共通のmin_remaining_secsを保持する。表示選択(enabled)の変更やnotify=false draftの追加・削除・条件編集では変わらず、notify切替・通知参加ルールの条件・min_remaining_secsの変更は通知範囲へ反映される。ルール名は表示用メタデータであり射影に含まれない(名前変更は通知範囲を変えず、再seedを起こさない) (notify=false追加で射影が変化した)");

        edited_muted.notify = false;
        *with_muted.rules.last_mut().expect("notify=false ruleを追加済み") = edited_muted;
        let edited = filter::notification_projection(&with_muted);
        prop_assert_eq!(edited.rules.as_slice(), base.rules.as_slice(), "SPEC FLT-014 違反: notification projection(通知範囲の射影)はnotify=trueのルールをenabledに依らず元の順序で保持し、照合用にenabled=trueへ正規化して、notify=falseルールを除き、共通のmin_remaining_secsを保持する。表示選択(enabled)の変更やnotify=false draftの追加・削除・条件編集では変わらず、notify切替・通知参加ルールの条件・min_remaining_secsの変更は通知範囲へ反映される。ルール名は表示用メタデータであり射影に含まれない(名前変更は通知範囲を変えず、再seedを起こさない) (notify=false条件編集で射影が変化した)");
        with_muted.rules.pop();
        let removed = filter::notification_projection(&with_muted);
        prop_assert_eq!(removed.rules.as_slice(), base.rules.as_slice(), "SPEC FLT-014 違反: notification projection(通知範囲の射影)はnotify=trueのルールをenabledに依らず元の順序で保持し、照合用にenabled=trueへ正規化して、notify=falseルールを除き、共通のmin_remaining_secsを保持する。表示選択(enabled)の変更やnotify=false draftの追加・削除・条件編集では変わらず、notify切替・通知参加ルールの条件・min_remaining_secsの変更は通知範囲へ反映される。ルール名は表示用メタデータであり射影に含まれない(名前変更は通知範囲を変えず、再seedを起こさない) (notify=false削除で射影が変化した)");

        // enabledは一覧表示だけ: 全ルールの表示選択を反転しても通知射影・scopeは不変
        let mut display_toggled = s.clone();
        for rule in &mut display_toggled.rules {
            rule.enabled = !rule.enabled;
        }
        prop_assert_eq!(
            filter::notification_projection(&display_toggled),
            base.clone(),
            "SPEC FLT-014 違反: notification projection(通知範囲の射影)はnotify=trueのルールをenabledに依らず元の順序で保持し、照合用にenabled=trueへ正規化して、notify=falseルールを除き、共通のmin_remaining_secsを保持する。表示選択(enabled)の変更やnotify=false draftの追加・削除・条件編集では変わらず、notify切替・通知参加ルールの条件・min_remaining_secsの変更は通知範囲へ反映される。ルール名は表示用メタデータであり射影に含まれない(名前変更は通知範囲を変えず、再seedを起こさない) (enabled変更で通知射影が変化した)"
        );
        prop_assert!(
            !poller::notification_scope_changed(Some(&s), &display_toggled),
            "SPEC FLT-014 違反: notification projection(通知範囲の射影)はnotify=trueのルールをenabledに依らず元の順序で保持し、照合用にenabled=trueへ正規化して、notify=falseルールを除き、共通のmin_remaining_secsを保持する。表示選択(enabled)の変更やnotify=false draftの追加・削除・条件編集では変わらず、notify切替・通知参加ルールの条件・min_remaining_secsの変更は通知範囲へ反映される。ルール名は表示用メタデータであり射影に含まれない(名前変更は通知範囲を変えず、再seedを起こさない) (enabled変更を通知範囲変更と誤判定した)"
        );

        // 非表示(enabled=false)でもnotify=trueなら射影へ入り、enabled=trueへ正規化される
        notifying.enabled = false;
        notifying.notify = true;
        let mut with_notifying = s.clone();
        with_notifying.rules.push(notifying.clone());
        let notifying_added = filter::notification_projection(&with_notifying);
        prop_assert_eq!(notifying_added.rules.len(), base.rules.len() + 1, "SPEC FLT-014 違反: notification projection(通知範囲の射影)はnotify=trueのルールをenabledに依らず元の順序で保持し、照合用にenabled=trueへ正規化して、notify=falseルールを除き、共通のmin_remaining_secsを保持する。表示選択(enabled)の変更やnotify=false draftの追加・削除・条件編集では変わらず、notify切替・通知参加ルールの条件・min_remaining_secsの変更は通知範囲へ反映される。ルール名は表示用メタデータであり射影に含まれない(名前変更は通知範囲を変えず、再seedを起こさない) (非表示通知ルール追加が射影へ反映されない)");
        let normalized = normalize(&notifying);
        prop_assert_eq!(notifying_added.rules.last(), Some(&normalized), "SPEC FLT-014 違反: notification projection(通知範囲の射影)はnotify=trueのルールをenabledに依らず元の順序で保持し、照合用にenabled=trueへ正規化して、notify=falseルールを除き、共通のmin_remaining_secsを保持する。表示選択(enabled)の変更やnotify=false draftの追加・削除・条件編集では変わらず、notify切替・通知参加ルールの条件・min_remaining_secsの変更は通知範囲へ反映される。ルール名は表示用メタデータであり射影に含まれない(名前変更は通知範囲を変えず、再seedを起こさない) (非表示通知ルールの条件を保持しない)");

        // 名前は表示用メタデータ: 変更しても射影も通知範囲判定も変わらない
        let mut renamed = s.clone();
        for rule in &mut renamed.rules {
            rule.name = Some("renamed".to_string());
        }
        prop_assert_eq!(filter::notification_projection(&renamed), base, "SPEC FLT-014 違反: notification projection(通知範囲の射影)はnotify=trueのルールをenabledに依らず元の順序で保持し、照合用にenabled=trueへ正規化して、notify=falseルールを除き、共通のmin_remaining_secsを保持する。表示選択(enabled)の変更やnotify=false draftの追加・削除・条件編集では変わらず、notify切替・通知参加ルールの条件・min_remaining_secsの変更は通知範囲へ反映される。ルール名は表示用メタデータであり射影に含まれない(名前変更は通知範囲を変えず、再seedを起こさない) (名前変更で射影が変化した)");
        prop_assert!(
            !poller::notification_scope_changed(Some(&s), &renamed),
            "SPEC FLT-014 違反: notification projection(通知範囲の射影)はnotify=trueのルールをenabledに依らず元の順序で保持し、照合用にenabled=trueへ正規化して、notify=falseルールを除き、共通のmin_remaining_secsを保持する。表示選択(enabled)の変更やnotify=false draftの追加・削除・条件編集では変わらず、notify切替・通知参加ルールの条件・min_remaining_secsの変更は通知範囲へ反映される。ルール名は表示用メタデータであり射影に含まれない(名前変更は通知範囲を変えず、再seedを起こさない) (名前変更を通知範囲変更と誤判定した)"
        );

        let mut toggled = FilterSettings {
            rules: vec![WatchRule { enabled: false, notify: true, ..WatchRule::default() }],
            min_remaining_secs: s.min_remaining_secs,
        };
        let hidden_projection = filter::notification_projection(&toggled);
        prop_assert_eq!(hidden_projection.rules.len(), 1, "SPEC FLT-014 違反: notification projection(通知範囲の射影)はnotify=trueのルールをenabledに依らず元の順序で保持し、照合用にenabled=trueへ正規化して、notify=falseルールを除き、共通のmin_remaining_secsを保持する。表示選択(enabled)の変更やnotify=false draftの追加・削除・条件編集では変わらず、notify切替・通知参加ルールの条件・min_remaining_secsの変更は通知範囲へ反映される。ルール名は表示用メタデータであり射影に含まれない(名前変更は通知範囲を変えず、再seedを起こさない) (非表示通知ルールを射影から落とした)");
        toggled.rules[0].enabled = true;
        prop_assert_eq!(filter::notification_projection(&toggled), hidden_projection, "SPEC FLT-014 違反: notification projection(通知範囲の射影)はnotify=trueのルールをenabledに依らず元の順序で保持し、照合用にenabled=trueへ正規化して、notify=falseルールを除き、共通のmin_remaining_secsを保持する。表示選択(enabled)の変更やnotify=false draftの追加・削除・条件編集では変わらず、notify切替・通知参加ルールの条件・min_remaining_secsの変更は通知範囲へ反映される。ルール名は表示用メタデータであり射影に含まれない(名前変更は通知範囲を変えず、再seedを起こさない) (enabled切替が射影へ影響した)");
        toggled.rules[0].notify = false;
        prop_assert!(filter::notification_projection(&toggled).rules.is_empty(), "SPEC FLT-014 違反: notification projection(通知範囲の射影)はnotify=trueのルールをenabledに依らず元の順序で保持し、照合用にenabled=trueへ正規化して、notify=falseルールを除き、共通のmin_remaining_secsを保持する。表示選択(enabled)の変更やnotify=false draftの追加・削除・条件編集では変わらず、notify切替・通知参加ルールの条件・min_remaining_secsの変更は通知範囲へ反映される。ルール名は表示用メタデータであり射影に含まれない(名前変更は通知範囲を変えず、再seedを起こさない) (notify=falseを射影へ含めた)");
        toggled.rules[0].notify = true;

        let mut changed_condition = toggled.clone();
        changed_condition.rules[0].tiers = vec!["__projection_changed__".to_string()];
        prop_assert_ne!(
            filter::notification_projection(&toggled).rules,
            filter::notification_projection(&changed_condition).rules,
            "SPEC FLT-014 違反: notification projection(通知範囲の射影)はnotify=trueのルールをenabledに依らず元の順序で保持し、照合用にenabled=trueへ正規化して、notify=falseルールを除き、共通のmin_remaining_secsを保持する。表示選択(enabled)の変更やnotify=false draftの追加・削除・条件編集では変わらず、notify切替・通知参加ルールの条件・min_remaining_secsの変更は通知範囲へ反映される。ルール名は表示用メタデータであり射影に含まれない(名前変更は通知範囲を変えず、再seedを起こさない) (通知参加ルール条件の変更が射影へ反映されない)"
        );

        let changed_min = FilterSettings {
            rules: s.rules.clone(),
            min_remaining_secs: s.min_remaining_secs + 1,
        };
        prop_assert_ne!(
            filter::notification_projection(&s).min_remaining_secs,
            filter::notification_projection(&changed_min).min_remaining_secs,
            "SPEC FLT-014 違反: notification projection(通知範囲の射影)はnotify=trueのルールをenabledに依らず元の順序で保持し、照合用にenabled=trueへ正規化して、notify=falseルールを除き、共通のmin_remaining_secsを保持する。表示選択(enabled)の変更やnotify=false draftの追加・削除・条件編集では変わらず、notify切替・通知参加ルールの条件・min_remaining_secsの変更は通知範囲へ反映される。ルール名は表示用メタデータであり射影に含まれない(名前変更は通知範囲を変えず、再seedを起こさない) (min_remaining_secs変更が射影へ反映されない)"
        );
    }

    /// DED-001: 同一亀裂idは任意のポーリング列で高々1回しか通知されない
    #[test]
    fn ded_001(ids in proptest::collection::vec("[a-c][0-9]", 0..60)) {
        let far = base_now() + Duration::hours(2);
        let mut set = NotifiedSet::new();
        let mut times_notified: HashMap<String, usize> = HashMap::new();
        for id in &ids {
            if set.mark(id, far) {
                *times_notified.entry(id.clone()).or_default() += 1;
            }
        }
        prop_assert!(times_notified.values().all(|&c| c <= 1), "SPEC DED-001 違反: 同一亀裂idは任意のポーリング列で高々1回しか通知されない");
    }

    /// DED-002: pruneは生存中idの通知済み状態を保持し、期限切れidを除去する
    #[test]
    fn ded_002(n_live in 0usize..20, n_dead in 0usize..20) {
        let now = base_now();
        let mut set = NotifiedSet::new();
        for i in 0..n_live { set.mark(&format!("L{i}"), now + Duration::hours(1)); }
        for i in 0..n_dead { set.mark(&format!("D{i}"), now - Duration::hours(1)); }
        set.prune(now);
        for i in 0..n_live {
            prop_assert!(set.contains(&format!("L{i}")), "SPEC DED-002 違反: pruneは生存中idの通知済み状態を保持し、期限切れidを除去する (生存idが消えた)");
        }
        for i in 0..n_dead {
            prop_assert!(!set.contains(&format!("D{i}")), "SPEC DED-002 違反: pruneは生存中idの通知済み状態を保持し、期限切れidを除去する (期限切れidが残った)");
        }
    }

    /// DED-003: 同じ亀裂へ複数の表示ルールまたは通知ルールが合致しても、一覧・通知候補では亀裂id単位の1件として扱い、同一亀裂は高々1回しか通知されない
    #[test]
    fn ded_003(mut f in arb_fissure()) {
        let now = base_now();
        f.expiry = now + Duration::hours(1);
        f.is_storm = false;
        let rule = WatchRule::default();
        let settings = FilterSettings {
            rules: vec![rule.clone(), rule],
            min_remaining_secs: 0,
        };
        let visible = poller::notify_candidates(&settings, &[f.clone()], now);
        prop_assert_eq!(visible.len(), 1, "SPEC DED-003 違反: 同じ亀裂へ複数の表示ルールまたは通知ルールが合致しても、一覧・通知候補では亀裂id単位の1件として扱い、同一亀裂は高々1回しか通知されない (複数ルール合致で一覧が重複した)");

        let mut notified = NotifiedSet::new();
        let first = poller::select_notifications(&mut notified, visible.clone(), false);
        prop_assert_eq!(first.len(), 1, "SPEC DED-003 違反: 同じ亀裂へ複数の表示ルールまたは通知ルールが合致しても、一覧・通知候補では亀裂id単位の1件として扱い、同一亀裂は高々1回しか通知されない (最初の通知候補が1件でない)");
        prop_assert_eq!(first[0].id.as_str(), f.id.as_str(), "SPEC DED-003 違反: 同じ亀裂へ複数の表示ルールまたは通知ルールが合致しても、一覧・通知候補では亀裂id単位の1件として扱い、同一亀裂は高々1回しか通知されない (別idを通知した)");
        let second = poller::select_notifications(&mut notified, visible, false);
        prop_assert!(second.is_empty(), "SPEC DED-003 違反: 同じ亀裂へ複数の表示ルールまたは通知ルールが合致しても、一覧・通知候補では亀裂id単位の1件として扱い、同一亀裂は高々1回しか通知されない (同じidを再通知した)");
    }

    /// PRS-001: 惑星抽出は任意文字列でパニックせず、"Node (Planet)" 形式でPlanetを返す (全入力でパニックしない)
    #[test]
    fn prs_001_total(s in ".*") {
        let _ = filter::extract_planet(&s);
    }

    /// PRS-001: 惑星抽出は任意文字列でパニックせず、"Node (Planet)" 形式でPlanetを返す (整形式で括弧内を返す)
    #[test]
    fn prs_001_wellformed(name in "[A-Za-z][A-Za-z ]{0,14}", planet in "[A-Za-z][A-Za-z ]{0,14}") {
        let planet = planet.trim().to_string();
        prop_assume!(!planet.is_empty());
        let node = format!("{} ({})", name.trim(), planet);
        prop_assert_eq!(filter::extract_planet(&node), Some(planet), "SPEC PRS-001 違反: 惑星抽出は任意文字列でパニックせず、\"Node (Planet)\" 形式でPlanetを返す");
    }

    /// POL-001: APIバックオフの遅延は失敗・成功がどう並んでも常に[60s, 600s]に収まる
    #[test]
    fn pol_001(ops in proptest::collection::vec(any::<bool>(), 0..100)) {
        let mut b = Backoff::new(60, 600);
        for fail in ops {
            let v = if fail { b.on_failure() } else { b.on_success() };
            prop_assert!((60..=600).contains(&v), "SPEC POL-001 違反: APIバックオフの遅延は失敗・成功がどう並んでも常に[60s, 600s]に収まる (v={})", v);
        }
    }

    /// POL-002: 起動直後の初回ポーリングはシードのみ: 既存の合致亀裂を通知済みとして記録するが、通知は1件も発火しない(起動時の通知洪水を防ぐ)
    #[test]
    fn pol_002(fs in proptest::collection::vec(arb_fissure(), 0..30)) {
        let mut set = NotifiedSet::new();
        let out = poller::select_notifications(&mut set, fs.clone(), true);
        prop_assert!(out.is_empty(), "SPEC POL-002 違反: 起動直後の初回ポーリングはシードのみ: 既存の合致亀裂を通知済みとして記録するが、通知は1件も発火しない(起動時の通知洪水を防ぐ) (通知が発火した)");
        for f in &fs {
            prop_assert!(set.contains(&f.id), "SPEC POL-002 違反: 起動直後の初回ポーリングはシードのみ: 既存の合致亀裂を通知済みとして記録するが、通知は1件も発火しない(起動時の通知洪水を防ぐ) (シードされていないidがある)");
        }
    }

    /// POL-003: 初回評価とnotification projectionが変わった設定変更だけを通知範囲変更とし、変更時点で現存する合致亀裂はsilent seedして一括通知しない。その後に現れた新規idは1回だけ通知候補となる。表示選択(enabled)だけの変更、notify=false draftだけの追加・削除・条件編集、配送設定だけの変更では再seedしない (射影による変更判定)
    #[test]
    fn pol_003_projection(
        previous in arb_settings(),
        current in arb_settings(),
        mut muted in arb_rule(),
    ) {
        let previous_projection = filter::notification_projection(&previous);
        let current_projection = filter::notification_projection(&current);
        let expected = previous_projection.min_remaining_secs != current_projection.min_remaining_secs
            || previous_projection.rules != current_projection.rules;
        prop_assert_eq!(
            poller::notification_scope_changed(Some(&previous), &current),
            expected,
            "SPEC POL-003 違反: 初回評価とnotification projectionが変わった設定変更だけを通知範囲変更とし、変更時点で現存する合致亀裂はsilent seedして一括通知しない。その後に現れた新規idは1回だけ通知候補となる。表示選択(enabled)だけの変更、notify=false draftだけの追加・削除・条件編集、配送設定だけの変更では再seedしない (notification projectionとの差分と一致しない)"
        );
        prop_assert!(
            poller::notification_scope_changed(None, &current),
            "SPEC POL-003 違反: 初回評価とnotification projectionが変わった設定変更だけを通知範囲変更とし、変更時点で現存する合致亀裂はsilent seedして一括通知しない。その後に現れた新規idは1回だけ通知候補となる。表示選択(enabled)だけの変更、notify=false draftだけの追加・削除・条件編集、配送設定だけの変更では再seedしない (初回評価をscope changeと判定しない)"
        );

        // notify=false draftの追加・編集はscope changeではない
        muted.notify = false;
        let mut muted_only_change = previous.clone();
        muted_only_change.rules.push(muted);
        prop_assert!(
            !poller::notification_scope_changed(Some(&previous), &muted_only_change),
            "SPEC POL-003 違反: 初回評価とnotification projectionが変わった設定変更だけを通知範囲変更とし、変更時点で現存する合致亀裂はsilent seedして一括通知しない。その後に現れた新規idは1回だけ通知候補となる。表示選択(enabled)だけの変更、notify=false draftだけの追加・削除・条件編集、配送設定だけの変更では再seedしない (notify=false draft追加をscope changeと誤判定した)"
        );

        // enabledは表示選択だけなので任意に変えてもscope changeではない
        let mut display_only_change = previous.clone();
        for rule in &mut display_only_change.rules {
            rule.enabled = !rule.enabled;
        }
        prop_assert!(
            !poller::notification_scope_changed(Some(&previous), &display_only_change),
            "SPEC POL-003 違反: 初回評価とnotification projectionが変わった設定変更だけを通知範囲変更とし、変更時点で現存する合致亀裂はsilent seedして一括通知しない。その後に現れた新規idは1回だけ通知候補となる。表示選択(enabled)だけの変更、notify=false draftだけの追加・削除・条件編集、配送設定だけの変更では再seedしない (enabled変更をscope changeと誤判定した)"
        );
    }

    /// POL-003: 初回評価とnotification projectionが変わった設定変更だけを通知範囲変更とし、変更時点で現存する合致亀裂はsilent seedして一括通知しない。その後に現れた新規idは1回だけ通知候補となる。表示選択(enabled)だけの変更、notify=false draftだけの追加・削除・条件編集、配送設定だけの変更では再seedしない (scope change時のsilent seed)
    #[test]
    fn pol_003_silent_seed(mut f in arb_fissure()) {
        let now = base_now();
        f.expiry = now + Duration::hours(1);
        f.is_storm = false;

        let mut hidden_notify_rule = WatchRule::default();
        hidden_notify_rule.enabled = false;
        hidden_notify_rule.notify = true;
        let mut muted_rule = hidden_notify_rule.clone();
        muted_rule.notify = false;
        let previous = FilterSettings {
            rules: vec![muted_rule],
            min_remaining_secs: 0,
        };
        let current = FilterSettings {
            rules: vec![hidden_notify_rule],
            min_remaining_secs: 0,
        };
        prop_assert!(
            poller::notification_scope_changed(Some(&previous), &current),
            "SPEC POL-003 違反: 初回評価とnotification projectionが変わった設定変更だけを通知範囲変更とし、変更時点で現存する合致亀裂はsilent seedして一括通知しない。その後に現れた新規idは1回だけ通知候補となる。表示選択(enabled)だけの変更、notify=false draftだけの追加・削除・条件編集、配送設定だけの変更では再seedしない (notify有効化をscope changeと判定しない)"
        );

        let existing = poller::notify_candidates(&current, &[f.clone()], now);
        prop_assert_eq!(existing.len(), 1, "SPEC POL-003 違反: 初回評価とnotification projectionが変わった設定変更だけを通知範囲変更とし、変更時点で現存する合致亀裂はsilent seedして一括通知しない。その後に現れた新規idは1回だけ通知候補となる。表示選択(enabled)だけの変更、notify=false draftだけの追加・削除・条件編集、配送設定だけの変更では再seedしない (現存合致亀裂を取得できない)");
        let mut notified = NotifiedSet::new();
        let seeded = poller::select_notifications(&mut notified, existing.clone(), true);
        prop_assert!(seeded.is_empty(), "SPEC POL-003 違反: 初回評価とnotification projectionが変わった設定変更だけを通知範囲変更とし、変更時点で現存する合致亀裂はsilent seedして一括通知しない。その後に現れた新規idは1回だけ通知候補となる。表示選択(enabled)だけの変更、notify=false draftだけの追加・削除・条件編集、配送設定だけの変更では再seedしない (scope change直後の現存亀裂を一括通知した)");
        prop_assert!(notified.contains(&f.id), "SPEC POL-003 違反: 初回評価とnotification projectionが変わった設定変更だけを通知範囲変更とし、変更時点で現存する合致亀裂はsilent seedして一括通知しない。その後に現れた新規idは1回だけ通知候補となる。表示選択(enabled)だけの変更、notify=false draftだけの追加・削除・条件編集、配送設定だけの変更では再seedしない (現存亀裂をsilent seedしていない)");
        let repeated = poller::select_notifications(&mut notified, existing, false);
        prop_assert!(repeated.is_empty(), "SPEC POL-003 違反: 初回評価とnotification projectionが変わった設定変更だけを通知範囲変更とし、変更時点で現存する合致亀裂はsilent seedして一括通知しない。その後に現れた新規idは1回だけ通知候補となる。表示選択(enabled)だけの変更、notify=false draftだけの追加・削除・条件編集、配送設定だけの変更では再seedしない (seed済み現存亀裂を次回通知した)");

        let mut new_fissure = f.clone();
        new_fissure.id = format!("{}-new", f.id);
        let newly_visible = poller::notify_candidates(&current, &[new_fissure.clone()], now);
        let fresh = poller::select_notifications(&mut notified, newly_visible.clone(), false);
        prop_assert_eq!(fresh.len(), 1, "SPEC POL-003 違反: 初回評価とnotification projectionが変わった設定変更だけを通知範囲変更とし、変更時点で現存する合致亀裂はsilent seedして一括通知しない。その後に現れた新規idは1回だけ通知候補となる。表示選択(enabled)だけの変更、notify=false draftだけの追加・削除・条件編集、配送設定だけの変更では再seedしない (scope change後の新規idを通知候補にしない)");
        prop_assert_eq!(fresh[0].id.as_str(), new_fissure.id.as_str(), "SPEC POL-003 違反: 初回評価とnotification projectionが変わった設定変更だけを通知範囲変更とし、変更時点で現存する合致亀裂はsilent seedして一括通知しない。その後に現れた新規idは1回だけ通知候補となる。表示選択(enabled)だけの変更、notify=false draftだけの追加・削除・条件編集、配送設定だけの変更では再seedしない (新規idを保持しない)");
        let duplicate = poller::select_notifications(&mut notified, newly_visible, false);
        prop_assert!(duplicate.is_empty(), "SPEC POL-003 違反: 初回評価とnotification projectionが変わった設定変更だけを通知範囲変更とし、変更時点で現存する合致亀裂はsilent seedして一括通知しない。その後に現れた新規idは1回だけ通知候補となる。表示選択(enabled)だけの変更、notify=false draftだけの追加・削除・条件編集、配送設定だけの変更では再seedしない (scope change後の新規idを再通知した)");
    }

    /// NTY-001: 通知候補はnotify=trueのルールのORに合致する亀裂のみで、それらを1件も取りこぼさない。enabled=falseの非表示ルールも通知へ参加し、通知候補は一覧表示の部分集合に限定されない
    #[test]
    fn nty_001(
        s in arb_settings(),
        fs in proptest::collection::vec(arb_fissure(), 0..30),
        mut hidden_fissure in arb_fissure(),
    ) {
        let now = base_now();
        let candidates = poller::notify_candidates(&s, &fs, now);
        let scope = filter::notification_projection(&s);
        // 健全性: 候補はnotify=trueルールのORに合致する
        for f in &candidates {
            prop_assert!(filter::matches(&scope, f, now), "SPEC NTY-001 違反: 通知候補はnotify=trueのルールのORに合致する亀裂のみで、それらを1件も取りこぼさない。enabled=falseの非表示ルールも通知へ参加し、通知候補は一覧表示の部分集合に限定されない (通知対象外が候補になった)");
        }
        // 完全性: 通知参加ルールに合致する亀裂は1件も取りこぼさない
        for f in fs.iter().filter(|f| filter::matches(&scope, f, now)) {
            prop_assert!(candidates.iter().any(|c| c.id == f.id), "SPEC NTY-001 違反: 通知候補はnotify=trueのルールのORに合致する亀裂のみで、それらを1件も取りこぼさない。enabled=falseの非表示ルールも通知へ参加し、通知候補は一覧表示の部分集合に限定されない (通知候補の取りこぼし)");
        }
        // 明示反例: 非表示(enabled=false)通知ルールだけに合致する亀裂も通知し、一覧には出さない
        hidden_fissure.expiry = now + Duration::hours(1);
        let hidden_notify = WatchRule {
            enabled: false,
            notify: true,
            mode: Mode::Both,
            storms: StormMode::Include,
            ..WatchRule::default()
        };
        let displayed_nonmatch = WatchRule {
            enabled: true,
            notify: false,
            tiers: vec!["__never_matches__".to_string()],
            mode: Mode::Both,
            storms: StormMode::Include,
            ..WatchRule::default()
        };
        let separated = FilterSettings {
            rules: vec![displayed_nonmatch, hidden_notify],
            min_remaining_secs: 0,
        };
        let hidden_candidates = poller::notify_candidates(&separated, &[hidden_fissure.clone()], now);
        let visible = poller::visible_fissures(&separated, &[hidden_fissure.clone()], now);
        prop_assert_eq!(hidden_candidates.len(), 1, "SPEC NTY-001 違反: 通知候補はnotify=trueのルールのORに合致する亀裂のみで、それらを1件も取りこぼさない。enabled=falseの非表示ルールも通知へ参加し、通知候補は一覧表示の部分集合に限定されない (非表示通知ルールの合致を候補にしない)");
        prop_assert_eq!(hidden_candidates[0].id.as_str(), hidden_fissure.id.as_str(), "SPEC NTY-001 違反: 通知候補はnotify=trueのルールのORに合致する亀裂のみで、それらを1件も取りこぼさない。enabled=falseの非表示ルールも通知へ参加し、通知候補は一覧表示の部分集合に限定されない (非表示通知ルールで別idを選んだ)");
        prop_assert!(visible.is_empty(), "SPEC NTY-001 違反: 通知候補はnotify=trueのルールのORに合致する亀裂のみで、それらを1件も取りこぼさない。enabled=falseの非表示ルールも通知へ参加し、通知候補は一覧表示の部分集合に限定されない (通知ルールを一覧表示へ混入した)");
    }

    /// VIS-001: 表示選択(enabled=true)ルールがあるとき、一覧に表示されるのはいずれかの表示ルールに合致する生存中(expiry > now)の亀裂のみで、合致する亀裂は1件も取りこぼさない。表示選択が1本もない(無指定)ときはmin_remaining_secsにかかわらず生存中の全亀裂を表示し、期限切れは表示しない。どちらの場合も通知参加はnotifyだけで独立に決まる
    #[test]
    fn vis_001(s in arb_settings(), fs in proptest::collection::vec(arb_fissure(), 0..30)) {
        let now = base_now();
        let visible = poller::visible_fissures(&s, &fs, now);
        // notifyは表示判定へ影響しない
        let mut notify_toggled = s.clone();
        for rule in &mut notify_toggled.rules {
            rule.notify = !rule.notify;
        }
        prop_assert_eq!(
            poller::visible_fissures(&notify_toggled, &fs, now),
            visible.clone(),
            "SPEC VIS-001 違反: 表示選択(enabled=true)ルールがあるとき、一覧に表示されるのはいずれかの表示ルールに合致する生存中(expiry > now)の亀裂のみで、合致する亀裂は1件も取りこぼさない。表示選択が1本もない(無指定)ときはmin_remaining_secsにかかわらず生存中の全亀裂を表示し、期限切れは表示しない。どちらの場合も通知参加はnotifyだけで独立に決まる (notify変更で一覧表示が変化した)"
        );
        if s.rules.iter().any(|rule| rule.enabled) {
            for f in &visible {
                prop_assert!(filter::matches(&s, f, now), "SPEC VIS-001 違反: 表示選択(enabled=true)ルールがあるとき、一覧に表示されるのはいずれかの表示ルールに合致する生存中(expiry > now)の亀裂のみで、合致する亀裂は1件も取りこぼさない。表示選択が1本もない(無指定)ときはmin_remaining_secsにかかわらず生存中の全亀裂を表示し、期限切れは表示しない。どちらの場合も通知参加はnotifyだけで独立に決まる (対象外が表示された)");
            }
            for f in fs.iter().filter(|f| filter::matches(&s, f, now)) {
                prop_assert!(visible.iter().any(|v| v.id == f.id), "SPEC VIS-001 違反: 表示選択(enabled=true)ルールがあるとき、一覧に表示されるのはいずれかの表示ルールに合致する生存中(expiry > now)の亀裂のみで、合致する亀裂は1件も取りこぼさない。表示選択が1本もない(無指定)ときはmin_remaining_secsにかかわらず生存中の全亀裂を表示し、期限切れは表示しない。どちらの場合も通知参加はnotifyだけで独立に決まる (合致亀裂が欠落した)");
            }
        } else {
            // 無指定(表示選択なし): 通知参加・min_remainingとは独立に生存中だけ全件表示する
            let live: Vec<&Fissure> = fs.iter().filter(|f| f.expiry > now).collect();
            prop_assert_eq!(visible.len(), live.len(), "SPEC VIS-001 違反: 表示選択(enabled=true)ルールがあるとき、一覧に表示されるのはいずれかの表示ルールに合致する生存中(expiry > now)の亀裂のみで、合致する亀裂は1件も取りこぼさない。表示選択が1本もない(無指定)ときはmin_remaining_secsにかかわらず生存中の全亀裂を表示し、期限切れは表示しない。どちらの場合も通知参加はnotifyだけで独立に決まる (無指定の生存中全件と一致しない)");
            for f in live {
                prop_assert!(visible.iter().any(|v| v.id == f.id), "SPEC VIS-001 違反: 表示選択(enabled=true)ルールがあるとき、一覧に表示されるのはいずれかの表示ルールに合致する生存中(expiry > now)の亀裂のみで、合致する亀裂は1件も取りこぼさない。表示選択が1本もない(無指定)ときはmin_remaining_secsにかかわらず生存中の全亀裂を表示し、期限切れは表示しない。どちらの場合も通知参加はnotifyだけで独立に決まる (無指定で生存中亀裂が欠落した)");
            }
            for f in fs.iter().filter(|f| f.expiry <= now) {
                prop_assert!(!visible.iter().any(|v| v.id == f.id), "SPEC VIS-001 違反: 表示選択(enabled=true)ルールがあるとき、一覧に表示されるのはいずれかの表示ルールに合致する生存中(expiry > now)の亀裂のみで、合致する亀裂は1件も取りこぼさない。表示選択が1本もない(無指定)ときはmin_remaining_secsにかかわらず生存中の全亀裂を表示し、期限切れは表示しない。どちらの場合も通知参加はnotifyだけで独立に決まる (無指定で期限切れを表示した)");
            }
        }
    }

    /// FZY-001: パレットのファジーマッチが成立するのは、クエリ文字が候補文字列(またはalias)に順序どおり現れる場合に限る(健全性)
    #[test]
    fn fzy_001(q in ".{0,12}", text in ".{0,24}") {
        if let Some((_score, idx)) = palette::fuzzy_score(&q, &text) {
            let tc: Vec<char> = text.chars().collect();
            let qc: Vec<char> = q.chars().collect();
            prop_assert_eq!(idx.len(), qc.len(), "SPEC FZY-001 違反: パレットのファジーマッチが成立するのは、クエリ文字が候補文字列(またはalias)に順序どおり現れる場合に限る(健全性)");
            for w in idx.windows(2) {
                prop_assert!(w[0] < w[1], "SPEC FZY-001 違反: パレットのファジーマッチが成立するのは、クエリ文字が候補文字列(またはalias)に順序どおり現れる場合に限る(健全性) (順序が保存されていない)");
            }
            for (k, &i) in idx.iter().enumerate() {
                let a = tc[i];
                let b = qc[k];
                prop_assert!(a == b || a.to_lowercase().eq(b.to_lowercase()), "SPEC FZY-001 違反: パレットのファジーマッチが成立するのは、クエリ文字が候補文字列(またはalias)に順序どおり現れる場合に限る(健全性) (文字不一致)");
            }
        }
    }

    /// FZY-002: 空クエリはパレット候補の全件を返す(完全性)
    #[test]
    fn fzy_002(labels in proptest::collection::vec("[A-Za-z ]{1,12}", 0..20)) {
        let catalog = mk_catalog(labels);
        prop_assert_eq!(palette::query_catalog(&catalog, "").len(), catalog.len(), "SPEC FZY-002 違反: 空クエリはパレット候補の全件を返す(完全性)");
    }

    /// FZY-003: クエリと完全一致する候補(label/alias)が存在すれば、先頭候補は完全一致である
    #[test]
    fn fzy_003(labels in proptest::collection::vec("[a-z]{1,8}", 1..15), pick in any::<prop::sample::Index>()) {
        let q = labels[pick.index(labels.len())].clone();
        let catalog = mk_catalog(labels);
        let res = palette::query_catalog(&catalog, &q);
        prop_assert!(!res.is_empty(), "SPEC FZY-003 違反: クエリと完全一致する候補(label/alias)が存在すれば、先頭候補は完全一致である (結果が空)");
        let top = &catalog[res[0].idx];
        let exact = top.label.eq_ignore_ascii_case(&q)
            || top.aliases.iter().any(|a| a.eq_ignore_ascii_case(&q));
        prop_assert!(exact, "SPEC FZY-003 違反: クエリと完全一致する候補(label/alias)が存在すれば、先頭候補は完全一致である (先頭が完全一致でない: {})", top.label);
    }

    /// FZY-004: 同一クエリ・同一候補集合に対するパレットの結果順序は決定的
    #[test]
    fn fzy_004(labels in proptest::collection::vec("[A-Za-z ]{1,10}", 0..15), q in "[a-z]{0,6}") {
        let catalog = mk_catalog(labels);
        let a: Vec<usize> = palette::query_catalog(&catalog, &q).into_iter().map(|r| r.idx).collect();
        let b: Vec<usize> = palette::query_catalog(&catalog, &q).into_iter().map(|r| r.idx).collect();
        prop_assert_eq!(a, b, "SPEC FZY-004 違反: 同一クエリ・同一候補集合に対するパレットの結果順序は決定的");
    }

    /// SAT-001: パレット操作列をどう並べても、適用後のすべてのルールはドメイン互換表(Requiem↔クバ要塞、Omnia↔ザリマン、VOID嵐↔Proxima星系等)に関して充足可能。ルール内で両立しない選択は新しい方を残して上書き解決される
    #[test]
    fn sat_001(ops in proptest::collection::vec(any::<prop::sample::Index>(), 0..40)) {
        let catalog = palette::filter_catalog();
        let mut state = palette::EditorState::default();
        for op in ops {
            let cand = &catalog[op.index(catalog.len())];
            palette::apply(&mut state, cand);
            for rule in &state.rules {
                prop_assert!(
                    palette::satisfiable(rule),
                    "SPEC SAT-001 違反: パレット操作列をどう並べても、適用後のすべてのルールはドメイン互換表(Requiem↔クバ要塞、Omnia↔ザリマン、VOID嵐↔Proxima星系等)に関して充足可能。ルール内で両立しない選択は新しい方を残して上書き解決される ({} 適用後に充足不能: {:?})", cand.id, rule
                );
            }
        }
    }

    /// EDT-001: edit focus・一覧表示選択(enabled)・通知参加(notify)は独立する。enabled切替は条件・notify・edit indexを変えず、notify切替も条件・enabled・edit indexを変えず、edit index変更はrulesを変えない。別にVIEW選択ルールがある状態で非表示ルールへfilter候補を適用してもenabled/notifyを暗黙に変えない (enabled切替)
    #[test]
    fn edt_001_set_enabled(
        rules in proptest::collection::vec(arb_rule(), 1..5),
        edit_pick in any::<prop::sample::Index>(),
        target_pick in any::<prop::sample::Index>(),
        enabled in any::<bool>(),
    ) {
        let active = edit_pick.index(rules.len());
        let target = target_pick.index(rules.len());
        let mut expected_rules = rules.clone();
        expected_rules[target].enabled = enabled;
        let mut state = palette::EditorState { rules, active };
        let before_active = state.active;
        prop_assert!(
            palette::set_rule_enabled(&mut state, target, enabled),
            "SPEC EDT-001 違反: edit focus・一覧表示選択(enabled)・通知参加(notify)は独立する。enabled切替は条件・notify・edit indexを変えず、notify切替も条件・enabled・edit indexを変えず、edit index変更はrulesを変えない。別にVIEW選択ルールがある状態で非表示ルールへfilter候補を適用してもenabled/notifyを暗黙に変えない (有効なindexの切替に失敗した)"
        );
        prop_assert_eq!(state.active, before_active, "SPEC EDT-001 違反: edit focus・一覧表示選択(enabled)・通知参加(notify)は独立する。enabled切替は条件・notify・edit indexを変えず、notify切替も条件・enabled・edit indexを変えず、edit index変更はrulesを変えない。別にVIEW選択ルールがある状態で非表示ルールへfilter候補を適用してもenabled/notifyを暗黙に変えない (enabled切替でedit indexが変化した)");
        prop_assert_eq!(state.rules.as_slice(), expected_rules.as_slice(), "SPEC EDT-001 違反: edit focus・一覧表示選択(enabled)・通知参加(notify)は独立する。enabled切替は条件・notify・edit indexを変えず、notify切替も条件・enabled・edit indexを変えず、edit index変更はrulesを変えない。別にVIEW選択ルールがある状態で非表示ルールへfilter候補を適用してもenabled/notifyを暗黙に変えない (enabled以外の条件が変化した)");

        let before_invalid = state.clone();
        let invalid_index = state.rules.len();
        prop_assert!(
            !palette::set_rule_enabled(&mut state, invalid_index, enabled),
            "SPEC EDT-001 違反: edit focus・一覧表示選択(enabled)・通知参加(notify)は独立する。enabled切替は条件・notify・edit indexを変えず、notify切替も条件・enabled・edit indexを変えず、edit index変更はrulesを変えない。別にVIEW選択ルールがある状態で非表示ルールへfilter候補を適用してもenabled/notifyを暗黙に変えない (範囲外indexを成功扱いした)"
        );
        prop_assert_eq!(state, before_invalid, "SPEC EDT-001 違反: edit focus・一覧表示選択(enabled)・通知参加(notify)は独立する。enabled切替は条件・notify・edit indexを変えず、notify切替も条件・enabled・edit indexを変えず、edit index変更はrulesを変えない。別にVIEW選択ルールがある状態で非表示ルールへfilter候補を適用してもenabled/notifyを暗黙に変えない (範囲外indexでstateを変更した)");
    }

    /// EDT-001: edit focus・一覧表示選択(enabled)・通知参加(notify)は独立する。enabled切替は条件・notify・edit indexを変えず、notify切替も条件・enabled・edit indexを変えず、edit index変更はrulesを変えない。別にVIEW選択ルールがある状態で非表示ルールへfilter候補を適用してもenabled/notifyを暗黙に変えない (notify切替)
    #[test]
    fn edt_001_set_notify(
        rules in proptest::collection::vec(arb_rule(), 1..5),
        edit_pick in any::<prop::sample::Index>(),
        target_pick in any::<prop::sample::Index>(),
        notify in any::<bool>(),
    ) {
        let active = edit_pick.index(rules.len());
        let target = target_pick.index(rules.len());
        let mut expected_rules = rules.clone();
        expected_rules[target].notify = notify;
        let mut state = palette::EditorState { rules, active };
        let before_active = state.active;
        prop_assert!(
            palette::set_rule_notify(&mut state, target, notify),
            "SPEC EDT-001 違反: edit focus・一覧表示選択(enabled)・通知参加(notify)は独立する。enabled切替は条件・notify・edit indexを変えず、notify切替も条件・enabled・edit indexを変えず、edit index変更はrulesを変えない。別にVIEW選択ルールがある状態で非表示ルールへfilter候補を適用してもenabled/notifyを暗黙に変えない (有効なindexのnotify切替に失敗した)"
        );
        prop_assert_eq!(state.active, before_active, "SPEC EDT-001 違反: edit focus・一覧表示選択(enabled)・通知参加(notify)は独立する。enabled切替は条件・notify・edit indexを変えず、notify切替も条件・enabled・edit indexを変えず、edit index変更はrulesを変えない。別にVIEW選択ルールがある状態で非表示ルールへfilter候補を適用してもenabled/notifyを暗黙に変えない (notify切替でedit indexが変化した)");
        prop_assert_eq!(state.rules.as_slice(), expected_rules.as_slice(), "SPEC EDT-001 違反: edit focus・一覧表示選択(enabled)・通知参加(notify)は独立する。enabled切替は条件・notify・edit indexを変えず、notify切替も条件・enabled・edit indexを変えず、edit index変更はrulesを変えない。別にVIEW選択ルールがある状態で非表示ルールへfilter候補を適用してもenabled/notifyを暗黙に変えない (notify以外が変化した)");

        let before_invalid = state.clone();
        let invalid_index = state.rules.len();
        prop_assert!(
            !palette::set_rule_notify(&mut state, invalid_index, notify),
            "SPEC EDT-001 違反: edit focus・一覧表示選択(enabled)・通知参加(notify)は独立する。enabled切替は条件・notify・edit indexを変えず、notify切替も条件・enabled・edit indexを変えず、edit index変更はrulesを変えない。別にVIEW選択ルールがある状態で非表示ルールへfilter候補を適用してもenabled/notifyを暗黙に変えない (範囲外indexのnotify切替を成功扱いした)"
        );
        prop_assert_eq!(state, before_invalid, "SPEC EDT-001 違反: edit focus・一覧表示選択(enabled)・通知参加(notify)は独立する。enabled切替は条件・notify・edit indexを変えず、notify切替も条件・enabled・edit indexを変えず、edit index変更はrulesを変えない。別にVIEW選択ルールがある状態で非表示ルールへfilter候補を適用してもenabled/notifyを暗黙に変えない (範囲外indexでstateを変更した)");
    }

    /// EDT-001: edit focus・一覧表示選択(enabled)・通知参加(notify)は独立する。enabled切替は条件・notify・edit indexを変えず、notify切替も条件・enabled・edit indexを変えず、edit index変更はrulesを変えない。別にVIEW選択ルールがある状態で非表示ルールへfilter候補を適用してもenabled/notifyを暗黙に変えない (edit focus変更)
    #[test]
    fn edt_001_edit_focus(
        rules in proptest::collection::vec(arb_rule(), 1..5),
        pick in any::<prop::sample::Index>(),
    ) {
        let before = rules.clone();
        let mut state = palette::EditorState { rules, active: 0 };
        state.active = pick.index(state.rules.len());
        prop_assert_eq!(state.rules.as_slice(), before.as_slice(), "SPEC EDT-001 違反: edit focus・一覧表示選択(enabled)・通知参加(notify)は独立する。enabled切替は条件・notify・edit indexを変えず、notify切替も条件・enabled・edit indexを変えず、edit index変更はrulesを変えない。別にVIEW選択ルールがある状態で非表示ルールへfilter候補を適用してもenabled/notifyを暗黙に変えない (edit index変更でrulesが変化した)");
    }

    /// EDT-001: edit focus・一覧表示選択(enabled)・通知参加(notify)は独立する。enabled切替は条件・notify・edit indexを変えず、notify切替も条件・enabled・edit indexを変えず、edit index変更はrulesを変えない。別にVIEW選択ルールがある状態で非表示ルールへfilter候補を適用してもenabled/notifyを暗黙に変えない (非表示・通知OFF draftの条件編集)
    #[test]
    fn edt_001_disabled_edit(
        mut rule in arb_rule(),
        mut guard in arb_rule(),
        ops in proptest::collection::vec(any::<prop::sample::Index>(), 0..40),
    ) {
        rule.enabled = false;
        rule.notify = false;
        guard.enabled = true;
        guard.notify = true;
        let expected_projection = vec![WatchRule { name: None, ..guard.clone() }];
        let mut state = palette::EditorState { rules: vec![rule, guard], active: 0 };
        let candidates: Vec<Candidate> = palette::catalog()
            .into_iter()
            .filter(|candidate| candidate.facet != Facet::Action)
            .collect();
        for op in ops {
            let candidate = &candidates[op.index(candidates.len())];
            palette::apply(&mut state, candidate);
            prop_assert_eq!(state.rules.len(), 2, "SPEC EDT-001 違反: edit focus・一覧表示選択(enabled)・通知参加(notify)は独立する。enabled切替は条件・notify・edit indexを変えず、notify切替も条件・enabled・edit indexを変えず、edit index変更はrulesを変えない。別にVIEW選択ルールがある状態で非表示ルールへfilter候補を適用してもenabled/notifyを暗黙に変えない ({} 適用でルール数が変わった)", candidate.id);
            prop_assert!(!state.rules[0].enabled, "SPEC EDT-001 違反: edit focus・一覧表示選択(enabled)・通知参加(notify)は独立する。enabled切替は条件・notify・edit indexを変えず、notify切替も条件・enabled・edit indexを変えず、edit index変更はrulesを変えない。別にVIEW選択ルールがある状態で非表示ルールへfilter候補を適用してもenabled/notifyを暗黙に変えない ({} 適用で非表示ruleを表示選択した)", candidate.id);
            prop_assert!(!state.rules[0].notify, "SPEC EDT-001 違反: edit focus・一覧表示選択(enabled)・通知参加(notify)は独立する。enabled切替は条件・notify・edit indexを変えず、notify切替も条件・enabled・edit indexを変えず、edit index変更はrulesを変えない。別にVIEW選択ルールがある状態で非表示ルールへfilter候補を適用してもenabled/notifyを暗黙に変えない ({} 適用でdraftを通知参加させた)", candidate.id);
            let settings = FilterSettings {
                rules: state.rules.clone(),
                min_remaining_secs: 0,
            };
            let projection = filter::notification_projection(&settings);
            prop_assert_eq!(
                projection.rules.as_slice(),
                expected_projection.as_slice(),
                "SPEC EDT-001 違反: edit focus・一覧表示選択(enabled)・通知参加(notify)は独立する。enabled切替は条件・notify・edit indexを変えず、notify切替も条件・enabled・edit indexを変えず、edit index変更はrulesを変えない。別にVIEW選択ルールがある状態で非表示ルールへfilter候補を適用してもenabled/notifyを暗黙に変えない (notify=false draft編集がnotification projectionへ現れた)"
            );
        }
    }

    /// EDT-002: NEW RULEは既存ルールを一切変更せず、enabled=falseかつnotify=falseの安全な空draftを末尾へ追加し、そのdraftをedit対象にする。VIEW選択0本でその空draftへ最初のfilter候補を適用すると、名前が付いていても別ルールを増やさずdraftをenabled=true・notify=falseのVIEWルールとして確定する
    #[test]
    fn edt_002(
        rules in proptest::collection::vec(arb_rule(), 0..5),
        pick in any::<prop::sample::Index>(),
        cand_pick in any::<prop::sample::Index>(),
    ) {
        let active = if rules.is_empty() { 0 } else { pick.index(rules.len()) };
        let mut state = palette::EditorState { rules, active };
        let before = state.rules.clone();
        let catalog = palette::catalog();
        let new_rule = catalog.iter()
            .find(|candidate| candidate.id == "action:new-rule")
            .expect("NEW RULE candidateが存在すること");
        palette::apply(&mut state, new_rule);
        prop_assert_eq!(state.rules.len(), before.len() + 1, "SPEC EDT-002 違反: NEW RULEは既存ルールを一切変更せず、enabled=falseかつnotify=falseの安全な空draftを末尾へ追加し、そのdraftをedit対象にする。VIEW選択0本でその空draftへ最初のfilter候補を適用すると、名前が付いていても別ルールを増やさずdraftをenabled=true・notify=falseのVIEWルールとして確定する (draftが1本追加されない)");
        prop_assert_eq!(&state.rules[..before.len()], before.as_slice(), "SPEC EDT-002 違反: NEW RULEは既存ルールを一切変更せず、enabled=falseかつnotify=falseの安全な空draftを末尾へ追加し、そのdraftをedit対象にする。VIEW選択0本でその空draftへ最初のfilter候補を適用すると、名前が付いていても別ルールを増やさずdraftをenabled=true・notify=falseのVIEWルールとして確定する (既存ルールを変更した)");
        prop_assert!(!state.rules.last().expect("draft追加済み").enabled, "SPEC EDT-002 違反: NEW RULEは既存ルールを一切変更せず、enabled=falseかつnotify=falseの安全な空draftを末尾へ追加し、そのdraftをedit対象にする。VIEW選択0本でその空draftへ最初のfilter候補を適用すると、名前が付いていても別ルールを増やさずdraftをenabled=true・notify=falseのVIEWルールとして確定する (NEW RULEがenabledで作成された)");
        prop_assert!(!state.rules.last().expect("draft追加済み").notify, "SPEC EDT-002 違反: NEW RULEは既存ルールを一切変更せず、enabled=falseかつnotify=falseの安全な空draftを末尾へ追加し、そのdraftをedit対象にする。VIEW選択0本でその空draftへ最初のfilter候補を適用すると、名前が付いていても別ルールを増やさずdraftをenabled=true・notify=falseのVIEWルールとして確定する (NEW RULEがnotify=trueで作成された)");
        prop_assert_eq!(state.active, state.rules.len() - 1, "SPEC EDT-002 違反: NEW RULEは既存ルールを一切変更せず、enabled=falseかつnotify=falseの安全な空draftを末尾へ追加し、そのdraftをedit対象にする。VIEW選択0本でその空draftへ最初のfilter候補を適用すると、名前が付いていても別ルールを増やさずdraftをenabled=true・notify=falseのVIEWルールとして確定する (新しいdraftがedit対象でない)");

        // VIEW選択0本の明示draftへ最初のfilter候補を適用すると、draftを再利用してVIEWルールへ確定する
        let mut no_view = before.clone();
        for rule in &mut no_view {
            rule.enabled = false;
            rule.notify = true;
        }
        let prefix = no_view.clone();
        let active = if no_view.is_empty() { 0 } else { pick.index(no_view.len()) };
        let mut draft_state = palette::EditorState { rules: no_view, active };
        palette::apply(&mut draft_state, new_rule);
        let draft_index = draft_state.active;
        // nameは判定条件ではないため、名前付きの空draftも同じルールとして再利用する
        draft_state.rules[draft_index].name = Some("NAMED DRAFT".to_string());
        let filter_candidates: Vec<Candidate> = palette::catalog()
            .into_iter()
            .filter(|candidate| !matches!(candidate.facet, Facet::Action | Facet::Rule))
            .collect();
        let filter_candidate = &filter_candidates[cand_pick.index(filter_candidates.len())];
        palette::apply(&mut draft_state, filter_candidate);
        prop_assert_eq!(draft_state.rules.len(), prefix.len() + 1, "SPEC EDT-002 違反: NEW RULEは既存ルールを一切変更せず、enabled=falseかつnotify=falseの安全な空draftを末尾へ追加し、そのdraftをedit対象にする。VIEW選択0本でその空draftへ最初のfilter候補を適用すると、名前が付いていても別ルールを増やさずdraftをenabled=true・notify=falseのVIEWルールとして確定する (空draft適用時に別ルールを追加した)");
        prop_assert_eq!(&draft_state.rules[..prefix.len()], prefix.as_slice(), "SPEC EDT-002 違反: NEW RULEは既存ルールを一切変更せず、enabled=falseかつnotify=falseの安全な空draftを末尾へ追加し、そのdraftをedit対象にする。VIEW選択0本でその空draftへ最初のfilter候補を適用すると、名前が付いていても別ルールを増やさずdraftをenabled=true・notify=falseのVIEWルールとして確定する (空draft確定時に既存ルールを変更した)");
        prop_assert_eq!(draft_state.active, draft_index, "SPEC EDT-002 違反: NEW RULEは既存ルールを一切変更せず、enabled=falseかつnotify=falseの安全な空draftを末尾へ追加し、そのdraftをedit対象にする。VIEW選択0本でその空draftへ最初のfilter候補を適用すると、名前が付いていても別ルールを増やさずdraftをenabled=true・notify=falseのVIEWルールとして確定する (空draft確定時にedit対象を移動した)");
        prop_assert!(draft_state.rules[draft_index].enabled, "SPEC EDT-002 違反: NEW RULEは既存ルールを一切変更せず、enabled=falseかつnotify=falseの安全な空draftを末尾へ追加し、そのdraftをedit対象にする。VIEW選択0本でその空draftへ最初のfilter候補を適用すると、名前が付いていても別ルールを増やさずdraftをenabled=true・notify=falseのVIEWルールとして確定する (空draftをVIEWルールへ確定しない)");
        prop_assert!(!draft_state.rules[draft_index].notify, "SPEC EDT-002 違反: NEW RULEは既存ルールを一切変更せず、enabled=falseかつnotify=falseの安全な空draftを末尾へ追加し、そのdraftをedit対象にする。VIEW選択0本でその空draftへ最初のfilter候補を適用すると、名前が付いていても別ルールを増やさずdraftをenabled=true・notify=falseのVIEWルールとして確定する (空draftを暗黙に通知参加させた)");
        prop_assert_eq!(draft_state.rules[draft_index].name.as_deref(), Some("NAMED DRAFT"), "SPEC EDT-002 違反: NEW RULEは既存ルールを一切変更せず、enabled=falseかつnotify=falseの安全な空draftを末尾へ追加し、そのdraftをedit対象にする。VIEW選択0本でその空draftへ最初のfilter候補を適用すると、名前が付いていても別ルールを増やさずdraftをenabled=true・notify=falseのVIEWルールとして確定する (空draft確定時に名前を失った)");
    }

    /// EDT-004: 表示選択が1本もない(無指定)状態でfilter候補を適用すると、既存ルールを変更せず末尾へenabled=true・notify=falseの新しいVIEWルールを1本作り、候補を適用してedit対象にする。以後のfilter候補は同じ新ルールへ適用して増殖させない。edit対象がNEW RULEで作った安全な空draftなら、そのdraftを再利用してVIEWルールへ確定する
    #[test]
    fn edt_004(
        mut rules in proptest::collection::vec(arb_rule(), 1..5),
        pick in any::<prop::sample::Index>(),
        first_pick in any::<prop::sample::Index>(),
        second_pick in any::<prop::sample::Index>(),
    ) {
        for rule in rules.iter_mut() {
            rule.enabled = false;
            // 既存ルールを安全な空draftと区別し、必ず新規作成経路を検査する
            rule.notify = true;
        }
        let active = pick.index(rules.len());
        let candidates: Vec<Candidate> = palette::catalog()
            .into_iter()
            .filter(|candidate| !matches!(candidate.facet, Facet::Action | Facet::Rule))
            .collect();
        let first = &candidates[first_pick.index(candidates.len())];
        let second = &candidates[second_pick.index(candidates.len())];

        // VIEW選択0本では既存ルールを保持し、VIEW ON・NOTIFY OFFの新ルールへ適用する
        let mut state = palette::EditorState { rules: rules.clone(), active };
        palette::apply(&mut state, first);
        prop_assert_eq!(state.rules.len(), rules.len() + 1, "SPEC EDT-004 違反: 表示選択が1本もない(無指定)状態でfilter候補を適用すると、既存ルールを変更せず末尾へenabled=true・notify=falseの新しいVIEWルールを1本作り、候補を適用してedit対象にする。以後のfilter候補は同じ新ルールへ適用して増殖させない。edit対象がNEW RULEで作った安全な空draftなら、そのdraftを再利用してVIEWルールへ確定する (新しいVIEWルールを1本追加しない)");
        prop_assert_eq!(&state.rules[..rules.len()], rules.as_slice(), "SPEC EDT-004 違反: 表示選択が1本もない(無指定)状態でfilter候補を適用すると、既存ルールを変更せず末尾へenabled=true・notify=falseの新しいVIEWルールを1本作り、候補を適用してedit対象にする。以後のfilter候補は同じ新ルールへ適用して増殖させない。edit対象がNEW RULEで作った安全な空draftなら、そのdraftを再利用してVIEWルールへ確定する (既存ルールを変更した)");
        prop_assert_eq!(state.active, rules.len(), "SPEC EDT-004 違反: 表示選択が1本もない(無指定)状態でfilter候補を適用すると、既存ルールを変更せず末尾へenabled=true・notify=falseの新しいVIEWルールを1本作り、候補を適用してedit対象にする。以後のfilter候補は同じ新ルールへ適用して増殖させない。edit対象がNEW RULEで作った安全な空draftなら、そのdraftを再利用してVIEWルールへ確定する (新しいルールをedit対象にしない)");

        let mut expected = palette::EditorState {
            rules: vec![WatchRule { enabled: true, notify: false, ..WatchRule::default() }],
            active: 0,
        };
        palette::apply(&mut expected, first);
        prop_assert_eq!(state.rules.last(), expected.rules.first(), "SPEC EDT-004 違反: 表示選択が1本もない(無指定)状態でfilter候補を適用すると、既存ルールを変更せず末尾へenabled=true・notify=falseの新しいVIEWルールを1本作り、候補を適用してedit対象にする。以後のfilter候補は同じ新ルールへ適用して増殖させない。edit対象がNEW RULEで作った安全な空draftなら、そのdraftを再利用してVIEWルールへ確定する (最初の候補を新ルールへ正しく適用しない)");
        let expected_after_first = expected.rules[0].clone();
        prop_assert!(state.rules.last().expect("新ルール追加済み").enabled, "SPEC EDT-004 違反: 表示選択が1本もない(無指定)状態でfilter候補を適用すると、既存ルールを変更せず末尾へenabled=true・notify=falseの新しいVIEWルールを1本作り、候補を適用してedit対象にする。以後のfilter候補は同じ新ルールへ適用して増殖させない。edit対象がNEW RULEで作った安全な空draftなら、そのdraftを再利用してVIEWルールへ確定する (新ルールがVIEW OFF)");
        prop_assert!(!state.rules.last().expect("新ルール追加済み").notify, "SPEC EDT-004 違反: 表示選択が1本もない(無指定)状態でfilter候補を適用すると、既存ルールを変更せず末尾へenabled=true・notify=falseの新しいVIEWルールを1本作り、候補を適用してedit対象にする。以後のfilter候補は同じ新ルールへ適用して増殖させない。edit対象がNEW RULEで作った安全な空draftなら、そのdraftを再利用してVIEWルールへ確定する (新ルールを暗黙に通知参加させた)");

        // 2候補目は同じ新ルールへ連続適用し、さらにルールを増やさない
        palette::apply(&mut state, second);
        palette::apply(&mut expected, second);
        prop_assert_eq!(state.rules.len(), rules.len() + 1, "SPEC EDT-004 違反: 表示選択が1本もない(無指定)状態でfilter候補を適用すると、既存ルールを変更せず末尾へenabled=true・notify=falseの新しいVIEWルールを1本作り、候補を適用してedit対象にする。以後のfilter候補は同じ新ルールへ適用して増殖させない。edit対象がNEW RULEで作った安全な空draftなら、そのdraftを再利用してVIEWルールへ確定する (後続候補でルールが増殖した)");
        prop_assert_eq!(&state.rules[..rules.len()], rules.as_slice(), "SPEC EDT-004 違反: 表示選択が1本もない(無指定)状態でfilter候補を適用すると、既存ルールを変更せず末尾へenabled=true・notify=falseの新しいVIEWルールを1本作り、候補を適用してedit対象にする。以後のfilter候補は同じ新ルールへ適用して増殖させない。edit対象がNEW RULEで作った安全な空draftなら、そのdraftを再利用してVIEWルールへ確定する (後続候補で既存ルールを変更した)");
        prop_assert_eq!(state.active, rules.len(), "SPEC EDT-004 違反: 表示選択が1本もない(無指定)状態でfilter候補を適用すると、既存ルールを変更せず末尾へenabled=true・notify=falseの新しいVIEWルールを1本作り、候補を適用してedit対象にする。以後のfilter候補は同じ新ルールへ適用して増殖させない。edit対象がNEW RULEで作った安全な空draftなら、そのdraftを再利用してVIEWルールへ確定する (後続候補でedit対象が移動した)");
        prop_assert_eq!(state.rules.last(), expected.rules.first(), "SPEC EDT-004 違反: 表示選択が1本もない(無指定)状態でfilter候補を適用すると、既存ルールを変更せず末尾へenabled=true・notify=falseの新しいVIEWルールを1本作り、候補を適用してedit対象にする。以後のfilter候補は同じ新ルールへ適用して増殖させない。edit対象がNEW RULEで作った安全な空draftなら、そのdraftを再利用してVIEWルールへ確定する (後続候補を同じ新ルールへ適用しない)");

        // ルール自体が0本でも同じVIEW ON・NOTIFY OFFルールを1本だけ作る
        let mut empty = palette::EditorState { rules: vec![], active: 0 };
        palette::apply(&mut empty, first);
        prop_assert_eq!(empty.rules, vec![expected_after_first], "SPEC EDT-004 違反: 表示選択が1本もない(無指定)状態でfilter候補を適用すると、既存ルールを変更せず末尾へenabled=true・notify=falseの新しいVIEWルールを1本作り、候補を適用してedit対象にする。以後のfilter候補は同じ新ルールへ適用して増殖させない。edit対象がNEW RULEで作った安全な空draftなら、そのdraftを再利用してVIEWルールへ確定する (ルール0本から正しい新VIEWルールを作らない)");
        prop_assert_eq!(empty.active, 0, "SPEC EDT-004 違反: 表示選択が1本もない(無指定)状態でfilter候補を適用すると、既存ルールを変更せず末尾へenabled=true・notify=falseの新しいVIEWルールを1本作り、候補を適用してedit対象にする。以後のfilter候補は同じ新ルールへ適用して増殖させない。edit対象がNEW RULEで作った安全な空draftなら、そのdraftを再利用してVIEWルールへ確定する (ルール0本から作成したルールをedit対象にしない)");
    }

    /// EDT-003: パレットの実行時カタログは各ルールをrule:{index}候補(label=ルール名、未設定ならR{n}、facet=RULE)として含み、適用は対象ルールのenabledだけを反転して条件・順序・notify・edit indexを変えず、再適用で元に戻る(トグル)。action:toggle-rule候補は編集中(active)ルールのenabledだけを、action:notify-rule候補は編集中ルールのnotifyだけを同様に反転する。action:deselect-all-rules(全ルール解除)は全ルールのenabledだけをfalseにしてnotify・条件・順序・edit indexを保持し、再適用しても同じ状態になる
    #[test]
    fn edt_003(
        rules in proptest::collection::vec(arb_rule(), 1..5),
        edit_pick in any::<prop::sample::Index>(),
        target_pick in any::<prop::sample::Index>(),
    ) {
        let active = edit_pick.index(rules.len());
        let target = target_pick.index(rules.len());
        let catalog = palette::catalog_with_rules(&rules);
        // 静的カタログの語彙は据え置きで、各ルールのrule:{index}候補が追加される
        for (i, rule) in rules.iter().enumerate() {
            let cand = catalog.iter()
                .find(|c| c.id == format!("rule:{i}"))
                .expect("rule候補が存在すること");
            let expected_label = rule.name.clone().unwrap_or_else(|| format!("R{}", i + 1));
            prop_assert_eq!(&cand.label, &expected_label, "SPEC EDT-003 違反: パレットの実行時カタログは各ルールをrule:{{index}}候補(label=ルール名、未設定ならR{{n}}、facet=RULE)として含み、適用は対象ルールのenabledだけを反転して条件・順序・notify・edit indexを変えず、再適用で元に戻る(トグル)。action:toggle-rule候補は編集中(active)ルールのenabledだけを、action:notify-rule候補は編集中ルールのnotifyだけを同様に反転する。action:deselect-all-rules(全ルール解除)は全ルールのenabledだけをfalseにしてnotify・条件・順序・edit indexを保持し、再適用しても同じ状態になる (labelが名前/R{{n}}でない)");
            prop_assert_eq!(cand.facet, Facet::Rule, "SPEC EDT-003 違反: パレットの実行時カタログは各ルールをrule:{{index}}候補(label=ルール名、未設定ならR{{n}}、facet=RULE)として含み、適用は対象ルールのenabledだけを反転して条件・順序・notify・edit indexを変えず、再適用で元に戻る(トグル)。action:toggle-rule候補は編集中(active)ルールのenabledだけを、action:notify-rule候補は編集中ルールのnotifyだけを同様に反転する。action:deselect-all-rules(全ルール解除)は全ルールのenabledだけをfalseにしてnotify・条件・順序・edit indexを保持し、再適用しても同じ状態になる (facetがRULEでない)");
        }
        // 適用は対象ルールのenabledだけを反転し、条件・順序・edit indexを変えない
        let cand = catalog.iter()
            .find(|c| c.id == format!("rule:{target}"))
            .expect("rule候補が存在すること");
        let mut state = palette::EditorState { rules: rules.clone(), active };
        palette::apply(&mut state, cand);
        prop_assert_eq!(state.active, active, "SPEC EDT-003 違反: パレットの実行時カタログは各ルールをrule:{{index}}候補(label=ルール名、未設定ならR{{n}}、facet=RULE)として含み、適用は対象ルールのenabledだけを反転して条件・順序・notify・edit indexを変えず、再適用で元に戻る(トグル)。action:toggle-rule候補は編集中(active)ルールのenabledだけを、action:notify-rule候補は編集中ルールのnotifyだけを同様に反転する。action:deselect-all-rules(全ルール解除)は全ルールのenabledだけをfalseにしてnotify・条件・順序・edit indexを保持し、再適用しても同じ状態になる (edit indexが変化した)");
        let mut expected = rules.clone();
        expected[target].enabled = !rules[target].enabled;
        prop_assert_eq!(state.rules.as_slice(), expected.as_slice(), "SPEC EDT-003 違反: パレットの実行時カタログは各ルールをrule:{{index}}候補(label=ルール名、未設定ならR{{n}}、facet=RULE)として含み、適用は対象ルールのenabledだけを反転して条件・順序・notify・edit indexを変えず、再適用で元に戻る(トグル)。action:toggle-rule候補は編集中(active)ルールのenabledだけを、action:notify-rule候補は編集中ルールのnotifyだけを同様に反転する。action:deselect-all-rules(全ルール解除)は全ルールのenabledだけをfalseにしてnotify・条件・順序・edit indexを保持し、再適用しても同じ状態になる (enabled反転以外が変化した)");
        // 再適用で元に戻る(トグル)
        palette::apply(&mut state, cand);
        prop_assert_eq!(state.rules.as_slice(), rules.as_slice(), "SPEC EDT-003 違反: パレットの実行時カタログは各ルールをrule:{{index}}候補(label=ルール名、未設定ならR{{n}}、facet=RULE)として含み、適用は対象ルールのenabledだけを反転して条件・順序・notify・edit indexを変えず、再適用で元に戻る(トグル)。action:toggle-rule候補は編集中(active)ルールのenabledだけを、action:notify-rule候補は編集中ルールのnotifyだけを同様に反転する。action:deselect-all-rules(全ルール解除)は全ルールのenabledだけをfalseにしてnotify・条件・順序・edit indexを保持し、再適用しても同じ状態になる (再適用で往復しない)");

        // action:toggle-rule は編集中(active)ルールのenabledだけを同様に反転する
        let toggle_cand = catalog.iter()
            .find(|c| c.id == "action:toggle-rule")
            .expect("TOGGLE RULE候補が存在すること");
        let mut state = palette::EditorState { rules: rules.clone(), active };
        palette::apply(&mut state, toggle_cand);
        prop_assert_eq!(state.active, active, "SPEC EDT-003 違反: パレットの実行時カタログは各ルールをrule:{{index}}候補(label=ルール名、未設定ならR{{n}}、facet=RULE)として含み、適用は対象ルールのenabledだけを反転して条件・順序・notify・edit indexを変えず、再適用で元に戻る(トグル)。action:toggle-rule候補は編集中(active)ルールのenabledだけを、action:notify-rule候補は編集中ルールのnotifyだけを同様に反転する。action:deselect-all-rules(全ルール解除)は全ルールのenabledだけをfalseにしてnotify・条件・順序・edit indexを保持し、再適用しても同じ状態になる (toggle-ruleでedit indexが変化した)");
        let mut expected = rules.clone();
        expected[active].enabled = !rules[active].enabled;
        prop_assert_eq!(state.rules.as_slice(), expected.as_slice(), "SPEC EDT-003 違反: パレットの実行時カタログは各ルールをrule:{{index}}候補(label=ルール名、未設定ならR{{n}}、facet=RULE)として含み、適用は対象ルールのenabledだけを反転して条件・順序・notify・edit indexを変えず、再適用で元に戻る(トグル)。action:toggle-rule候補は編集中(active)ルールのenabledだけを、action:notify-rule候補は編集中ルールのnotifyだけを同様に反転する。action:deselect-all-rules(全ルール解除)は全ルールのenabledだけをfalseにしてnotify・条件・順序・edit indexを保持し、再適用しても同じ状態になる (toggle-ruleがactive以外を変更した)");
        palette::apply(&mut state, toggle_cand);
        prop_assert_eq!(state.rules.as_slice(), rules.as_slice(), "SPEC EDT-003 違反: パレットの実行時カタログは各ルールをrule:{{index}}候補(label=ルール名、未設定ならR{{n}}、facet=RULE)として含み、適用は対象ルールのenabledだけを反転して条件・順序・notify・edit indexを変えず、再適用で元に戻る(トグル)。action:toggle-rule候補は編集中(active)ルールのenabledだけを、action:notify-rule候補は編集中ルールのnotifyだけを同様に反転する。action:deselect-all-rules(全ルール解除)は全ルールのenabledだけをfalseにしてnotify・条件・順序・edit indexを保持し、再適用しても同じ状態になる (toggle-rule再適用で往復しない)");

        // action:notify-rule は編集中(active)ルールのnotifyだけを同様に反転する
        let notify_cand = catalog.iter()
            .find(|c| c.id == "action:notify-rule")
            .expect("TOGGLE NOTIFY候補が存在すること");
        let mut state = palette::EditorState { rules: rules.clone(), active };
        palette::apply(&mut state, notify_cand);
        prop_assert_eq!(state.active, active, "SPEC EDT-003 違反: パレットの実行時カタログは各ルールをrule:{{index}}候補(label=ルール名、未設定ならR{{n}}、facet=RULE)として含み、適用は対象ルールのenabledだけを反転して条件・順序・notify・edit indexを変えず、再適用で元に戻る(トグル)。action:toggle-rule候補は編集中(active)ルールのenabledだけを、action:notify-rule候補は編集中ルールのnotifyだけを同様に反転する。action:deselect-all-rules(全ルール解除)は全ルールのenabledだけをfalseにしてnotify・条件・順序・edit indexを保持し、再適用しても同じ状態になる (notify-ruleでedit indexが変化した)");
        let mut expected = rules.clone();
        expected[active].notify = !rules[active].notify;
        prop_assert_eq!(state.rules.as_slice(), expected.as_slice(), "SPEC EDT-003 違反: パレットの実行時カタログは各ルールをrule:{{index}}候補(label=ルール名、未設定ならR{{n}}、facet=RULE)として含み、適用は対象ルールのenabledだけを反転して条件・順序・notify・edit indexを変えず、再適用で元に戻る(トグル)。action:toggle-rule候補は編集中(active)ルールのenabledだけを、action:notify-rule候補は編集中ルールのnotifyだけを同様に反転する。action:deselect-all-rules(全ルール解除)は全ルールのenabledだけをfalseにしてnotify・条件・順序・edit indexを保持し、再適用しても同じ状態になる (notify-ruleがnotify以外を変更した)");
        palette::apply(&mut state, notify_cand);
        prop_assert_eq!(state.rules.as_slice(), rules.as_slice(), "SPEC EDT-003 違反: パレットの実行時カタログは各ルールをrule:{{index}}候補(label=ルール名、未設定ならR{{n}}、facet=RULE)として含み、適用は対象ルールのenabledだけを反転して条件・順序・notify・edit indexを変えず、再適用で元に戻る(トグル)。action:toggle-rule候補は編集中(active)ルールのenabledだけを、action:notify-rule候補は編集中ルールのnotifyだけを同様に反転する。action:deselect-all-rules(全ルール解除)は全ルールのenabledだけをfalseにしてnotify・条件・順序・edit indexを保持し、再適用しても同じ状態になる (notify-rule再適用で往復しない)");

        // action:deselect-all-rules は全enabledだけをfalseにし、通知射影・条件・順序・edit indexを保持する
        let deselect_cand = catalog.iter()
            .find(|c| c.id == "action:deselect-all-rules")
            .expect("DESELECT ALL RULES候補が存在すること");
        let before_projection = filter::notification_projection(&FilterSettings {
            rules: rules.clone(),
            min_remaining_secs: 123,
        });
        let mut state = palette::EditorState { rules: rules.clone(), active };
        palette::apply(&mut state, deselect_cand);
        prop_assert_eq!(state.active, active, "SPEC EDT-003 違反: パレットの実行時カタログは各ルールをrule:{{index}}候補(label=ルール名、未設定ならR{{n}}、facet=RULE)として含み、適用は対象ルールのenabledだけを反転して条件・順序・notify・edit indexを変えず、再適用で元に戻る(トグル)。action:toggle-rule候補は編集中(active)ルールのenabledだけを、action:notify-rule候補は編集中ルールのnotifyだけを同様に反転する。action:deselect-all-rules(全ルール解除)は全ルールのenabledだけをfalseにしてnotify・条件・順序・edit indexを保持し、再適用しても同じ状態になる (全ルール解除でedit indexが変化した)");
        let mut expected = rules.clone();
        for rule in &mut expected {
            rule.enabled = false;
        }
        prop_assert_eq!(state.rules.as_slice(), expected.as_slice(), "SPEC EDT-003 違反: パレットの実行時カタログは各ルールをrule:{{index}}候補(label=ルール名、未設定ならR{{n}}、facet=RULE)として含み、適用は対象ルールのenabledだけを反転して条件・順序・notify・edit indexを変えず、再適用で元に戻る(トグル)。action:toggle-rule候補は編集中(active)ルールのenabledだけを、action:notify-rule候補は編集中ルールのnotifyだけを同様に反転する。action:deselect-all-rules(全ルール解除)は全ルールのenabledだけをfalseにしてnotify・条件・順序・edit indexを保持し、再適用しても同じ状態になる (全ルール解除がenabled以外を変更した)");
        let after_projection = filter::notification_projection(&FilterSettings {
            rules: state.rules.clone(),
            min_remaining_secs: 123,
        });
        prop_assert_eq!(after_projection, before_projection, "SPEC EDT-003 違反: パレットの実行時カタログは各ルールをrule:{{index}}候補(label=ルール名、未設定ならR{{n}}、facet=RULE)として含み、適用は対象ルールのenabledだけを反転して条件・順序・notify・edit indexを変えず、再適用で元に戻る(トグル)。action:toggle-rule候補は編集中(active)ルールのenabledだけを、action:notify-rule候補は編集中ルールのnotifyだけを同様に反転する。action:deselect-all-rules(全ルール解除)は全ルールのenabledだけをfalseにしてnotify・条件・順序・edit indexを保持し、再適用しても同じ状態になる (全ルール解除で通知射影が変化した)");
        palette::apply(&mut state, deselect_cand);
        prop_assert_eq!(state.rules.as_slice(), expected.as_slice(), "SPEC EDT-003 違反: パレットの実行時カタログは各ルールをrule:{{index}}候補(label=ルール名、未設定ならR{{n}}、facet=RULE)として含み、適用は対象ルールのenabledだけを反転して条件・順序・notify・edit indexを変えず、再適用で元に戻る(トグル)。action:toggle-rule候補は編集中(active)ルールのenabledだけを、action:notify-rule候補は編集中ルールのnotifyだけを同様に反転する。action:deselect-all-rules(全ルール解除)は全ルールのenabledだけをfalseにしてnotify・条件・順序・edit indexを保持し、再適用しても同じ状態になる (全ルール解除が冪等でない)");
    }

    /// CLR-001: クリア操作は1回でルール構成を既定(enabled=trueの全対象ルール1本、ストーム除外、両方モード)に戻す
    #[test]
    fn clr_001(rules in proptest::collection::vec(arb_rule(), 0..4), pick in any::<prop::sample::Index>()) {
        let active = if rules.is_empty() { 0 } else { pick.index(rules.len()) };
        let mut state = palette::EditorState { rules, active };
        palette::clear(&mut state);
        prop_assert_eq!(state.rules.len(), 1, "SPEC CLR-001 違反: クリア操作は1回でルール構成を既定(enabled=trueの全対象ルール1本、ストーム除外、両方モード)に戻す");
        prop_assert_eq!(state.active, 0, "SPEC CLR-001 違反: クリア操作は1回でルール構成を既定(enabled=trueの全対象ルール1本、ストーム除外、両方モード)に戻す");
        let r = &state.rules[0];
        prop_assert!(
            r.tiers.is_empty() && r.mission_types.is_empty() && r.planets.is_empty(),
            "SPEC CLR-001 違反: クリア操作は1回でルール構成を既定(enabled=trueの全対象ルール1本、ストーム除外、両方モード)に戻す (軸が既定でない)"
        );
        prop_assert!(matches!(r.mode, Mode::Both), "SPEC CLR-001 違反: クリア操作は1回でルール構成を既定(enabled=trueの全対象ルール1本、ストーム除外、両方モード)に戻す (modeが既定でない)");
        prop_assert!(matches!(r.storms, StormMode::Exclude), "SPEC CLR-001 違反: クリア操作は1回でルール構成を既定(enabled=trueの全対象ルール1本、ストーム除外、両方モード)に戻す (stormsが既定でない)");
        prop_assert!(r.enabled, "SPEC CLR-001 違反: クリア操作は1回でルール構成を既定(enabled=trueの全対象ルール1本、ストーム除外、両方モード)に戻す (既定ルールがdisabled)");
        prop_assert!(palette::satisfiable(r), "SPEC CLR-001 違反: クリア操作は1回でルール構成を既定(enabled=trueの全対象ルール1本、ストーム除外、両方モード)に戻す (既定ルールが充足不能)");
    }

    /// CFG-001: 旧設定のincludeStorms=false/trueは、読込時にstorms=除外/含むへそれぞれ無損失移行される
    #[test]
    fn cfg_001(include in any::<bool>()) {
        let raw = format!(r#"{{"includeStorms":{include}}}"#);
        let rule: WatchRule = serde_json::from_str(&raw)
            .expect("旧WatchRule JSONを読み込めること");
        let expected = if include { StormMode::Include } else { StormMode::Exclude };
        prop_assert_eq!(rule.storms, expected, "SPEC CFG-001 違反: 旧設定のincludeStorms=false/trueは、読込時にstorms=除外/含むへそれぞれ無損失移行される");
    }
}


/// CFG-002: enabledを持たない既存WatchRule JSONはenabled=true(一覧表示へ参加)として読み込み、明示したenabled=falseはserialize/deserialize後もfalseのまま保持する
#[test]
fn cfg_002() {
    let legacy: WatchRule = serde_json::from_str(
        r#"{"tiers":["Axi"],"includeStorms":false}"#,
    )
    .expect("enabled欠落の旧WatchRule JSONを読み込めること");
    assert!(legacy.enabled, "SPEC CFG-002 違反: enabledを持たない既存WatchRule JSONはenabled=true(一覧表示へ参加)として読み込み、明示したenabled=falseはserialize/deserialize後もfalseのまま保持する (enabled欠落をfalseへ移行した)");

    let explicit_disabled: WatchRule = serde_json::from_str(r#"{"enabled":false}"#)
        .expect("enabled=falseを読み込めること");
    assert!(!explicit_disabled.enabled, "SPEC CFG-002 違反: enabledを持たない既存WatchRule JSONはenabled=true(一覧表示へ参加)として読み込み、明示したenabled=falseはserialize/deserialize後もfalseのまま保持する (明示falseをtrueへ変更した)");
    let encoded = serde_json::to_string(&explicit_disabled)
        .expect("enabled=falseをserializeできること");
    let round_trip: WatchRule = serde_json::from_str(&encoded)
        .expect("serialize済みWatchRuleを再読込できること");
    assert!(!round_trip.enabled, "SPEC CFG-002 違反: enabledを持たない既存WatchRule JSONはenabled=true(一覧表示へ参加)として読み込み、明示したenabled=falseはserialize/deserialize後もfalseのまま保持する (round-tripで明示falseを失った)");
}

/// CFG-003: WatchRuleのnameは省略可能な表示用メタデータで、nameを持たない旧JSONは名前なしとして読み込み、設定したnameはserialize/deserializeを往復しても他のフィールドと共に保持される
#[test]
fn cfg_003() {
    let legacy: WatchRule = serde_json::from_str(
        r#"{"tiers":["Axi"],"includeStorms":false}"#,
    )
    .expect("name欠落の旧WatchRule JSONを読み込めること");
    assert!(legacy.name.is_none(), "SPEC CFG-003 違反: WatchRuleのnameは省略可能な表示用メタデータで、nameを持たない旧JSONは名前なしとして読み込み、設定したnameはserialize/deserializeを往復しても他のフィールドと共に保持される (name欠落を名前ありへ移行した)");

    let named = WatchRule {
        name: Some("MY FARM".to_string()),
        tiers: vec!["Axi".to_string()],
        enabled: false,
        ..WatchRule::default()
    };
    let encoded = serde_json::to_string(&named).expect("name付きWatchRuleをserializeできること");
    let round_trip: WatchRule = serde_json::from_str(&encoded)
        .expect("serialize済みWatchRuleを再読込できること");
    assert_eq!(round_trip, named, "SPEC CFG-003 違反: WatchRuleのnameは省略可能な表示用メタデータで、nameを持たない旧JSONは名前なしとして読み込み、設定したnameはserialize/deserializeを往復しても他のフィールドと共に保持される (nameまたは他フィールドがround-tripで変わった)");
}

/// CFG-004: WatchRuleのnotifyはenabledから独立した通知参加フラグで、notifyを持たない旧JSONは旧enabled値(それも欠落ならtrue)を引き継ぐ。明示したnotify=true/falseはenabledの値に関係なくserialize/deserializeを往復しても保持される
#[test]
fn cfg_004() {
    let legacy_enabled: WatchRule = serde_json::from_str(
        r#"{"tiers":["Axi"],"includeStorms":false}"#,
    )
    .expect("notify欠落の旧WatchRule JSONを読み込めること");
    assert!(legacy_enabled.enabled && legacy_enabled.notify, "SPEC CFG-004 違反: WatchRuleのnotifyはenabledから独立した通知参加フラグで、notifyを持たない旧JSONは旧enabled値(それも欠落ならtrue)を引き継ぐ。明示したnotify=true/falseはenabledの値に関係なくserialize/deserializeを往復しても保持される (enabled欠落時の既定trueをnotifyへ引き継がない)");

    let legacy_disabled: WatchRule = serde_json::from_str(
        r#"{"enabled":false,"tiers":["Axi"]}"#,
    )
    .expect("notify欠落・enabled=falseの旧WatchRule JSONを読み込めること");
    assert!(!legacy_disabled.notify, "SPEC CFG-004 違反: WatchRuleのnotifyはenabledから独立した通知参加フラグで、notifyを持たない旧JSONは旧enabled値(それも欠落ならtrue)を引き継ぐ。明示したnotify=true/falseはenabledの値に関係なくserialize/deserializeを往復しても保持される (旧disabled draftを通知ONへ移行した)");

    let hidden_notify: WatchRule = serde_json::from_str(
        r#"{"enabled":false,"notify":true,"tiers":["Axi"]}"#,
    )
    .expect("明示notify=trueの非表示WatchRule JSONを読み込めること");
    assert!(!hidden_notify.enabled && hidden_notify.notify, "SPEC CFG-004 違反: WatchRuleのnotifyはenabledから独立した通知参加フラグで、notifyを持たない旧JSONは旧enabled値(それも欠落ならtrue)を引き継ぐ。明示したnotify=true/falseはenabledの値に関係なくserialize/deserializeを往復しても保持される (明示notify=trueをenabledへ結合した)");

    let display_only = WatchRule {
        notify: false,
        enabled: true,
        tiers: vec!["Axi".to_string()],
        ..WatchRule::default()
    };
    let encoded =
        serde_json::to_string(&display_only).expect("notify=falseのWatchRuleをserializeできること");
    let round_trip: WatchRule = serde_json::from_str(&encoded)
        .expect("serialize済みWatchRuleを再読込できること");
    assert_eq!(round_trip, display_only, "SPEC CFG-004 違反: WatchRuleのnotifyはenabledから独立した通知参加フラグで、notifyを持たない旧JSONは旧enabled値(それも欠落ならtrue)を引き継ぐ。明示したnotify=true/falseはenabledの値に関係なくserialize/deserializeを往復しても保持される (notifyまたは他フィールドがround-tripで変わった)");

    let encoded = serde_json::to_string(&hidden_notify)
        .expect("enabled=false, notify=trueのWatchRuleをserializeできること");
    let round_trip: WatchRule = serde_json::from_str(&encoded)
        .expect("非表示通知WatchRuleを再読込できること");
    assert_eq!(round_trip, hidden_notify, "SPEC CFG-004 違反: WatchRuleのnotifyはenabledから独立した通知参加フラグで、notifyを持たない旧JSONは旧enabled値(それも欠落ならtrue)を引き継ぐ。明示したnotify=true/falseはenabledの値に関係なくserialize/deserializeを往復しても保持される (enabledとnotifyの独立状態をround-tripで失った)");
}

/// NTF-001: 通知テストは全選択先の要求受付時だけ成功し、desktopを表示済み・配信済みとは扱わない。1件でも失敗すれば失敗先・理由・要求受付済みの部分成功先を保持して失敗し、通知先なしも失敗する
#[test]
fn ntf_001() {
    let accepted = notify::summarize_test_outcomes(&[
        NotificationOutcome::Requested { destination: "desktop" },
        NotificationOutcome::Requested { destination: "discord" },
    ])
    .expect("全選択先がRequestedなら成功すること");
    assert!(
        accepted.contains("通知要求を受け付けました"),
        "SPEC NTF-001 違反: 通知テストは全選択先の要求受付時だけ成功し、desktopを表示済み・配信済みとは扱わない。1件でも失敗すれば失敗先・理由・要求受付済みの部分成功先を保持して失敗し、通知先なしも失敗する (要求受付の文言がない: {accepted})"
    );
    for forbidden in ["送信OK", "表示済み", "配信済み"] {
        assert!(
            !accepted.contains(forbidden),
            "SPEC NTF-001 違反: 通知テストは全選択先の要求受付時だけ成功し、desktopを表示済み・配信済みとは扱わない。1件でも失敗すれば失敗先・理由・要求受付済みの部分成功先を保持して失敗し、通知先なしも失敗する (結果不明なのに成功を主張した: {accepted})"
        );
    }

    let partial = notify::summarize_test_outcomes(&[
        NotificationOutcome::Requested { destination: "desktop" },
        NotificationOutcome::Failed {
            destination: "discord",
            reason: "HTTP 500".to_string(),
        },
    ])
    .expect_err("1件でもFailedなら失敗すること");
    assert!(partial.contains("desktop"), "SPEC NTF-001 違反: 通知テストは全選択先の要求受付時だけ成功し、desktopを表示済み・配信済みとは扱わない。1件でも失敗すれば失敗先・理由・要求受付済みの部分成功先を保持して失敗し、通知先なしも失敗する (部分成功先がない: {partial})");
    assert!(partial.contains("discord"), "SPEC NTF-001 違反: 通知テストは全選択先の要求受付時だけ成功し、desktopを表示済み・配信済みとは扱わない。1件でも失敗すれば失敗先・理由・要求受付済みの部分成功先を保持して失敗し、通知先なしも失敗する (失敗先がない: {partial})");
    assert!(partial.contains("HTTP 500"), "SPEC NTF-001 違反: 通知テストは全選択先の要求受付時だけ成功し、desktopを表示済み・配信済みとは扱わない。1件でも失敗すれば失敗先・理由・要求受付済みの部分成功先を保持して失敗し、通知先なしも失敗する (失敗理由がない: {partial})");
    for forbidden in ["送信OK", "表示済み", "配信済み"] {
        assert!(
            !partial.contains(forbidden),
            "SPEC NTF-001 違反: 通知テストは全選択先の要求受付時だけ成功し、desktopを表示済み・配信済みとは扱わない。1件でも失敗すれば失敗先・理由・要求受付済みの部分成功先を保持して失敗し、通知先なしも失敗する (エラーに成功語がある: {partial})"
        );
    }

    assert!(
        notify::summarize_test_outcomes(&[]).is_err(),
        "SPEC NTF-001 違反: 通知テストは全選択先の要求受付時だけ成功し、desktopを表示済み・配信済みとは扱わない。1件でも失敗すれば失敗先・理由・要求受付済みの部分成功先を保持して失敗し、通知先なしも失敗する (通知先なしを成功扱いした)"
    );
}

/// NTF-002: desktop通知payloadは呼出側から渡した同一nowで残り時間を計算し、HARDとSTORMを独立にtitleへ含め、期限切れの残り時間を0分に丸める
#[test]
fn ntf_002() {
    let now = base_now();
    let mut fissure = Fissure {
        id: "notification-example".to_string(),
        activation: now,
        expiry: now + Duration::minutes(30),
        node: "Test Node (Void)".to_string(),
        mission_type: "Survival".to_string(),
        enemy: "Orokin".to_string(),
        tier: "Axi".to_string(),
        tier_num: 4,
        is_storm: true,
        is_hard: true,
    };

    let payload = notify::desktop_payload(&fissure, now);
    assert_eq!(
        payload.title,
        "Axi Survival — Test Node (Void) 【鋼】 [STORM]",
        "SPEC NTF-002 違反: desktop通知payloadは呼出側から渡した同一nowで残り時間を計算し、HARDとSTORMを独立にtitleへ含め、期限切れの残り時間を0分に丸める (title)"
    );
    assert_eq!(
        payload.body,
        "Orokin / 消滅まで残り30分",
        "SPEC NTF-002 違反: desktop通知payloadは呼出側から渡した同一nowで残り時間を計算し、HARDとSTORMを独立にtitleへ含め、期限切れの残り時間を0分に丸める (body)"
    );

    fissure.expiry = now - Duration::seconds(1);
    let expired = notify::desktop_payload(&fissure, now);
    assert_eq!(
        expired.body,
        "Orokin / 消滅まで残り0分",
        "SPEC NTF-002 違反: desktop通知payloadは呼出側から渡した同一nowで残り時間を計算し、HARDとSTORMを独立にtitleへ含め、期限切れの残り時間を0分に丸める (期限切れbody)"
    );
}

/// NTF-003: 未バンドルのraw devでdesktop通知を利用できない場合は、失敗詳細を保持し、デバッグbundle .appを使う just notification-test を案内する
#[test]
fn ntf_003() {
    let detail = "notification backend unavailable";
    let message = notify::desktop_unavailable_message(detail);
    assert!(message.contains(detail), "SPEC NTF-003 違反: 未バンドルのraw devでdesktop通知を利用できない場合は、失敗詳細を保持し、デバッグbundle .appを使う just notification-test を案内する (失敗詳細がない: {message})");
    assert!(
        message.contains("just notification-test"),
        "SPEC NTF-003 違反: 未バンドルのraw devでdesktop通知を利用できない場合は、失敗詳細を保持し、デバッグbundle .appを使う just notification-test を案内する (実行コマンドがない: {message})"
    );
    assert!(
        message.contains(".app"),
        "SPEC NTF-003 違反: 未バンドルのraw devでdesktop通知を利用できない場合は、失敗詳細を保持し、デバッグbundle .appを使う just notification-test を案内する (bundleアプリを使う案内がない: {message})"
    );
    for forbidden in ["送信OK", "表示済み", "配信済み"] {
        assert!(
            !message.contains(forbidden),
            "SPEC NTF-003 違反: 未バンドルのraw devでdesktop通知を利用できない場合は、失敗詳細を保持し、デバッグbundle .appを使う just notification-test を案内する (利用不能案内に成功語がある: {message})"
        );
    }
}

/// NTF-004: Discord Webhook URLは既存queryを保持しながらwait=trueをちょうど1つに正規化し、レスポンスが非空Message IDを含むJSONのときだけ要求受付と判定する。ID欠落・空文字・不正JSONは失敗する
#[test]
fn ntf_004() {
    let request_url = match notify::discord_request_url(
        "https://discord.com/api/webhooks/123/test-token?thread_id=456&wait=false&foo=bar&wait=false",
    ) {
        Ok(url) => url,
        Err(_) => panic!("SPEC NTF-004 違反: Discord Webhook URLは既存queryを保持しながらwait=trueをちょうど1つに正規化し、レスポンスが非空Message IDを含むJSONのときだけ要求受付と判定する。ID欠落・空文字・不正JSONは失敗する (有効なWebhook URLを構築できない)"),
    };
    let query: Vec<(String, String)> = request_url
        .query_pairs()
        .map(|(key, value)| (key.into_owned(), value.into_owned()))
        .collect();
    assert!(
        query.iter().any(|pair| pair == &("thread_id".to_string(), "456".to_string())),
        "SPEC NTF-004 違反: Discord Webhook URLは既存queryを保持しながらwait=trueをちょうど1つに正規化し、レスポンスが非空Message IDを含むJSONのときだけ要求受付と判定する。ID欠落・空文字・不正JSONは失敗する (既存thread_id queryが失われた)"
    );
    assert!(
        query.iter().any(|pair| pair == &("foo".to_string(), "bar".to_string())),
        "SPEC NTF-004 違反: Discord Webhook URLは既存queryを保持しながらwait=trueをちょうど1つに正規化し、レスポンスが非空Message IDを含むJSONのときだけ要求受付と判定する。ID欠落・空文字・不正JSONは失敗する (既存queryが失われた)"
    );
    let waits: Vec<&str> = query
        .iter()
        .filter(|(key, _)| key == "wait")
        .map(|(_, value)| value.as_str())
        .collect();
    assert_eq!(
        waits,
        vec!["true"],
        "SPEC NTF-004 違反: Discord Webhook URLは既存queryを保持しながらwait=trueをちょうど1つに正規化し、レスポンスが非空Message IDを含むJSONのときだけ要求受付と判定する。ID欠落・空文字・不正JSONは失敗する (wait queryはtrueをちょうど1つだけ持つこと)"
    );

    let message_id = notify::discord_message_id(r#"{"id":"1234567890"}"#)
        .unwrap_or_else(|_| panic!("SPEC NTF-004 違反: Discord Webhook URLは既存queryを保持しながらwait=trueをちょうど1つに正規化し、レスポンスが非空Message IDを含むJSONのときだけ要求受付と判定する。ID欠落・空文字・不正JSONは失敗する (非空Message IDを拒否した)"));
    assert_eq!(message_id, "1234567890", "SPEC NTF-004 違反: Discord Webhook URLは既存queryを保持しながらwait=trueをちょうど1つに正規化し、レスポンスが非空Message IDを含むJSONのときだけ要求受付と判定する。ID欠落・空文字・不正JSONは失敗する (Message IDを保持しない)");

    for invalid_response in [r#"{}"#, r#"{"id":""}"#, "not json"] {
        assert!(
            notify::discord_message_id(invalid_response).is_err(),
            "SPEC NTF-004 違反: Discord Webhook URLは既存queryを保持しながらwait=trueをちょうど1つに正規化し、レスポンスが非空Message IDを含むJSONのときだけ要求受付と判定する。ID欠落・空文字・不正JSONは失敗する (ID欠落・空文字・不正JSONを成功扱いした)"
        );
    }
}

/// STA-001: 配布版(relico / com.annenpolka.relico)・通知テスト版(RELICO Notification Test / com.annenpolka.relico.notification-test)・E2E版(RELICO E2E / com.annenpolka.relico.e2e)は設定ファイル上でproductName・identifierがそれぞれ規定値を持ち、互いに一致しない
#[test]
fn sta_001() {
    let manifest = std::path::Path::new(env!("CARGO_MANIFEST_DIR"));
    let release: serde_json::Value = serde_json::from_str(
        &std::fs::read_to_string(manifest.join("tauri.conf.json"))
            .expect("tauri.conf.jsonを読めること"),
    )
    .expect("tauri.conf.jsonがJSONであること");
    let test: serde_json::Value = serde_json::from_str(
        &std::fs::read_to_string(manifest.join("tauri.notification-test.conf.json"))
            .expect("tauri.notification-test.conf.jsonを読めること"),
    )
    .expect("tauri.notification-test.conf.jsonがJSONであること");

    assert_eq!(
        release["identifier"], "com.annenpolka.relico",
        "SPEC STA-001 違反: 配布版(relico / com.annenpolka.relico)・通知テスト版(RELICO Notification Test / com.annenpolka.relico.notification-test)・E2E版(RELICO E2E / com.annenpolka.relico.e2e)は設定ファイル上でproductName・identifierがそれぞれ規定値を持ち、互いに一致しない (配布identifier)"
    );
    assert_eq!(release["productName"], "relico", "SPEC STA-001 違反: 配布版(relico / com.annenpolka.relico)・通知テスト版(RELICO Notification Test / com.annenpolka.relico.notification-test)・E2E版(RELICO E2E / com.annenpolka.relico.e2e)は設定ファイル上でproductName・identifierがそれぞれ規定値を持ち、互いに一致しない (配布productName)");
    assert_eq!(
        test["identifier"], "com.annenpolka.relico.notification-test",
        "SPEC STA-001 違反: 配布版(relico / com.annenpolka.relico)・通知テスト版(RELICO Notification Test / com.annenpolka.relico.notification-test)・E2E版(RELICO E2E / com.annenpolka.relico.e2e)は設定ファイル上でproductName・identifierがそれぞれ規定値を持ち、互いに一致しない (通知テストidentifier)"
    );
    assert_eq!(
        test["productName"], "RELICO Notification Test",
        "SPEC STA-001 違反: 配布版(relico / com.annenpolka.relico)・通知テスト版(RELICO Notification Test / com.annenpolka.relico.notification-test)・E2E版(RELICO E2E / com.annenpolka.relico.e2e)は設定ファイル上でproductName・identifierがそれぞれ規定値を持ち、互いに一致しない (通知テストproductName)"
    );
    let e2e: serde_json::Value = serde_json::from_str(
        &std::fs::read_to_string(manifest.join("tauri.e2e.conf.json"))
            .expect("tauri.e2e.conf.jsonを読めること"),
    )
    .expect("tauri.e2e.conf.jsonがJSONであること");
    assert_eq!(
        e2e["identifier"], "com.annenpolka.relico.e2e",
        "SPEC STA-001 違反: 配布版(relico / com.annenpolka.relico)・通知テスト版(RELICO Notification Test / com.annenpolka.relico.notification-test)・E2E版(RELICO E2E / com.annenpolka.relico.e2e)は設定ファイル上でproductName・identifierがそれぞれ規定値を持ち、互いに一致しない (E2E identifier)"
    );
    assert_eq!(e2e["productName"], "RELICO E2E", "SPEC STA-001 違反: 配布版(relico / com.annenpolka.relico)・通知テスト版(RELICO Notification Test / com.annenpolka.relico.notification-test)・E2E版(RELICO E2E / com.annenpolka.relico.e2e)は設定ファイル上でproductName・identifierがそれぞれ規定値を持ち、互いに一致しない (E2E productName)");

    for (left, right) in [(&release, &test), (&release, &e2e), (&test, &e2e)] {
        assert_ne!(left["identifier"], right["identifier"], "SPEC STA-001 違反: 配布版(relico / com.annenpolka.relico)・通知テスト版(RELICO Notification Test / com.annenpolka.relico.notification-test)・E2E版(RELICO E2E / com.annenpolka.relico.e2e)は設定ファイル上でproductName・identifierがそれぞれ規定値を持ち、互いに一致しない (identifier衝突)");
        assert_ne!(left["productName"], right["productName"], "SPEC STA-001 違反: 配布版(relico / com.annenpolka.relico)・通知テスト版(RELICO Notification Test / com.annenpolka.relico.notification-test)・E2E版(RELICO E2E / com.annenpolka.relico.e2e)は設定ファイル上でproductName・identifierがそれぞれ規定値を持ち、互いに一致しない (productName衝突)");
    }
}

/// STA-002: トレイは専用tray-icon.pngをテンプレート画像として登録する配線を持ち、PNGはモノクロ(+アルファ)形式である
#[test]
fn sta_002() {
    let manifest = std::path::Path::new(env!("CARGO_MANIFEST_DIR"));
    let bytes = std::fs::read(manifest.join("icons/tray-icon.png"))
        .expect("icons/tray-icon.pngを読めること");
    assert_eq!(
        &bytes[..8],
        &[0x89, b'P', b'N', b'G', 0x0D, 0x0A, 0x1A, 0x0A],
        "SPEC STA-002 違反: トレイは専用tray-icon.pngをテンプレート画像として登録する配線を持ち、PNGはモノクロ(+アルファ)形式である (PNGシグネチャ)"
    );
    // IHDRのcolor type: 0=grayscale / 4=grayscale+alpha だけをテンプレート互換とする
    let color_type = bytes[25];
    assert!(
        color_type == 0 || color_type == 4,
        "SPEC STA-002 違反: トレイは専用tray-icon.pngをテンプレート画像として登録する配線を持ち、PNGはモノクロ(+アルファ)形式である (colortype={color_type}: モノクロ+アルファのPNGであること)"
    );

    let lib_rs = std::fs::read_to_string(manifest.join("src/lib.rs"))
        .expect("src/lib.rsを読めること");
    assert!(
        lib_rs.contains("tray-icon.png"),
        "SPEC STA-002 違反: トレイは専用tray-icon.pngをテンプレート画像として登録する配線を持ち、PNGはモノクロ(+アルファ)形式である (専用tray-icon.pngを使う配線が失われた)"
    );
    assert!(
        lib_rs.contains(".icon_as_template("),
        "SPEC STA-002 違反: トレイは専用tray-icon.pngをテンプレート画像として登録する配線を持ち、PNGはモノクロ(+アルファ)形式である (テンプレート登録の配線が失われた)"
    );
}

/// STA-003: macOS AUTOSTARTは内部のUnix実行ファイルをLaunchAgent登録せず、アプリアイコンを保持するAppleScript Login Itemとして.app bundleを登録し、旧relico.plistを一度だけ移行する配線を持つ
#[test]
fn sta_003() {
    let manifest = std::path::Path::new(env!("CARGO_MANIFEST_DIR"));
    let lib_rs = std::fs::read_to_string(manifest.join("src/lib.rs"))
        .expect("src/lib.rsを読めること");
    assert!(
        lib_rs.contains("MacosLauncher::AppleScript"),
        "SPEC STA-003 違反: macOS AUTOSTARTは内部のUnix実行ファイルをLaunchAgent登録せず、アプリアイコンを保持するAppleScript Login Itemとして.app bundleを登録し、旧relico.plistを一度だけ移行する配線を持つ (.app bundleをLogin Item登録するlauncherでない)"
    );
    assert!(
        !lib_rs.contains("MacosLauncher::LaunchAgent"),
        "SPEC STA-003 違反: macOS AUTOSTARTは内部のUnix実行ファイルをLaunchAgent登録せず、アプリアイコンを保持するAppleScript Login Itemとして.app bundleを登録し、旧relico.plistを一度だけ移行する配線を持つ (内部Unix実行ファイルをLaunchAgent登録している)"
    );
    assert!(
        lib_rs.contains("migrate_legacy_launch_agent"),
        "SPEC STA-003 違反: macOS AUTOSTARTは内部のUnix実行ファイルをLaunchAgent登録せず、アプリアイコンを保持するAppleScript Login Itemとして.app bundleを登録し、旧relico.plistを一度だけ移行する配線を持つ (旧relico.plistの移行配線がない)"
    );
    let legacy = r#"<key>Label</key><string>relico</string><key>ProgramArguments</key><array><string>/Users/test/Applications/relico.app/Contents/MacOS/relico</string></array>"#;
    assert!(
        relico_lib::autostart::is_legacy_relico_launch_agent(legacy),
        "SPEC STA-003 違反: macOS AUTOSTARTは内部のUnix実行ファイルをLaunchAgent登録せず、アプリアイコンを保持するAppleScript Login Itemとして.app bundleを登録し、旧relico.plistを一度だけ移行する配線を持つ (正規の旧plistを移行対象と認識しない)"
    );
    assert!(
        !relico_lib::autostart::is_legacy_relico_launch_agent(
            r#"<key>Label</key><string>other</string><key>ProgramArguments</key><array><string>/tmp/other</string></array>"#,
        ),
        "SPEC STA-003 違反: macOS AUTOSTARTは内部のUnix実行ファイルをLaunchAgent登録せず、アプリアイコンを保持するAppleScript Login Itemとして.app bundleを登録し、旧relico.plistを一度だけ移行する配線を持つ (無関係な同名plistを移行対象にした)"
    );
}

/// AST-001: メニューバー用tray-icon.pngは目視承認済みの内容から変わっていない(変えたらMAN-005の手順で再承認しsha256を更新する)
#[test]
fn ast_001() {
    use sha2::{Digest, Sha256};
    let manifest = std::path::Path::new(env!("CARGO_MANIFEST_DIR"));
    let bytes = std::fs::read(manifest.join("icons/tray-icon.png"))
        .expect("承認済みアセット icons/tray-icon.png を読めること");
    let digest = format!("{:x}", Sha256::digest(&bytes));
    assert_eq!(
        digest, "6c467d92f9e08cec513d62012765aebd1807f5d41589c8fabf50c7027096162a",
        "SPEC AST-001 違反: メニューバー用tray-icon.pngは目視承認済みの内容から変わっていない(変えたらMAN-005の手順で再承認しsha256を更新する) — icons/tray-icon.png が承認済み内容から変わった。見た目を目視で再承認し、specs/notifier.pkl のsha256を更新して just spec-gen すること"
    );
}

/// AST-002: 配布用アプリアイコンicon.icnsは目視承認済みの内容から変わっていない(変えたらMAN-006の手順で再承認しsha256を更新する)
#[test]
fn ast_002() {
    use sha2::{Digest, Sha256};
    let manifest = std::path::Path::new(env!("CARGO_MANIFEST_DIR"));
    let bytes = std::fs::read(manifest.join("icons/icon.icns"))
        .expect("承認済みアセット icons/icon.icns を読めること");
    let digest = format!("{:x}", Sha256::digest(&bytes));
    assert_eq!(
        digest, "3b5771fafbd7068879d5ed783b7b66c91acb60d75fd922ca8474df56e9edfb97",
        "SPEC AST-002 違反: 配布用アプリアイコンicon.icnsは目視承認済みの内容から変わっていない(変えたらMAN-006の手順で再承認しsha256を更新する) — icons/icon.icns が承認済み内容から変わった。見た目を目視で再承認し、specs/notifier.pkl のsha256を更新して just spec-gen すること"
    );
}
