// @generated by tools/spec-gen.ts from specs/notifier.pkl — DO NOT EDIT
// テストを直したくなったら specs/ を編集して `just spec-gen` を実行する。
// 実行: bun test tests/unit

import { expect, test } from "bun:test";
import { candidateGlyphHtml, glyphHtml, planetForFissure, type GlyphKind } from "../../src/icons";

// ICN-001: 既知のTier・惑星・ミッション・ファクション・難易度・VOID嵐・アクション値には汎用と区別できる専用SVGグリフが割り当てられ、未知値はカテゴリ別の汎用グリフへフォールバックし、グリフは装飾(aria-hidden)である
test("ICN-001 icn_001", () => {
  const pools: Array<[GlyphKind, string[]]> = [
    ["tier", ["Lith","Meso","Neo","Axi","Requiem","Omnia"]],
    ["planet", ["Mars","Ceres","Sedna","Void","Saturn","Phobos","Zariman","Veil Proxima","Kuva Fortress","Lua"]],
    ["mission", ["Defense","Survival","Capture","Extermination","Rescue","Disruption","Mobile Defense","Void Flood","Void Cascade","Volatile"]],
    ["faction", ["Grineer","Corpus","Infested","Orokin","Corrupted","Murmur"]],
    ["difficulty", ["Normal","SteelPath","Both"]],
    ["storm", ["Exclude","Include","Only"]],
    ["action", ["new-rule","delete-rule","clear","pause"]],
  ];
  for (const [kind, values] of pools) {
    // 未知値はカテゴリ別の汎用グリフへフォールバックし、例外を出さない
    const generic = glyphHtml(kind, "__unknown-value__");
    expect(generic).toContain('aria-hidden="true"');
    expect(generic).toContain("viewBox");
    for (const value of values) {
      const html = glyphHtml(kind, value);
      // 既知値には汎用と区別できる専用グリフが割り当てられている
      expect(html).toContain('aria-hidden="true"');
      expect(html).not.toBe(generic);
    }
  }
  // パレット候補のfacet→グリフ種の写像(modeはdifficultyグリフを使う)
  expect(candidateGlyphHtml("mode", "mode:SteelPath")).toBe(glyphHtml("difficulty", "SteelPath"));
  expect(candidateGlyphHtml("tier", "tier:Axi")).toBe(glyphHtml("tier", "Axi"));
  expect(candidateGlyphHtml("storm", "storm:Only")).toBe(glyphHtml("storm", "Only"));
});

// ICN-002: 表示用惑星名はVOID嵐のときだけEarth/Venus/Saturn/Neptune/Pluto/VeilをProxima表記へ寄せ、通常亀裂・その他の惑星・欠損値はそのまま返す
test("ICN-002 icn_002", () => {
  for (const planet of ["Earth","Venus","Saturn","Neptune","Pluto","Veil"]) {
    expect(planetForFissure(planet, true)).toBe(planet + " Proxima");
    expect(planetForFissure(planet, false)).toBe(planet);
  }
  expect(planetForFissure("Mars", true)).toBe("Mars");
  expect(planetForFissure("  Earth  ", true)).toBe("Earth Proxima");
  expect(planetForFissure(null, true)).toBe("");
  expect(planetForFissure(null, false)).toBe("");
});
